- helm_deploy/values-dev.yaml
This was incorrectly renamed from the typescript template
> Use correct ingress host

- package-lock.json
- package.json
We don't have any git hooks configured with Husky and don't use lint-staged anywhere
This removes the Husky/lint-staged files that remain
> Remove Husky and lint-staged

- .github/PULL_REQUEST_TEMPLATE.md
This checklist item is appearing with line breaks as per the code when in a PR description (but not if you just view the template on GitHub), which is not what we want
Though it's best to keep lines short, we'll make an exception here to make it show up properly on PR descriptions
> Fix PR template styling

- server/@types/models/Course.ts
- server/@types/models/CourseOffering.ts
- server/testutils/factories/course.ts
- server/testutils/factories/courseOffering.ts
- wiremock/stubs/courseOfferings.json
- wiremock/stubs/courses.json
We have a few model fields that are artefacts from earlier designs and no longer needed
Remove unused model fields
> (458) Remove unused model fields

- integration_tests/pages/find/course.ts
- integration_tests/pages/page.ts
- integration_tests/support/commands.ts
- integration_tests/tsconfig.json
- server/@types/express/index.d.ts
- server/config.ts
- server/controllers/find/coursesController.ts
- server/data/hmppsAuthClient.test.ts
- server/data/prisonClient.test.ts
- server/data/prisonClient.ts
- server/data/restClient.ts
- server/data/restClientMetricsMiddleware.test.ts
- server/data/tokenStore.test.ts
- server/data/tokenStore.ts
- server/data/tokenVerification.test.ts
- server/data/tokenVerification.ts
- server/middleware/setUpWebSecurity.ts
- server/sanitisedError.ts
- server/services/organisationService.test.ts
- server/services/userService.test.ts
- server/utils/azureAppInsights.ts
- server/utils/typeUtils.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- tsconfig.json
https://trello.com/c/drGFfal5/454-use-strict-typing-for-typescript
This turns on strict TypeScript compilation to ensure we're getting the most Type safety we can while using TypeScript.
To get this to all compile successfully, we add a bunch of guards, type assertions etc.
> (454) Turn on strict TypeScript compilation

- helm_deploy/hmpps-accredited-programmes-ui/values.yaml
- helm_deploy/values-dev.yaml
- package-lock.json
- package.json
- server/app.ts
- server/applicationVersion.ts
- server/config.ts
- server/middleware/setUpSentry.ts
https://trello.com/c/jZYDnjEO/395-add-sentry-to-ui-and-api-for-logging-errors
This adds the relevant middleware for notifying us of any errors in live environments (currently just dev, but in future prod and pre-prod) on Sentry.io
This has required adding a `SENTRY_DSN` variable to the deployed environment which points to our project on Sentry.
> (395) Add and configure Sentry

- server/routes/index.ts
This is a temporary route that will throw an error so we can confirm our sentry config is working as expected.
> Add test sentry error route

- integration_tests/e2e/find.cy.ts
- integration_tests/mockApis/courses.ts
- integration_tests/pages/find/course.ts
- integration_tests/pages/find/courseOffering.ts
- integration_tests/pages/find/index.ts
- integration_tests/pages/page.ts
- server/@types/ui/index.d.ts
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/courseOfferingsController.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/controllers/index.ts
- server/data/courseClient.test.ts
- server/data/courseClient.ts
- server/data/prisonClient.test.ts
- server/data/prisonClient.ts
- server/paths/api.ts
- server/paths/find.ts
- server/routes/index.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- server/services/organisationService.test.ts
- server/services/organisationService.ts
- server/testutils/factories/index.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
- server/views/courses/offerings/show.njk
- wiremock/scripts/stubApis.ts
- Add course offering page
- Refactor various bits of code as groundwork
> (361) Course offering page

- integration_tests/mockApis/auth.ts
- integration_tests/pages/find/course.ts
- integration_tests/pages/find/courseOffering.ts
- integration_tests/pages/find/courses.ts
- integration_tests/pages/page.ts
- server/@types/ui/index.d.ts
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/courseOfferingsController.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
- server/views/courses/_audienceTags.njk
- server/views/courses/_indexCourseSummary.njk
- server/views/courses/index.njk
- server/views/courses/offerings/show.njk
- server/views/courses/show.njk
- server/views/dashboard/index.njk
- server/views/pages/error.njk
We weren't using the GOV.UK Design System heading classes
- Use GOV.UK Design System heading classes to bring things in line with the standard
- Remove redundant `p` class (inherited from `main`)
- Use class selector where it makes sense
For the heading classes, I've gone with `h1` = `l` and `h2` = `m` since we did have one `h1` that was an `l`. We could go `xl` and `l` instead though. On Approved Premises there are 62 `h1`s with `l` and 7 with `xl`, and 18 `h2`s with `m`, 4 with `l` and 4 with `s` (all `h3`s are `m`)*, so it's contextual (per the GDS guidelines) and/or inconsistent
\* this is based on searching `h1 class="govuk-heading-l"` etc - there may be some heading tags that aren't in that format
> Use govuk heading classes

- doc/how-to/manage-infrastructure.md
- doc/how-to/view-application-logs.md
Adds docs for managing infrastructure with reference to tools like Kubernetes, Kibana and the MOJ Cloud Platform Environments project.
This includes instructions for viewing logs, debugging deployments, restarting services etc.
It's very much copied and pasted/adapted from the Community Accommodation team's guidance
[here](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4325244964/Manage+infrastructure)
> (332) Add docs for managing infrastructure

- .github/PULL_REQUEST_TEMPLATE.md
- doc/adr/0004-release-with-continuous-deployment.md
- doc/how-to/perform-a-release.md
- doc/how-to/view-application-logs.md
https://trello.com/c/NBRchTqI/333-decide-and-document-an-approach-for-production-deployments
This PR adds an ADR to document our decision to release with continuous deployment (if accepted).
It also adds documentation for how to actually perform a release.
As always, it's heavily influenced by (and copied from) the approach taken by the CAS teams, outlined [here](https://dsdmoj.atlassian.net/wiki/spaces/MRD/pages/4228547717/Release+process).
> (333) Document our release process

- .github/PULL_REQUEST_TEMPLATE.md
This PR description had some lines that were cut off due to line wrapping and looked a bit strange.
This fixes the line wrapping and clears up one or two more bits of whitespace.
release to preprod
release to prod
> Fix formatting in PR template

- server/middleware/setUpSentry.ts
https://trello.com/c/7wzlt3M4/564-improve-sentry-configuration
- Anonymises usernames in Sentry, replacing them with a random number, as other MOJ teams have done
- Adds tracing to allow us to follow a request across multiple services
- Adds sampling to ensure we're not logging every single request on non-production environments
> (564) Improve Sentry configuration

- integration_tests/e2e/app.cy.ts
- integration_tests/e2e/authentication.cy.ts
- integration_tests/e2e/health.cy.ts
- integration_tests/pages/find/courseOffering.ts
- integration_tests/pages/page.ts
- integration_tests/support/helpers.ts
- server/views/partials/layout.njk
We should have a phase banner identifying the service as being in beta and providing a link to provide feedback, in support of the Service Standard
- Add phase banner with feedback link
- Refactor some of the integration test code in support of this/as a general tidy up
> (570) Add phase banner

- integration_tests/pages/find/course.ts
- server/@types/ui/index.d.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
- server/views/courses/_locationsTable.njk
We haven't had time to add category to the Prison Register API yet, and we're due to launch a private beta soon
- Remove category from views and helpers where necessary, while retaining it in the rest of the code as much as possible for when it's ready to be visible
- [N/A] ... and I have written or updated an end-to-end test for the happy path in the [Accredited Programmes E2E repo](https://github.com/ministryofjustice/hmpps-accredited-programmes-e2e)
> (586) Remove prison category

- server/@types/ui/index.d.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
- server/views/courses/_locationsTable.njk
The field we were using for region was actually county, and we don't have immediate plans to change this to actual regions
The county field is relabelled from "region" to "county" for accuracy/to avoid confusion
> (588) Rename "region" "county"

- integration_tests/e2e/find.cy.ts
- integration_tests/mockApis/courses.ts
- integration_tests/pages/find/course.ts
- integration_tests/pages/find/courses.ts
- server/controllers/find/courseOfferingsController.ts
- server/controllers/find/coursesController.ts
- server/data/courseClient.test.ts
- server/data/courseClient.ts
- server/paths/api.ts
- server/paths/find.ts
- server/services/courseService.ts
- server/services/organisationService.ts
- server/utils/organisationUtils.ts
- wiremock/scripts/stubApis.ts
We prefer to use explicit IDs where possible
Use explicit IDs where possible. Not sure how useful the second commit is
> (500) Explicit IDs

- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
The title in the header reads "HMPPS HMPPS Accredited Programmes"
Remove the duplicate "HMPPS" from the `applicationName` and add it into the page title separately
Will this affect any CI/CD stuff or Slack integrations?
> Fix header title

- integration_tests/e2e/find.cy.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
Courses don't come back in any order from the API, so we should sort them in the UI to make it easier for users to navigate.
This sorts courses alphabetically on the main index page.
> Sort list of courses alphabetically

- integration_tests/pages/find/courseOffering.ts
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/courseOfferingsController.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
Adding an email subject with the organisation and course names will help with analytics
Do that ^
> (597) Add mailto subject for referrals

- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
The `mailto` links' subjects weren't working properly when there was an ampersand included in an organisation name
This encodes the subject in a `mailto` link to avoid an ampersand being parsed as starting a new query parameter
In the tests, we found that even when modifying a duplicated object (duplicated with `{ ...object }`), it was modifying the original values. We've moved to `beforeEach` to reset the data properly regardless of any example-specific modification
The default organisation name is also updated here from `HMP What` to `What (HMP)` to match the format of the real data
> (597b) Encode ampersand in `mailto` link

- .circleci/config.yml
In f74fcf7 we disabled the E2E tests due to mismatches with the data on dev, which were undergoing frequent changes. The data are now more stable, so we're ready to re-enable the E2E tests once fixed (in a [related PR][1])
- Re-enable E2E test step in CI
[1]: https://github.com/ministryofjustice/hmpps-accredited-programmes-e2e/pull/3
> (569b) Restore E2E tests

- integration_tests/e2e/find.cy.ts
- integration_tests/pages/page.ts
- server/utils/nunjucksSetup.ts
- server/views/courses/offerings/show.njk
- server/views/courses/show.njk
- server/views/partials/layout.njk
The design includes back links on the course show and course offering show pages
Add in back links where needed
[Video](https://www.youtube.com/watch?v=0Q14rHLvMco)
> (633) Back links

- .circleci/config.yml
Our E2E tests are currently not running on CI due to the following warning:
```
Looks like Playwright Test or Playwright was just updated to 1.36.2.
Please update docker image as well.
- current: mcr.microsoft.com/playwright:v1.34.2-focal
- required: mcr.microsoft.com/playwright:v1.36.2-focal
```
Updates the Playwright docker image in an attempt to get these tests to run again.
> FIX: Update Playwright docker image on CI

- integration_tests/e2e/find.cy.ts
- integration_tests/pages/page.ts
- server/@types/models/CourseOffering.ts
- server/@types/ui/index.d.ts
- server/testutils/factories/courseOffering.ts
- server/utils/courseUtils.ts
- server/utils/organisationUtils.test.ts
- wiremock/stubs/courseOfferings.json
I left a few comments on #119 post-merge
Fix the comments, most significantly the secondary contact email issue. I left the more subjective https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/119#discussion_r1263608057 for now (whether it's the responsibility of the integration tests to care about whether secondary contact email specifically is in the summary list)
> (617) Fix secondary contact email

- assets/scss/application.scss
- assets/scss/components/_dashboard.scss
- assets/scss/components/_navigation.scss
- assets/scss/helpers.scss
- integration_tests/e2e/app.cy.ts
- integration_tests/e2e/find.cy.ts
- integration_tests/pages/page.ts
- server/utils/nunjucksSetup.ts
- server/views/dashboard/index.njk
- server/views/partials/applicationInsightsScript.njk
- server/views/partials/layout.njk
The designs have a navigation menu with "List of programmes" and "My cases". The latter doesn't currently have a corresponding page in our service, but the former does
This is part one of (probably) two PRs to introduce the refer start page
- Add the navigation with a "List of programmes" link
- A few iterations in the same area of code
Courses page:
Course page:
Dashboard page (no change):
Courses page:
Course page:
Dashboard page (no change):
> (642a) Add navigation

- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/pages/refer/confirmPerson.ts
- integration_tests/pages/refer/findPerson.ts
- integration_tests/pages/refer/startReferral.ts
- script/test-history
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/refer/peopleController.test.ts
- server/controllers/refer/peopleController.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/utils/nunjucksSetup.ts
- server/utils/routeUtils.ts
- server/views/courses/offerings/show.njk
- server/views/courses/show.njk
- server/views/partials/layout.njk
- server/views/referrals/new.njk
- server/views/referrals/people/show.njk
- server/views/referrals/start.njk
We have the referral start page and the person show page, but we're missing the referral new/person search page in the middle
- Add the referral new/person search page
- Various related iterations
https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/assets/40244233/633cada1-70f1-4ffa-98b0-676b2fa8a22a
> (643) Find a person

- server/middleware/setUpWebSecurity.ts
On dev, the new referral page isn't allowing us to submit the form and/or is logging us out on submission due to a redirect
- Allow internal and HMPPS Auth redirects from forms
> (643b) Allow internal redirects from forms

- server/@types/models/Referral.ts
- server/@types/models/index.d.ts
- server/testutils/factories/index.ts
- server/testutils/factories/referral.ts
We're currently building the Refer journey and will need a UI type to represent a Referral object.
This adds a very barebones Referral model to the codebase, alongside a factory for generating one.
We'll likely be adding additional fields to this very soon, but this allows us to share the new objects while working on the new functionality in parallel.
> Add barebones Referral model and factory

- .eslintrc.json
- integration_tests/e2e/find.cy.ts
- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/find.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/courses.ts
- integration_tests/pages/find/course.ts
- integration_tests/pages/find/courseOffering.ts
- integration_tests/pages/refer/confirmPerson.ts
- integration_tests/pages/refer/startReferral.ts
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/courseOfferingsController.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/controllers/refer/peopleController.test.ts
- server/controllers/refer/peopleController.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/data/courseClient.test.ts
- server/data/courseClient.ts
- server/paths/api.ts
- server/paths/find.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
- server/views/courses/offerings/show.njk
- server/views/referrals/new.njk
- server/views/referrals/people/show.njk
- server/views/referrals/start.njk
The Refer URLs are getting very long, which makes it hard to use the URL to work out where you are
- Shorten the paths
- Tidy up some ESLint stuff
> (701) Shorten paths

- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/pages/refer/index.ts
- integration_tests/pages/refer/taskList.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/views/referrals/show.njk
https://trello.com/c/v4tXjn7m/720-build-basic-referral-template
Adds a template referral form page
This is a placeholder page with the course name, prison location and strand that we'll be building on in the next few PRs.
It's currently available at `/offerings/:offeringId/referrals/:referralId`, although the `referralId` isn't used yet.
I've kept it as simple as possible to allow us to get it up and running quickly.
> Add template referral form page

- integration_tests/e2e/refer.cy.ts
- integration_tests/pages/refer/findPerson.ts
https://trello.com/c/TovAzIoK/732-add-integration-test-for-searching-for-a-user-when-making-a-referral
We recently #148 added functionality for finding a person to be referred to an Accredited programme. The journey for finding a user and then showing them were added in piecemeal PRs, so we neglected to test the whole journey as a joined-up user experience.
Combines integration tests to give us a more complete user journey when testing the application.
We're only testing the happy path here, as we've not yet got any custom behaviour for showing error messages if a user isn't found, but we'll add test cases to cover that scenario when we add those error messages in the near future.
As part of our continuous deployment …
> (732) Test joined up journey for looking up a person in prison from the Prisoner Offender Search

- assets/scss/application.scss
- assets/scss/components/_task-list.scss
- integration_tests/e2e/refer.cy.ts
- integration_tests/pages/page.ts
- integration_tests/pages/refer/taskList.ts
- server/@types/ui/index.d.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/utils/index.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/_taskListSection.njk
- server/views/referrals/show.njk
Our task list page is currently without task list. We don't yet have all the fields on our referral model needed to make a fully functional task list, but we'd like to build out the template now so that it's ready for fleshing out later on (i.e. adding the appropriate form page links and updating the statuses based on the presence of fields on the referral
- Add basic task list
> (719) Add basic task list

- integration_tests/mockApis/courses.ts
- server/controllers/find/courseOfferingsController.ts
- server/controllers/refer/referralsController.ts
- server/data/courseClient.test.ts
- server/data/courseClient.ts
- server/paths/api.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- wiremock/scripts/stubApis.ts
The API now has a `/offerings/:offeringId` endpoint, which allows us to get to offerings without needing its course
The CI will fail until #168 is merged
- Update offering endpoint
> (718b) Update offering endpoint

- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/pages/refer/checkAnswers.ts
- integration_tests/pages/refer/index.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/checkAnswers.njk
New check answers page for referrals.  Contains application summary and personal details summary lists.
N/A
> (651) Check answers page for referrals

- README.md
- wiremock/scripts/stubApis.ts
#180 updated the README, but one thing didn't work as expected and another was inaccurate
- Update Wiremock stubs so that mocked API local development documentation is accurate
- Fix link to seeded referral
> Update README and stubs

- server/@types/models/Referral.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/testutils/factories/referral.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
- server/views/referrals/complete.njk
This page will be redirected to from an upcoming submit referral endpoint.
- Updated `Referral` type to include `status`
- Added `feedbackUrl` as nunjucks global to be used in multiple places
- Add complete page template
- Added complete method to referral controller
- Added `/complete` path for referral journey
N/A
> (650b) Complete referral page

- server/views/referrals/checkAnswers.njk
Fixes a couple of small issues that have creeped in:
- orphaned `div` - no closing tag
- de-indentation
> Fix check answers markup

- .djlintrc
- .vscode/extensions.json
- .vscode/settings.json
In 6f5f8a4, I said that the formatter removes whitespace around variables, but that doesn't seem to be the case (at least not anymore). In that commit, I disabled a djLint rule that conflicted with this, but with it not being the case there's no need to go against the djLint rule here (and it's one that we're already following/compliant with!)
**Possible to do:** document how to get Nunjucks language associations set up in VSCode. Possibly by adding `ronnidc.nunjucks` to `.vscode/extensions.json` or some kind of `files.associations` setting to `.vscode/settings.json`
- Re-enable djLint rule
> Update Nunjucks configuration

- assets/scss/local.scss
- integration_tests/e2e/refer.cy.ts
- integration_tests/pages/refer/checkAnswers.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/views/referrals/checkAnswers.njk
https://trello.com/c/bn9fpBhE/843-add-reason-for-referral-and-confirm-oasys-to-the-check-your-answers-page
Add OASys confirmation message and the provided additional information content to the check your answers page.
> (843) Add OASys confirmation and Additional information to check answers page

- .eslintrc.json
- package.json
- server/@types/models/Referral.ts
- server/@types/ui/index.d.ts
- server/data/prisonClient.test.ts
- server/data/prisonClient.ts
- server/data/prisonerClient.test.ts
- server/data/prisonerClient.ts
- server/data/restClient.ts
- server/services/organisationService.test.ts
- server/services/organisationService.ts
- server/services/personService.test.ts
- server/services/personService.ts
- server/testutils/factories/course.ts
- server/testutils/factories/courseOffering.ts
- server/testutils/factories/factoryHelpers.ts
- server/utils/appInsightsUtils.test.ts
- server/utils/routeUtils.ts
A few small refactors/tidy ups made on the way to the course participations index. Separated into a separate PR to avoid a mega one
> Miscellaneous

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/tsconfig.json
- server/@types/prisonApi/index.d.ts
- server/config.ts
- server/data/caseloadClient.test.ts
- server/data/caseloadClient.ts
- server/data/index.ts
- server/paths/index.ts
- server/paths/prisonApi.ts
- server/testutils/factories/caseload.ts
- server/testutils/factories/index.ts
- tsconfig.json
https://trello.com/c/PeLVF8dJ/814-ensure-referrers-cant-refer-people-outside-their-active-caseload-ui
Users should be restricted to only viewing the details of people in a prison that's in their caseload. To fetch a user's caseload, we need to call the relevant endpoint on the Prison API with their Staff ID.
Adds a CaseloadClient for fetching a user's caseloads, alongside config for the Prison API.
This currently isn't used, and we'll need to add stubs/run this locally with docker-compose, but that can come in a future PR when we actually need to use the client.
> (814a) Add Caseload client and Prison API config

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
These slipped in in #223.
Removes trailing slashes from Prison API URLs.
> Remove trailing slashes from Prison API URLs

- integration_tests/e2e/find.cy.ts
- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/find.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/courses.ts
- package.json
- server/@types/models/CourseParticipation.ts
- server/@types/models/index.d.ts
- server/routes/refer.ts
- server/testutils/factories/courseParticipation.ts
- server/testutils/factories/courseParticipationOutcome.ts
- server/utils/referralUtils.ts
- server/utils/stringUtils.test.ts
- server/utils/stringUtils.ts
- server/views/referrals/courseParticipations/new.njk
- server/views/referrals/showPerson.njk
- wiremock/scripts/stubApis.ts
- wiremock/stubs/courseParticipations.json
- wiremock/stubs/index.ts
- wiremock/stubs/referrals.json
- Various small fixes, tidy ups and refactors in preparation for the final PR to land 703
> (703c) Assorted prehistoric delights

- .eslintrc.json
- integration_tests/e2e/find.cy.ts
- integration_tests/e2e/refer.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/pages/authError.ts
- integration_tests/tsconfig.json
- server/@types/server/index.d.ts
- server/middleware/index.ts
- server/middleware/populateCurrentUser.test.ts
- server/middleware/populateCurrentUser.ts
- server/middleware/roleBasedAccessMiddleware.test.ts
- server/middleware/roleBasedAccessMiddleware.ts
- server/routes/refer.ts
- server/utils/routeUtils.ts
- server/views/autherror.njk
- server/views/courses/offerings/show.njk
- tsconfig.json
We need to restrict access to anything referral related to users with the `ACP_REFERRER` role/authority.
https://trello.com/c/2K0xmD3j/800-restrict-being-able-to-make-a-referral-to-only-those-with-accredited-programme-referrer-permissions-ui-api
Created a new `roleBasedAccessMiddleware` which accepts an options parameter with an `allowedRoles` Array.  We can then use this in each of the routes to restrict access to routes to users with only the specified, allowed roles.
Also updates res.locals.user to include an `hasReferrerRole` property which can be used in the templates.
> (800) Add role based access and apply to refer

- cypress.config.ts
- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/courseParticipations.ts
- integration_tests/pages/page.ts
- integration_tests/pages/refer/index.ts
- integration_tests/pages/refer/programmeHistory.ts
- server/@types/models/CourseParticipation.ts
- server/@types/models/index.d.ts
- server/@types/ui/index.d.ts
- server/controllers/refer/courseParticipationsController.test.ts
- server/controllers/refer/courseParticipationsController.ts
- server/controllers/refer/index.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/utils/courseParticipationUtils.test.ts
- server/utils/courseParticipationUtils.ts
- server/utils/index.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/courseParticipations/index.njk
This is the fourth and final PR in the journey to landing 703
Note:
- this is currently broken locally due to #208 until changes are merged into the HMPPS Auth repository
- this should not be merged until [the API is up to date](https://trello.com/c/kWwW6vM1)
- Add `CourseParticipationUtils`
- Add programme history index
Cannot get until HMPPS Auth changes are merged
Cannot get until HMPPS Auth changes are merged
> (703d) Add programme history index

- .env.example
- README.md
- Updates `.env.example` to provide working config for running the service locally.
- Adds new local users to the README
> Misc updates: update .env and document new users

- server/paths/api.ts
This should be `/people/:prisonNumber`, rather than `person/:prisonNumber` and is 404ing on dev.
Updates the route to point to the correct endpoint.
> Use correct `participationsByPersonPath`

- integration_tests/e2e/refer.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/courseParticipations.ts
- integration_tests/pages/page.ts
- integration_tests/pages/refer/index.ts
- integration_tests/pages/refer/programmeHistoryDetails.ts
- integration_tests/pages/refer/selectProgramme.ts
- server/controllers/refer/courseParticipationDetailsController.test.ts
- server/controllers/refer/courseParticipationDetailsController.ts
- server/controllers/refer/index.ts
- server/routes/refer.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- server/views/referrals/courseParticipations/details/show.njk
https://trello.com/c/oMnAOOLO/851-add-page-for-entering-course-details-ui-m
This PR contains the form page view only.  Form submission and validation is still to come.
> (851b) Course participation details page

- integration_tests/e2e/refer/programmeHistory.cy.ts
- integration_tests/mockApis/courseParticipations.ts
- integration_tests/pages/page.ts
- integration_tests/pages/refer/programmeHistory.ts
- integration_tests/pages/refer/selectProgramme.ts
- server/@types/ui/index.d.ts
- server/controllers/refer/courseParticipationsController.test.ts
- server/controllers/refer/courseParticipationsController.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/services/courseService.ts
- server/utils/courseParticipationUtils.test.ts
- server/utils/courseParticipationUtils.ts
- server/views/referrals/courseParticipations/course.njk
We can currently add a new course participation by selecting a course, then access the participation details page, but we can't edit the course for a course participation
- Allow editing/updating a course participation's course
This PR has a couple of significant abstractions and some minorly complicated `describe.each` work going on, but hopefully the order and content of the commits makes them understandable. Happy to do a run through of the PR if it would help the review process!
> (856b) Edit/update participation course

- integration_tests/e2e/find.cy.ts
- integration_tests/e2e/refer/confirmOasys.cy.ts
- integration_tests/e2e/refer/create.cy.ts
- integration_tests/e2e/refer/reason.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/e2e/refer/submit.cy.ts
- integration_tests/e2eReferDisabled/find.cy.ts
- server/controllers/find/courseOfferingsController.test.ts
- server/controllers/find/courseOfferingsController.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/controllers/refer/courseParticipationDetailsController.test.ts
- server/controllers/refer/courseParticipationDetailsController.ts
- server/controllers/refer/courseParticipationsController.test.ts
- server/controllers/refer/courseParticipationsController.ts
- server/controllers/refer/oasysConfirmationController.test.ts
- server/controllers/refer/oasysConfirmationController.ts
- server/controllers/refer/peopleController.test.ts
- server/controllers/refer/peopleController.ts
- server/controllers/refer/reasonController.test.ts
- server/controllers/refer/reasonController.ts
- server/controllers/refer/referralsController.test.ts
- server/controllers/refer/referralsController.ts
- server/services/courseService.test.ts
- server/services/organisationService.test.ts
- server/services/organisationService.ts
- server/services/personService.test.ts
- server/services/personService.ts
- server/utils/organisationUtils.test.ts
- server/utils/organisationUtils.ts
We're writing a lot of very similar error-handling tests because of resolving client errors in controllers
- Simplify `organisationFromPrison` util method
- Handle errors in finding people/organisations in service
- Fix an error code
> (831) Handle errors in services

- integration_tests/e2e/refer/programmeHistory.cy.ts
- server/controllers/refer/courseParticipationDetailsController.test.ts
- server/controllers/refer/courseParticipationDetailsController.ts
- server/views/referrals/courseParticipations/details/show.njk
Go back to `/referrals/:referralId/programme-history/:courseParticipationId/programme` so you can change the previously selected course.
> Update back link on programme history details page

- integration_tests/e2e/refer/programmeHistory.cy.ts
- integration_tests/pages/refer/programmeHistory.ts
- server/controllers/refer/courseParticipationDetailsController.test.ts
- server/controllers/refer/courseParticipationsController.test.ts
- server/views/referrals/courseParticipations/details/show.njk
A few fixes/tidy ups etc taken out of the final 853 branch to reduce PR size
See commits. Not confusion in "Fix expectation" - we might want to work out what was going on there
> (853c) Fixes and tidy ups

- docker-compose-test.yml
- docker-compose.yml
The Docker Compose file was getting even more chaotic than before
Basic tidy ups of the two Docker Compose files
> Tidy up docker compose

- doc/adr/0006-use-git-commits-to-explain-our-work.md
We should capture our ways of working as much as possible to make it easier for new developers to get up to speed on our preferred approaches. We place a lot of emphasis on writing good git commit messages to document our codebase for future readers and make code review as easy as possible for the reviewer.
Adds an ADR for how we should use Git on the project, copied from [the Interventions team's ADR](https://github.com/ministryofjustice/hmpps-architecture-as-code/commit/8f2eaf725df892485a6e6cd9e82470ccf791adc9)
> Add ADR for how we should use Git

- integration_tests/mockApis/manageUsers.ts
- integration_tests/tsconfig.json
- server/@types/manageUsersApi/index.d.ts
- server/@types/users/index.d.ts
- server/data/hmppsManageUsersClient.test.ts
- server/data/hmppsManageUsersClient.ts
- tsconfig.json
Add types from [manage-users-api](https://github.com/ministryofjustice/hmpps-manage-users-api) to new `@manage-users-api` tsconfig path, to keep this separate from the types elsewhere local to this app.
> User types tidy - Add `@manage-users-api`

- server/data/courseClient.test.ts
https://trello.com/c/gB76GqkW/788-add-missing-pact-contract-tests-referrals-and-courseparticipations-api-s
We've had our Pact tests disabled for some time as we were getting up and running quickly. Now we're turning them back on, there are a few that are out of date and need fixing.
- Updates the Pact tests to match existing behaviour of the API.
- Ensures API tests can be run in any order.
> Update pact tests

- server/data/courseClient.test.ts
- server/data/referralClient.test.ts
We're fixing some failing Pact tests on the API
Adds a couple of tweaks to Pact expectations to line them up with what the Provider (API) is sending.
> Update pact tests 2

- server/paths/refer.ts
> Fix typo in paths

- cypress.config.ts
- integration_tests/e2e/refer/submitted.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/mockApis/sentenceInformation.ts
- integration_tests/pages/refer/index.ts
- integration_tests/pages/refer/submitted/sentenceInformation.ts
- script/utils/start-backing-services
- server/controllers/shared/index.ts
- server/controllers/shared/submittedReferralsController.test.ts
- server/controllers/shared/submittedReferralsController.ts
- server/routes/refer.ts
- server/services/index.ts
- server/services/sentenceInformationService.test.ts
- server/services/sentenceInformationService.ts
- server/utils/index.ts
- server/utils/sentenceInformationUtils.test.ts
- server/utils/sentenceInformationUtils.ts
- server/views/referrals/submitted/sentenceInformation.njk
- wiremock/scripts/stubSentenceAndOffenceDetails.ts
- wiremock/stubs/index.ts
- wiremock/stubs/prisoners.json
- wiremock/stubs/sentenceAndOffenceDetails.json
- Add sentence information page with sentence details summary card (release dates to follow
> (889b) Add sentence information page

- integration_tests/e2e/refer/submitted.cy.ts
- integration_tests/pages/page.ts
- server/@types/models/Referral.ts
- server/controllers/shared/submittedReferralsController.test.ts
- server/controllers/shared/submittedReferralsController.ts
- server/testutils/factories/referral.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/submitted/partials/layout.njk
- Show date referred when viewing submitted referral
> (1035) Show date referred

- integration_tests/e2e/refer/submit.cy.ts
- integration_tests/pages/refer/complete.ts
- server/views/referrals/complete.njk
The content on the referral completed page was out of date, and the integration tests weren't fully written
- Update referral completed page content
- Flesh out integration tests
> (970) Correct complete content

- integration_tests/e2e/refer/show.cy.ts
- integration_tests/e2eReferDisabled/refer.cy.ts
- integration_tests/pages/refer/index.ts
- integration_tests/pages/refer/show/additionalInformation.ts
- server/controllers/shared/referralsController.test.ts
- server/controllers/shared/referralsController.ts
- server/routes/refer.ts
- server/views/referrals/show/additionalInformation.njk
https://trello.com/c/LXCt2U2V/895-add-page-for-viewing-a-referrals-additional-information-s
Adds page for viewing additional information on a submitted referral
> (895) Add page to view submitted referral additional info

- integration_tests/tsconfig.json
- server/@types/hmppsAuth/index.d.ts
- server/controllers/refer/new/additionalInformationController.test.ts
- server/controllers/refer/new/additionalInformationController.ts
- server/controllers/refer/new/courseParticipationDetailsController.test.ts
- server/controllers/refer/new/courseParticipationDetailsController.ts
- server/controllers/refer/new/courseParticipationsController.test.ts
- server/controllers/refer/new/courseParticipationsController.ts
- server/controllers/refer/new/oasysConfirmationController.test.ts
- server/controllers/refer/new/oasysConfirmationController.ts
- server/controllers/refer/new/referralsController.test.ts
- server/controllers/refer/new/referralsController.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/data/hmppsAuthClient.ts
- server/data/prisonerSearchClient.ts
- server/services/index.ts
- server/services/referralService.test.ts
- server/services/referralService.ts
- tsconfig.json
https://trello.com/c/VxKOqk1u/803-use-system-token-to-communicate-with-api-m
We've had a new role added to secure our API endpoints (`ACCREDITED_PROGRAMMES_API`). This will require authenticating with client credentials, so we need to use our system token rather than the usual user token.
Uses the system token for the Referral Client. There are a few clients we'll need to update, which will mean a lot of code changes, so I'm splitting them out into multiple PRs.
I've split this PR up into lots of commits to hopefully keep it easier to review, but I'll squash them together once it's been approved to ensure we don't have any failing tests on a commit.
As part of our continuous deployment strategy we must ensure that this …
> (803a) Use system token rather than user token for calls to Accredited Programmes API - Referral Client

- server/@types/ui/index.d.ts
- server/services/personService.test.ts
- server/services/personService.ts
- server/testutils/factories/offenceDto.ts
- server/testutils/factories/offenceHistoryDetail.ts
We need to get the active offence history for a person and return the index/most serious offence a long with the additional offences.
Added a service which makes a call to get the `offenceHistory` from an offender booking, and then make an additional call for each of the offences, using the `offenceCode`, to get the `description` and `statuteCode.description` and merge them together.  
It then returns an object with `indexOffence` (`mostSerious === true`) and `additionalOffences` sorted in descending order by `offenceDate`.
> (886d) Add `getOffenceHistory` method to `PersonService`

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/pages/page.ts
- integration_tests/pages/refer/new/checkAnswers.ts
- integration_tests/pages/shared/showReferral/additionalInformation.ts
- integration_tests/pages/shared/showReferral/programmeHistory.ts
- integration_tests/support/sharedTests.ts
- server/controllers/refer/new/referralsController.test.ts
- server/testutils/factories/offenderSentenceAndOffences.ts
- server/views/partials/keylessSummaryCard.njk
- server/views/referrals/new/checkAnswers.njk
- server/views/referrals/show/additionalInformation.njk
- server/views/referrals/show/programmeHistory.njk
A few small refactors and tidy ups before #352 
> (pre-1107 2) Refactors and tidy ups

- integration_tests/e2e/refer/show.cy.ts
- integration_tests/pages/shared/showReferral/sentenceInformation.ts
- integration_tests/support/sharedTests.ts
- server/@types/ui/index.d.ts
- server/controllers/shared/referralsController.test.ts
- server/controllers/shared/referralsController.ts
- server/utils/sentenceInformationUtils.test.ts
- server/utils/sentenceInformationUtils.ts
- server/views/referrals/show/sentenceInformation.njk
When sentence details are missing, we should display a message
- Display in-row message when some sentence details are missing
- Replace rows with message when all sentence details are missing
- Miscellaneous related updates
> (1107) No sentence details

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/shared/caseList.ts
- integration_tests/pages/shared/index.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/caseList/show.njk
Assess case list needs integration tests.
Add integration test for checking table contents.  I imagine this will be tweaked/optimised in future to be more reusable as we add more tables that are similar on both the assess and refer paths.
Also removed the default sorting on prison name/number column as this isn't required.
> (1086d) Case list integration tests

- server/data/accreditedProgrammesApi/courseClient.test.ts
The test for course offerings was out of date with the state of the API
- update the course offerings we use in this test to bring it back in sync
> (1167) Fix Pact test

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
https://trello.com/c/3n25jR0i/775-restrict-the-service-to-ips-in-preprod-and-prod-m
For security, we should have our preprod and prod environments to whitelisted IP addresses, so they're available to users at the MOJ and in prisons.
This restricts access to the site to IPs in the following groups:
- Internal
- Prisons
- Private prisons
The IPs are listed in [a config file in another repo](https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml), then published as environment variables in the `hmpps-common-vars` CircleCI context. These are fetched in the `deploy_env` job in CircleCI.
Once this is merged, we'll need to use the MOJ VPN to access these environments.
**N.B** Before merging, we'll need to investigate how this will affect our monitoring with …
> (775) Restrict preprod and prod to HMPPS group IP addresses

- .circleci/config.yml
We recently deployed changes to restrict the preprod and prod environments to specific HMPPS IP addresses, but this is currently not working on preprod.
Updates CircleCI config to use the latest HMPPS orb, following example [here](https://github.com/ministryofjustice/hmpps-adjustments/pull/95/files) as we're not able to fetch IP address groups from the CircleCI contexts.
> Use latest hmpps orb in CI to fetch IP address groups.

- assets/scss/local.scss
- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/page.ts
- integration_tests/pages/shared/caseList.ts
- server/@types/models/Referral.ts
- server/controllers/shared/caseListController.test.ts
- server/controllers/shared/caseListController.ts
- server/data/accreditedProgrammesApi/referralClient.test.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/services/referralService.test.ts
- server/services/referralService.ts
- server/testutils/factories/referralSummary.ts
- server/utils/formUtils.test.ts
- server/utils/formUtils.ts
- server/utils/referralUtils.test.ts
- server/utils/referralUtils.ts
- server/views/referrals/caseList/show.njk
https://trello.com/c/OHWmFT0d/1127-add-filters-to-assess-case-list-m
Added two filters to the top of the case list page.  This will likely be further improved (e.g. new partial for filters components) as we add more of the case list pages but struggling to think that far ahead at this stage 😄 
Have made the filters at least look presentable on smaller screens too, despite the table needing improvement.
No results error message to be done under a separate card once we have content and design.
> (1127) Add case list filters

- script/bootstrap
- script/utils/start-backing-services
A little tidy up of the scripts, things I had issues with while getting started.
> chore: minor clean up the scripts

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/mockApis/referrals.ts
- server/@types/prisonApi/imported/index.d.ts
- server/controllers/shared/caseListController.test.ts
- server/controllers/shared/caseListController.ts
- server/testutils/factories/factoryHelpers.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
A few tidy ups made in the process of writing #409, including:
- updating Prison API types (this will hopefully stop being as much of a thing in random PRs after #348 is in
- mocking in unit tests
- a factory helper
- simplifying and tightening integration tests
> (pre-1138) Tidy up

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/page.ts
- server/@types/ui/index.d.ts
- server/controllers/shared/caseListController.test.ts
- server/controllers/shared/caseListController.ts
- server/data/accreditedProgrammesApi/referralClient.test.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/services/referralService.test.ts
- server/services/referralService.ts
- server/utils/index.ts
- server/utils/paginationUtils.test.ts
- server/utils/paginationUtils.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
- server/views/referrals/caseList/show.njk
A review of a work-in-progress version of this can be found at #388
- Add pagination utils
- Add pagination to Assess case list
> (1138) Paginate case list

- server/@types/ui/index.d.ts
- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/controllers/assess/index.ts
- server/controllers/index.ts
- server/controllers/shared/index.ts
- server/routes/assess.ts
- server/utils/referrals/caseListUtils.ts
- server/utils/referrals/showReferralUtils.ts
- server/views/referrals/caseList/assess/show.njk
We need to add the case list for a users referrals.
After much thinking, I think we need 2 case list controllers, 1 for assess and 1 for refer.
This PR is to update what we currently have, to be used by assess, in anticipation for the my referral related case lists.
See draft PR #399 for what will hopefully follow on from this PR.
Also happy to wait for #388 to be merged first then will handle the rebase.
> (1137a) Update existing `CaseListController` to be `AssessCaseListController`

- server/@types/ui/index.d.ts
- server/controllers/index.ts
- server/controllers/refer/caseListController.test.ts
- server/controllers/refer/caseListController.ts
- server/controllers/refer/index.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
- server/views/partials/layout.njk
- server/views/referrals/caseList/refer/show.njk
We need to add a new **My referrals** page show referrals for the logged in use.
- Add new ReferCaseListController
- This uses the existing dashboard endpoint for the time-being, to get something displayed and working. Then in theory it should be a case of switching to the new endpoint when it exists.
- Only adds the Open tab/page
- Linked to from from the primary navigation.
Suggest we move the `/refer/new` files in another directory if we still think that's needed.
> (1137b) My referrals case list

- server/views/referrals/caseList/refer/show.njk
This shouldn't have been in here for the Refer case list
- Remove unused Refer case list column
> Remove unused case list heading

- server/@types/ui/index.d.ts
- server/controllers/shared/index.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/views/referrals/show/risksAndNeeds/offenceAnalysis.njk
- server/views/referrals/show/risksAndNeeds/partials/layout.njk
New section required to display Risks and needs
Adds new controller for Risks and needs pages/data and associated routes and template files.
> (1214a) Risks and needs - Section 2 - Offence analysis page

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/e2e/refer/caseList.cy.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/shared/caseList.ts
#441, #424, and earlier PRs developed case lists in the Refer journey, but didn't add any integration tests
- Add integration tests for Refer case lists
> (1126c) Add refer case list integration tests

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/offenceAnalysis.ts
- integration_tests/support/sharedTests.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/views/referrals/show/risksAndNeeds/offenceAnalysis.njk
When there is no offence details information from oasys for a prison number we need to still show the page with some appropriate content, rather than the standard 404 page.
When there is a 404 from the oasys endpoint, the service now returns null and we now display some a summary card with some text explaining that there are no details found.  This text will likely change.
> (1214e) Show message when there are no offence details from oasys

- server/controllers/shared/risksAndNeedsController.test.ts
- server/services/oasysService.test.ts
- server/testutils/factories/offenceDetail.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.test.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.ts
A few small things on the way to 1227, including a minor content change
> (1227a) Tidy up

- integration_tests/pages/shared/showReferral/risksAndNeeds/offenceAnalysis.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.test.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.ts
- server/utils/risksAndNeeds/roshAnalysisUtils.test.ts
- server/utils/risksAndNeeds/roshAnalysisUtils.ts
- server/views/referrals/show/risksAndNeeds/roshAnalysis.njk
Follows #456 
- Add ROSH analysis service method, utils, controller action, template, route, path etc
> (1227c) Add ROSH analysis page

- server/@types/models/Lifestyle.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/index.ts
- server/testutils/factories/lifestyle.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/lifestyleAndAssociatesUtils.test.ts
- server/utils/risksAndNeeds/lifestyleAndAssociatesUtils.ts
- server/views/referrals/show/risksAndNeeds/lifestyleAndAssociates.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/oasysLifestyle.json
https://trello.com/c/FUjaZCgu/1228-add-oasys-section-7-page-lifestyle-and-associates-m
- New `Lifestyle` type (name may change depending on what it gets called in the API)
- New client for calling `/oasys/:prisonNumber/lifestyle`
- New `OasysService` method to call client and return data, or not.
- New `RisksAndNeedsController` method for lifestyle and associates page.
- Add Section 7 - Lifestyle and associates to Risk and needs page navigation
> (1228a) Risks and needs Section 7

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/lifestyleAndAssociates.ts
- integration_tests/support/sharedTests.ts
Follows #454 
- Added integration tests for risks and needs, section 7 - lifestyle and associates page.
> (1228b) Section 7 - Lifestyle and associates integration tests

- server/@types/models/Psychiatric.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/index.ts
- server/testutils/factories/psychiatric.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/emotionalWellbeingUtils.test.ts
- server/utils/risksAndNeeds/emotionalWellbeingUtils.ts
- server/views/referrals/show/risksAndNeeds/emotionalWellbeing.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/psychiatric.json
https://trello.com/c/16oY2Li9/1229-add-oasys-section-10-page-emotional-wellbeing-m
Adds new OASys Section 10 (Emotional wellbeing) page, fetching Psychiatric data from the API.
This is accessible from both the assess and refer journeys.
This PR doesn't include integration tests, they'll come in a separate PR.
> (1229a) Add OASys Section 10 (Emotional wellbeing) page

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/emotionalWellbeing.ts
- integration_tests/support/sharedTests.ts
- server/@types/prisonApi/imported/index.d.ts
- server/@types/prisonerSearch/imported/index.d.ts
https://trello.com/c/16oY2Li9/1229-add-oasys-section-10-page-emotional-wellbeing-m
We added the emotional wellbeing page in #463, without integration tests to keep the PR small and easier to review.
- Adds integration tests for the Emotional wellbeing page
- Updates latest types from Prison API and Prisoner Search (generated by running `script/test`)
> (1229b) Add Emotional wellbeing page integration tests

- server/@types/models/Behaviour.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/behaviour.ts
- server/testutils/factories/index.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/thinkingAndBehavingUtils.test.ts
- server/utils/risksAndNeeds/thinkingAndBehavingUtils.ts
- server/views/referrals/show/risksAndNeeds/thinkingAndBehaving.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/oasysBehaviour.json
https://trello.com/c/yqRDp34z/1219-add-oasys-section-11-page-thinking-and-behaving-m
- New Behaviour type and factory
- New client for calling /oasys/:prisonNumber/behaviour
- New OasysService method to call client and return data, or not.
- New RisksAndNeedsController method for thinking and behaving page.
- Add Section 11 - Thinking and behaving to Risk and needs page navigation
> (1219a) Section 11 - Thinking and Behaving

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/thinkingAndBehaving.ts
- integration_tests/support/sharedTests.ts
- server/views/referrals/show/risksAndNeeds/thinkingAndBehaving.njk
> (1219b) Section 11 - Thinking and behaving integration tests

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/roshAnalysis.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/stringUtils.test.ts
- server/views/referrals/show/partials/rootLayout.njk
- server/views/referrals/show/risksAndNeeds/roshAnalysis.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
A few small tidy ups before the main 1234 PR
> (1234a) Pre-risks and alerts tidy up

- server/@types/models/Attitude.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/attitude.ts
- server/testutils/factories/index.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/attitudesUtils.test.ts
- server/utils/risksAndNeeds/attitudesUtils.ts
- server/views/referrals/show/risksAndNeeds/attitudes.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/oasysAttitude.json
https://trello.com/c/Cr4wZ0y9/1231-add-oasys-section-12-page-attitudes-m
- New Attitude type and factory
- New client for calling /oasys/:prisonNumber/attitude
- New OasysService method to call client and return data, or not.
- New RisksAndNeedsController method for Section 12 - Attitudes page.
- Add Section 12 - Attitudes to Risk and needs page navigation
> (1231a) Risks and Needs - Section 12 - Attitudes

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/attitudes.ts
- integration_tests/support/sharedTests.ts
> (1231b) Integration tests for Section 12 - Attitudes

- server/@types/models/LearningNeeds.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/index.ts
- server/testutils/factories/learningNeeds.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/learningNeedsUtils.test.ts
- server/utils/risksAndNeeds/learningNeedsUtils.ts
- server/views/referrals/show/risksAndNeeds/learningNeeds.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/oasysLearningNeeds.json
- Add learning needs page
Integration tests to follow in another PR
> (1233a) Add learning needs page

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/learningNeeds.ts
- integration_tests/support/sharedTests.ts
Follows #480 
- Add learning needs integration tests
> (1233b) Add learning needs integration tests

- server/@types/models/Health.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/oasysService.test.ts
- server/services/oasysService.ts
- server/testutils/factories/health.ts
- server/testutils/factories/index.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/healthUtils.test.ts
- server/utils/risksAndNeeds/healthUtils.ts
- server/views/referrals/show/risksAndNeeds/health.njk
- wiremock/scripts/stubAccreditedProgrammesApi.ts
- wiremock/stubs/index.ts
- wiremock/stubs/oasysHealth.json
https://trello.com/c/Hv7BlrdD/1232-add-oasys-section-13-page-health-m
- New `Health` type and factory
- New client for calling `/oasys/:prisonNumber/health`
- New OasysService method to call client and return data, or not.
- New RisksAndNeedsController method for Section 13 - Health page.
- Add Section 13 - Health to Risk and needs page navigation
> (1232a) Risks and needs - Section 13 - Health

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/health.ts
- integration_tests/support/sharedTests.ts
> (1232b) Section 13 - Health - Integration tests

- integration_tests/e2e/refer/new/submit.cy.ts
- integration_tests/pages/refer/new/checkAnswers.ts
- server/@types/prisonApi/imported/index.d.ts
- server/@types/prisonerSearch/imported/index.d.ts
- server/controllers/refer/new/index.ts
- server/controllers/refer/new/referralsController.test.ts
- server/controllers/refer/new/referralsController.ts
- server/utils/referrals/newReferralUtils.test.ts
- server/utils/referrals/newReferralUtils.ts
We were showing the referrer username on the check your answers page, but the full name when viewing a submitted referral
- Show the full referrer name on the check your answers page
> (1259) Show referrer name on check your answers page

- integration_tests/e2e/refer/new/additionalInformation.cy.ts
- integration_tests/pages/refer/new/additionalInformation.ts
- server/views/referrals/new/additionalInformation/show.njk
- Update additional information form page content (excluding button)
> (1106) Update additional information form page content

- integration_tests/e2e/app.cy.ts
- integration_tests/e2e/authentication.cy.ts
- integration_tests/pages/index.ts
- integration_tests/pages/page.ts
- server/controllers/dashboardController.test.ts
- server/controllers/dashboardController.ts
- server/views/dashboard/index.njk
We need to update the service landing page to reflect the different user journeys on the service, as per current designs.
- Update existing link content
- Add link to refer case lists if user has `ACP_REFERRER` role.
- Add link to assess case lists if user has `ACP_PROGRAMME_TEAM` role
Both roles:
`ACP_REFERRER` role
`ACP_PROGRAMME_TEAM` role
No roles
> (1358) Update and add new index/dashboard links

- .circleci/config.yml
- Dockerfile
Update Docker and CircleCI Node versions
> updated node version for docker and circle ci

- helm_deploy/values-preprod.yaml
> enable refer in preprod

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/page.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/statusHistory.ts
- integration_tests/support/sharedTests.ts
- server/views/referrals/show/statusHistory/show.njk
Follow on from #517 
- Integration tests for Status history page and timeline
> (1335c) Status history timeline page integration tests

- server/@types/models/Referral.ts
- server/testutils/factories/referral.ts
- server/utils/referrals/showReferralUtils.test.ts
- server/utils/referrals/showReferralUtils.ts
- server/views/referrals/withdraw/reason-information/show.njk
We need to link to the select decision step of update status.
- Update `Referral` type to have new `closed` property which we can use to conditionally disable the `Update Status` and `Withdraw referral` buttons.
- Add `Update Status` button.
- Add header to withdraw reason information page which was missed.
> (1364c) Add Update status button

- server/@types/govukFrontend/index.d.ts
- server/@types/prisonApi/imported/index.d.ts
- server/@types/prisonerSearch/imported/index.d.ts
Imported types haven't been updated for a while.
> Update imported types

- helm_deploy/values-dev.yaml
> make WAF rule active

- Dockerfile
> addressing ITHC concern

- integration_tests/e2e/refer/new/submit.cy.ts
- integration_tests/mockApis/manageUsers.ts
- integration_tests/pages/refer/new/checkAnswers.ts
- server/@types/manageUsersApi/index.d.ts
- server/controllers/refer/new/referralsController.test.ts
- server/controllers/refer/new/referralsController.ts
- server/data/hmppsManageUsersClient.test.ts
- server/data/hmppsManageUsersClient.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/utils/referrals/newReferralUtils.test.ts
- server/utils/referrals/newReferralUtils.ts
- server/views/referrals/new/checkAnswers.njk
Following review, there are several changes needed to the current Check Your Answers screen.
- Ordering of summary items
- Added referrer email address
- Heading changes
> (1406) Update check your answers page

- server/controllers/assess/caseListController.test.ts
- server/utils/courseUtils.test.ts
- server/utils/courseUtils.ts
- server/utils/referrals/newReferralUtils.test.ts
- server/utils/referrals/showReferralUtils.test.ts
> fixing course name display

- assets/scss/application.scss
- assets/scss/components/_api-error.scss
- integration_tests/e2e/assess/show.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/page.ts
- integration_tests/support/sharedTests.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/views/referrals/show/partials/risksAndNeedsLayout.njk
- server/views/referrals/show/partials/rootLayout.njk
- server/views/referrals/show/partials/withNavigationLayout.njk
- server/views/referrals/show/risksAndNeeds/attitudes.njk
- server/views/referrals/show/risksAndNeeds/emotionalWellbeing.njk
- server/views/referrals/show/risksAndNeeds/health.njk
- server/views/referrals/show/risksAndNeeds/learningNeeds.njk
- server/views/referrals/show/risksAndNeeds/lifestyleAndAssociates.njk
- server/views/referrals/show/risksAndNeeds/offenceAnalysis.njk
- server/views/referrals/show/risksAndNeeds/relationships.njk
- server/views/referrals/show/risksAndNeeds/risksAndAlerts.njk
- server/views/referrals/show/risksAndNeeds/roshAnalysis.njk
- server/views/referrals/show/risksAndNeeds/thinkingAndBehaving.njk
There may be occasions where OASys is down or not responding. In this scenario the service needs to display something meaningful in the UI to ensure the user understands what is happening and what to do (e.g. try again later).
Show new banner at the top of the Risks and Needs page, as well as inset text further down in the content area, if there is a problem loading the data.
> (1434) Show error message on Risks and needs pages if oasys is down

- helm_deploy/values-prod.yaml
Final step in preparation for go live 😎
[1511](https://trello.com/c/KXJCNArx/1511-enable-the-refer-button-for-go-live)
> enable referrals in prod

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/e2e/refer/new/confirmOasys.cy.ts
- integration_tests/e2e/refer/new/create.cy.ts
- integration_tests/e2e/refer/new/submit.cy.ts
- integration_tests/e2e/refer/withdraw.cy.ts
- integration_tests/pages/shared/caseList.ts
- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/controllers/refer/new/oasysConfirmationController.test.ts
- server/controllers/refer/new/oasysConfirmationController.ts
- server/controllers/refer/new/peopleController.test.ts
- server/controllers/refer/new/peopleController.ts
- server/controllers/refer/new/referralsController.test.ts
- server/controllers/refer/new/referralsController.ts
- server/controllers/shared/categoryController.test.ts
- server/controllers/shared/categoryController.ts
- server/controllers/shared/reasonController.test.ts
- server/controllers/shared/reasonController.ts
- server/controllers/shared/updateStatusSelectionController.test.ts
- server/controllers/shared/updateStatusSelectionController.ts
- server/views/referrals/caseList/assess/show.njk
Updated error handling and error messages
> 1430 - Error Handling

- server/controllers/refer/new/peopleController.test.ts
- server/controllers/refer/new/peopleController.ts
If a valid prison number is entered with lowercase characters, we currently return not found.
Transform the entered string to uppercase to allow for lowercase entry.
> Uppercase the string when searching for a prisoner

- helm_deploy/values-dev.yaml
> Making the WAF less paranoid

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> Makeing the WAF less paranoid

- integration_tests/e2e/refer/new/additionalInformation.cy.ts
- integration_tests/e2e/refer/new/confirmOasys.cy.ts
- integration_tests/pages/refer/new/additionalInformation.ts
- integration_tests/pages/refer/new/confirmOasys.ts
- server/views/referrals/new/additionalInformation/show.njk
- server/views/referrals/new/oasysConfirmation/show.njk
Change "Save and continue" button text to "Continue"
> (APG-41) Continue button text

- server/views/referrals/new/additionalInformation/show.njk
This was accidently missed from the last commit.
> (APG-41) Add `data-testid` to Additional information Continue button

- integration_tests/e2e/assess/caseList.cy.ts
- integration_tests/e2e/refer/caseList.cy.ts
- integration_tests/pages/shared/caseList.ts
- server/@types/ui/index.d.ts
- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/controllers/refer/caseListController.test.ts
- server/controllers/refer/caseListController.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
Change **Name / Prison number** column heading to **Name and prison number**
> (APG-73) Update column heading for Name and prison number

- integration_tests/pages/page.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/risksAndAlerts.ts
- integration_tests/support/sharedTests.ts
- server/controllers/shared/referralsController.test.ts
- server/controllers/shared/referralsController.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/views/referrals/show/risksAndNeeds/risksAndAlerts.njk
[](https://dsdmoj.atlassian.net/browse/APG-55)
> Apg 55 rename nomis to nomis

- integration_tests/pages/shared/showReferral/risksAndNeeds/emotionalWellbeing.ts
- server/@types/models/Psychiatric.ts
- server/testutils/factories/psychiatric.ts
- server/utils/risksAndNeeds/emotionalWellbeingUtils.test.ts
- server/utils/risksAndNeeds/emotionalWellbeingUtils.ts
- server/views/referrals/show/risksAndNeeds/emotionalWellbeing.njk
Following consultation with Next Gen stakeholders, there are some additional OASys fields that need to be added to the Risks and Needs section of a referral.
Updated Section 10 - Emotional wellbeing summary card to contain
- 10.2 – Current psychological problems or depression
- 10.5 – Self-harm, attempted suicide, suicidal thoughts or feelings
As well as the existing 10.6 - Current psychiatric problems
> (APG-139a) Update Section 10 Emotional wellbeing content

- integration_tests/e2e/assess/show.cy.ts
- integration_tests/e2e/refer/show.cy.ts
- integration_tests/pages/shared/index.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/alcoholMisuse.ts
- integration_tests/support/sharedTests.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/utils/index.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/alcoholMisuseUtils.test.ts
- server/utils/risksAndNeeds/alcoholMisuseUtils.ts
- server/views/referrals/show/risksAndNeeds/alcoholMisuse.njk
Following consultation with Next Gen stakeholders, there are some additional OASys fields that need to be added to the Risks and Needs section of a referral.
Add Section 9 - Alcohol misuse page to Risks and needs section when viewing a referral.
> (APG-139c) Add Section 9 - Alcohol misuse details page in Risks and needs

- server/controllers/refer/new/peopleController.test.ts
- server/controllers/refer/new/peopleController.ts
When the user has BOTH PT and Referrer role - allow them to search for any prisoner across any caseload.
Check for both ACP roles and `CASE_TRANSFER_ENABLED` flag and allow search across all caseloads if both true.
> Allow users with both roles to search across all caseloads if `CASE_TRANSFER_ENABLED=true`

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> (APG-124) Set `CASE_TRANSFER_ENABLED` to true in pre and prod

- server/views/referrals/new/start.njk
Start now button needs to be styled [design system](https://design-system.service.gov.uk/components/button/#start-buttons)
Apply `isStartButton=true` 
Added extra bottom margin to content above
> (APG-63) Update appearance of Start now button

- .circleci/config.yml
> Update playwright docker image to 1.44.1 for circleci

- integration_tests/e2e/refer/withdraw.cy.ts
- server/controllers/shared/updateStatusSelectionController.test.ts
- server/controllers/shared/updateStatusSelectionController.ts
- server/views/referrals/updateStatus/selection/show.njk
Change label from Enter a reason to Enter additional information, on the final selection page when updating a status.
> (APG-164) Change reason label to Additional information

- assets/scss/local.scss
- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/controllers/refer/caseListController.test.ts
- server/controllers/refer/caseListController.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/services/referralService.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
- server/views/referrals/caseList/refer/show.njk
PTs and referrers at the pilot sites already have several pages of cases in their caselist view. They sometimes need to find a specific person within this. For PTs, the filters alone don’t cut the list down enough. For referrers, they don’t even have filters to help with this
Add search box to refer case list page
> (APG-171) Refer case list search

- assets/scss/local.scss
- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/controllers/refer/caseListController.test.ts
- server/controllers/refer/caseListController.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/paths/refer.ts
- server/routes/refer.ts
- server/services/referralService.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
- server/views/referrals/caseList/refer/show.njk
Reverts ministryofjustice/hmpps-accredited-programmes-ui#679
> Revert "(APG-171) Refer case list search"

- server/@types/models/CourseAudience.ts
- server/controllers/find/addCourseController.test.ts
- server/controllers/find/addCourseController.ts
- server/controllers/find/index.ts
- server/middleware/roleBasedAccessMiddleware.ts
- server/paths/find.ts
- server/routes/editor.ts
- server/routes/index.ts
- server/views/courses/form/show.njk
We need an easier way to update the content in find to ensure it is accurate. Follows #690 
Add new basic form page for adding a course.  More to come so further information and offerings can be added.
Routes protected by `ROLE_ACP_EDITOR` role.
> (APG-250) Add Course form page

- server/data/accreditedProgrammesApi/courseClient.test.ts
> Specify an existing `organisationId` for `addCourseOffering` PACT test

- integration_tests/e2e/app.cy.ts
- server/views/dashboard/_notificationBanner.njk
> APG-290 - enable pilot site : Fosse Way

- server/data/accreditedProgrammesApi/courseClient.test.ts
> (APG-251) Update `CourseClient.updateCoursePrerequisites` test

- integration_tests/e2e/app.cy.ts
- server/views/dashboard/_notificationBanner.njk
> APG-291 Add Peterborough to new pilot site banner

- integration_tests/e2e/app.cy.ts
- server/views/dashboard/_notificationBanner.njk
> APG-292 Enable referral for pilot site Drake Hall and Long Lartin

- package-lock.json
> Update axios package to resolve security vulnerability raised by npm audit

- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/thinkingAndBehaving.ts
- server/@types/models/Behaviour.ts
- server/@types/models/index.d.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/services/oasysService.ts
- server/testutils/factories/behaviour.ts
- server/utils/risksAndNeeds/thinkingAndBehavingUtils.test.ts
- server/utils/risksAndNeeds/thinkingAndBehavingUtils.ts
We need to add the extra OASys fields used to calculate the PNI to the front-end.
Added:
- 11.2 - Impulsivity
- 11.3 - Aggressive or controlling behaviour
- 11.11 - Sexual preoccupation
- 11.12 - Offence-related sexual interests
> (APG-317) Update Risks and Needs Section 11 - Thinking and behaving

- integration_tests/mockApis/oasys.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/attitudes.ts
- server/@types/models/Attitude.ts
- server/@types/models/index.d.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/data/accreditedProgrammesApi/oasysClient.ts
- server/services/oasysService.ts
- server/testutils/factories/attitude.ts
- server/utils/risksAndNeeds/attitudesUtils.test.ts
- server/utils/risksAndNeeds/attitudesUtils.ts
We need to add the extra OASys fields used to calculate the PNI to the front-end.
- Wrap call to assessment date endpoint in error handler so page still loads but with friendly error
- Added 12.9 - Hostile orientation
> (APG-318) Update Risks and Needs Section 12 - Attitudes

- integration_tests/pages/shared/showReferral/risksAndNeeds/lifestyleAndAssociates.ts
- integration_tests/pages/shared/showReferral/risksAndNeeds/offenceAnalysis.ts
- server/controllers/shared/risksAndNeedsController.test.ts
- server/controllers/shared/risksAndNeedsController.ts
- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
- server/utils/risksAndNeeds/alcoholMisuseUtils.ts
- server/utils/risksAndNeeds/healthUtils.ts
- server/utils/risksAndNeeds/learningNeedsUtils.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.test.ts
- server/utils/risksAndNeeds/offenceAnalysisUtils.ts
- server/utils/risksAndNeeds/roshAnalysisUtils.test.ts
- server/utils/risksAndNeeds/roshAnalysisUtils.ts
- server/views/referrals/show/risksAndNeeds/lifestyleAndAssociates.njk
- server/views/referrals/show/risksAndNeeds/offenceAnalysis.njk
- server/views/referrals/show/risksAndNeeds/relationships.njk
- wiremock/stubs/oasysHealth.json
- wiremock/stubs/oasysLearningNeeds.json
- wiremock/stubs/oasysLifestyle.json
- wiremock/stubs/oasysOffenceDetail.json
- wiremock/stubs/oasysRelationships.json
- wiremock/stubs/oasysRoshAnalysis.json
We need to format the text coming back from OASys which contains `\n` characters.
Replace some of the OASys values which contain `\n` with a `<br>` tag and render as html.
> (APG-300 Format text from OASys

- server/controllers/find/addCourseController.test.ts
- server/controllers/find/addCourseController.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/controllers/find/index.ts
- server/controllers/find/updateCourseController.test.ts
- server/controllers/find/updateCourseController.ts
- server/data/accreditedProgrammesApi/courseClient.ts
- server/paths/api.ts
- server/paths/find.ts
- server/routes/find.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- server/views/courses/form/partials/prerequisiteFieldset.njk
- server/views/courses/form/show.njk
- server/views/courses/show.njk
We need an easier way to update the content in FIND to ensure it is accurate.
- Add new `UpdateCourseController` 
- Update existing course form template to show pre-fill fields with existing values
- Added Update button link to course page
Button link from course page
Course form with values pre-filled
> (APG-249) Update a course

- server/utils/referrals/showRisksAndNeedsUtils.test.ts
- server/utils/referrals/showRisksAndNeedsUtils.ts
Move Learning needs link to second in the risks and needs page side navigation.
> (APG-389) Move Learning needs link in risks and needs navigation menu

- server/data/accreditedProgrammesApi/referralClient.test.ts
> Update pact after create referral change

- server/data/accreditedProgrammesApi/referralClient.test.ts
> Fix pact test for creating a referral

- server/views/reports/show.njk
Need a clear filters option.
Add clear filters link and move actions to bottom of filter block.
> (APG-385f) Add clear filters and move buttons to bottom of filter block

- server/views/referrals/updateStatus/selection/show.njk
Need to increase textarea height after increasing character limit to 500.
Change to 10 rows instead of default 6.
> (APG-414) Increase update status text area size to 10 rows

- server/data/accreditedProgrammesApi/referralClient.test.ts
> Update pact test for change in response code when submitting a referral

- Dockerfile
> Fix node version value in Dockerfile

- assets/scss/overrides.scss
- integration_tests/pages/page.ts
- integration_tests/pages/refer/new/taskList.ts
- package-lock.json
- server/testutils/factories/referral.ts
- server/testutils/factories/referralStatusHistory.ts
- server/testutils/factories/referralView.ts
- server/testutils/factories/user.ts
- server/utils/courseParticipationUtils.test.ts
- server/utils/courseParticipationUtils.ts
- server/utils/referrals/newReferralUtils.test.ts
- server/utils/referrals/newReferralUtils.ts
- server/views/accessibilityStatement/index.njk
- server/views/referrals/new/_taskListSection.njk
- server/views/referrals/new/delete/show.njk
Some minor improvements can be made, based on accessibility testing.
- Specify `aria-describedby` for Delete draft button
- Overide govuk-tag text colour
- Specify `aria-describedby` for draft referral task list items
- Replace "participation" with "programme" in visually hidden text
- Fix url type in accessibility statement
- Update faker package and use of `faker.internet.username`
> (APG-496) Accessibility updates

- assets/scss/overrides.scss
- server/utils/referrals/showReferralUtils.test.ts
- server/utils/referrals/showReferralUtils.ts
- server/views/referrals/caseList/assess/show.njk
- server/views/referrals/caseList/refer/show.njk
- server/views/referrals/show/partials/rootLayout.njk
- Use `aria-disabled` instead of `disabled` for referral action buttons
- Add table caption on case lists to help sight impaired users
> (APG-500) Accessibility updates

- server/data/index.ts
> Move new TokenStore into own variable

- server/data/accreditedProgrammesApi/courseClient.test.ts
> Update participation outcome and setting values to match pact test in API

- assets/scss/components/_api-error.scss
- assets/scss/components/_dashboard.scss
- assets/scss/components/_pathway-content.scss
- assets/scss/components/_risks-and-alerts.scss
- integration_tests/e2e/pniFind.cy.ts
- integration_tests/mockApis/oasys.ts
- integration_tests/pages/find/index.ts
- integration_tests/pages/find/recommendedPathway.ts
- server/@types/ui/index.d.ts
- server/controllers/find/index.ts
- server/controllers/find/recommendedPathwayController.test.ts
- server/controllers/find/recommendedPathwayController.ts
- server/paths/find.ts
- server/routes/find.ts
- server/views/find/recommendedPathway.njk
- server/views/partials/pathway.njk
- server/views/referrals/show/pni/show.njk
We need to implement the PNI Pathway result at the beginning of the referral journey, so users know which intensity level they should be referring to. This will result in changes to the user journey from FIND into REFER.
This PR adds a new controller for the second step within the new PNI driving a referral journey.
**High intensity:**
**Moderate intensity:**
**Alternative pathway/Not eligible:**
**Some information missing:**
**All information missing:**
> (APG-622) Recommended pathway step

- integration_tests/e2e/pniFind.cy.ts
- server/controllers/find/recommendedPathwayController.test.ts
- server/controllers/find/recommendedPathwayController.ts
- server/data/accreditedProgrammesApi/courseClient.ts
- server/paths/find.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- Fix typo for recommendedProgrammes path
- Update course client and service method to take query param for course intensity
> (APG-623a) Recommended programmes prep

- integration_tests/pages/page.ts
- server/views/referrals/show/partials/risksAndNeedsLayout.njk
Corrects text on the risks and needs tab within a referral
> APG-636 Correct risks and needs intro text

- renovate.json
Doing some housekeeping and attending to the PR backlog, I was looking at the lint failures for #867 to get those updates merged.
Have concluded that the best use of time for now is fixing  `eslint-import-resolver-typescript` to version `3.7.0` for renovate PRs.  
I've have raised https://dsdmoj.atlassian.net/browse/APG-744 to move our eslint config to use the [@ministryofjustice/eslint-config-hmpps](https://github.com/ministryofjustice/hmpps-typescript-lib/tree/main/packages/eslint-config-hmpps) package where we should be able to then remove the need for this fixed version.
> (APG-729a) Fix eslint-import-resolver-typescript to 3.7.0 for renovate

- server/@types/express/index.d.ts
- server/@types/ui/index.d.ts
- server/controllers/assess/index.ts
- server/controllers/assess/transferReferralController.test.ts
- server/controllers/assess/transferReferralController.ts
- server/paths/assess.ts
- server/routes/assess.ts
- server/views/referrals/transfer/show.njk
Add TransferReferralController with show method. This checks if the referral can be transferred _(currently doesn't include checking for duplicates)_.  If it can be transferred then it will show the reason form.
If it cannot be transferred then it will set some error data in the session and redirect to an upcoming Transfer Error page.
`submit` will be a separate PR.
> (APG-694b) Add new `TransferReferralController` with `show` method

- server/controllers/assess/transferReferralController.test.ts
- server/controllers/assess/transferReferralController.ts
We need to show a duplicate referral page when there is already an existing referral for a BC programme to the same location as the current referral for the person.
Use the single CourseOffering ID returned by `/referrals/{id}/transfer-to-building-choices/{courseId}` to call the new `/referrals/duplicates` endpoint to check for any duplicate referrals that match the persons `prisonNumber` and the `offeringId` and throw an Error which can be used by the `TransferErrorController`.
The `originalReferralId` value is/will be used by the existing duplicate referral page for page content and links.
> (APG-695b) Throw `DUPLICATE` Error when checking if a transfer to BC can be made

- server/controllers/assess/caseListController.test.ts
- server/controllers/assess/caseListController.ts
- server/utils/referrals/caseListUtils.test.ts
- server/utils/referrals/caseListUtils.ts
> APG-712: Add the isLdc argument to the caseListController

- integration_tests/e2e/assess/transfer.cy.ts
- integration_tests/mockApis/courses.ts
- integration_tests/mockApis/referrals.ts
- integration_tests/pages/assess/transfer.ts
- integration_tests/pages/assess/transferError.ts
- server/controllers/assess/transferReferralController.test.ts
- server/controllers/assess/transferReferralController.ts
- server/controllers/assess/transferReferralErrorController.test.ts
- server/controllers/assess/transferReferralErrorController.ts
- server/testutils/factories/course.ts
- server/views/referrals/transfer/show.njk
Transferring to Building Choices functionality is mostly there and we needed some integration tests.
Added tests for happy path and error scenarios.
> (APG-694f) Integration tests for Transfer

- package-lock.json
To fix issues shown in this failing job: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-accredited-programmes-ui/6444/workflows/caba8ba4-d9e0-4a9d-8a03-62235e0614b7/jobs/32192
Ran `npm audit --fix`
> Update package.lock to address some npm audit warnings

- server/utils/referrals/showReferralUtils.test.ts
- server/utils/referrals/showReferralUtils.ts
Reverts ministryofjustice/hmpps-accredited-programmes-ui#933
> Revert "(APG-625) Temporarily remove Change LDC status button"

- server/@types/accreditedProgrammesApi/index.d.ts
- server/testutils/factories/referralStatusReason.ts
- server/utils/referrals/referralUtils.test.ts
Types needed to be updated for some upcoming work.
Notable changes include:
- Added `categoryDescription` to `ReferralStatusReason`
-  Update associated test factory
- Change from `overrideReason` to `referrerOverrideReason` on `Referral`
> Update AcP types

- server/@types/govukFrontend/index.d.ts
- server/controllers/shared/referralsController.test.ts
- server/controllers/shared/referralsController.ts
- server/data/accreditedProgrammesApi/referralClient.ts
- server/paths/api.ts
- server/paths/assess.ts
- server/paths/refer.ts
- server/routes/assess.ts
- server/routes/refer.ts
- server/services/index.ts
- server/services/referralService.test.ts
- server/services/referralService.ts
- server/utils/referrals/showReferralUtils.test.ts
- server/utils/referrals/showReferralUtils.ts
- server/views/referrals/show/otherReferrals.njk
> [APG-717] Fetch other open referrals 

- package-lock.json
> NPM Audit fixes

- .env.dev.example
- helm_deploy/values-dev.yaml
- server/config.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/views/courses/show.njk
HSP referral functionality should be behind a flag for now.
- Add flag for enabling HSP referrals
- Add Start referral button to course page if:
- Course is HSP
- HSP is enabled
- In a PNI find and refer journey
> (APG-843) HSP Flag and Start referral button

- integration_tests/e2e/find.cy.ts
- integration_tests/e2e/pniFind.cy.ts
- integration_tests/mockApis/courses.ts
- server/@types/ui/index.d.ts
- server/controllers/find/buildingChoicesController.test.ts
- server/controllers/find/buildingChoicesController.ts
- server/controllers/find/coursesController.test.ts
- server/controllers/find/coursesController.ts
- server/data/accreditedProgrammesApi/courseClient.test.ts
- server/data/accreditedProgrammesApi/courseClient.ts
- server/services/courseService.test.ts
- server/services/courseService.ts
- server/utils/organisationUtils.test.ts
- server/views/courses/_locationsTable.njk
- server/views/courses/buildingChoices/show.njk
- server/views/courses/show.njk
Show withdrawn locations if the ACP_EDITOR role is present for the user.
> Apg 860 allow withdrawn locations

- helm_deploy/values-preprod.yaml
> [APG-898] Add config to enable HSP in preprod

- server/controllers/find/hspDetailsController.test.ts
- server/controllers/find/hspDetailsController.ts
> [APG-962] Do not throw error when none of the HSP reasons are selected
