helm_deploy/values-dev.yaml

Removes `hmpps` from ingress host
This should now match up with the URL we've configured in the Cloud Platform Environments repo [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/2a98d2873bcb1f27b0157d8b3b54bdeefda33c31/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-accredited-programmes-dev/06-certificates.yaml#L13)

Fix ingress host (2)

---

.env.example

This is used in the setup script to copy into `.env`, but it was missing
Add missing file used in setup script

Add `.env.example`

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

We were getting some high severity warnings relating to [CVE-2022-29458][1]
Over on the CAS3/Temporary Accommodation UI project, they were already setting the engine to 18 in package.json, but @tahb set CircleCI and Docker to use 18, which resolved the warnings. We were already on 18, but upgrading from 18.15 to 18.16 fixes the issues locally, as confirmed by running the commands below
Before the changes (three high severity warnings will show):
```
$ docker build . -t test-16
$ docker run --rm -v trivy-cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 100 --no-progress --severity HIGH,CRITICAL --ignore-unfixed --skip-dirs /usr/local/lib/node_modules/npm --skip-files /app/agent.jar test-16
```
After the changes (no warnings will show): …

Upgrade to Node 18.16

---

helm_deploy/values-dev.yaml

This adds the missing dev url for the Accredited Programmes API, which should have been added as part of #18. This is currently preventing the dev environment from starting up, causing the build to fail.

Add Accredited Programmes dev API url

---

.eslintrc.json
integration_tests/mockApis/auth.ts
integration_tests/mockApis/wiremock.ts
server/data/index.ts
server/data/restClientMetricsMiddleware.test.ts
server/errorHandler.ts
server/middleware/asyncMiddleware.ts
server/middleware/setUpWebSecurity.ts
server/utils/azureAppInsights.ts

On the Approved Premises UI repo, a linting rule dictates that when importing multiple things from one module, the imports are alphabetised. This like a useful thing to do here too
This adds a linter check for ordering imports alphabetically (within a single line, not between lines) and fixes resulting errors

Sort imports

---

.circleci/config.yml
.djlintrc
.gitignore
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json
server/views/autherror.njk
server/views/dashboard/index.njk
server/views/pages/error.njk
server/views/partials/breadCrumb.njk
server/views/partials/layout.njk
server/views/programmes/index.njk

#25 (unmerged) added djLint for both linting and formatting of Nunjucks files. The formatting side had some very questionable choices. After consulting with the Approved Premises team, I've tested another approach, which would replace #25
This uses Nunjucks Template Formatter (NTF) for formatting, which is just a VSCode extension. Not ideal if we have team members who don't use VSCode, but it does formats templates much more sensibly. For formatting and for our current team setup, this is probably fine
djLint is still used for linting, including in `npm run lint`, used in `script/test` (but skipped in the CI). One rule is turned off due to conflicting with a formatting choice of NTF that isn't immediately obviously configurable

Add linting and formatting

---

.djlintrc

When deciding to use Nunjucks Template Formatter for formatting and djLint only for linting, the `files` key was added to `.djlintrc` to be more specific about where to lint. When evaluating djLint as a formatter (as well as a linter), this key was omitted as it would produce unwanted behaviour in VSCode when using on-save autoformatting
However, it appears that with this key, VSCode also fails to highlight linting errors in the editor. Removing the key fixes the behaviour, allowing you to see errors without needing to run `npm run lint` or `script test`
This therefore removes the key to enable Nunjucks linting error highlighting

Enable djLint error highlighting in VSCode

---

server/testutils/factories/programme.ts
server/testutils/factories/programmePrerequisite.ts

We recently upgraded to Faker v8, which deprecated `.random`, which will be removed in v9.
This replaces those methods with non-deprecated alternatives. It also updates the programme prerequisite factory so that the key is one or more words, rather than one character, making it more realistic

Replace deprecated Faker methods

---

README.md
cypress.config.ts
doc/adr/0001-mock-api-endpoints-in-dev.md
docker-compose.yml
integration_tests/mockApis/auth.ts
integration_tests/mockApis/programmes.ts
integration_tests/mockApis/tokenVerification.ts
package-lock.json
package.json
script/bootstrap
script/server
script/utils/start-backing-services
wiremock/index.ts
wiremock/resetStubs.ts
wiremock/stubApis.ts
wiremock/stubs/programmes.json

[Trello card](https://trello.com/c/OoaO2VpR/400-use-wiremock-as-a-fake-api-in-local-development)
This adds the ability to mock the Accredited Programmes API locally so that UI work can progress independent of API development progress.
The application can now be started up with `script/server --mock-api` to return this canned response.
We'll need to make sure we update these as the data in the API changes, but we're hoping to be notified to do so with Pact when we add that in future.

(400) Set up mocks

---

script/test
script/update

This adds an `update` script, which currently just wraps around `bootstrap`. It's added at the start of the `test` script to ensure dependencies are resolved before testing (when running `script/test`, not `npm run test`/`npm run test:integration` etc)

Update dependencies before testing

---

README.md
doc/adr/0001-mock-api-endpoints-in-dev.md
package.json
script/bootstrap
wiremock/scripts/resetStubs.ts
wiremock/scripts/stubApis.ts

We lost some changes in #38 after [this force push](https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/compare/973aa00b8a8d6523d711603aac620939eab8c1c7..048105ba8545edb24c5bd051a19fa68606d62723)
- move Wiremock scripts into descriptive subdirectory
- add additional ADR consequence
- remove unnecessary call to start backing services

(400b) Recommit lost changes

---

README.md
script/test
script/update

We currently have to remember to run `docker compose pull` to bring in API changes
This updates all backing service images when running `script/update`. This is automatically run in `script/test`, but an option to run `script/test` without the update (to images or any other dependencies) is provided

Update backing service images in `script/update`

---

docker-compose.yml
helm_deploy/values-dev.yaml
integration_tests/tsconfig.json
server/@types/prisonApi/Prison.ts
server/@types/prisonApi/PrisonAddress.ts
server/@types/prisonApi/index.d.ts
server/config.ts
server/data/prisonClient.test.ts
server/data/prisonClient.ts
server/paths/prisonApi.ts
server/testutils/factories/prison.ts
server/testutils/factories/prisonAddress.ts
tsconfig.json

https://trello.com/c/d4yEqtSO/403-fetch-prison-information
This adds a Prison client for fetching Prison data from the Prisons API. We'll use it to populate the "Offerings" page in the near future. It also starts up the Prisons API locally as a backing service.
There's still an ongoing conversation as to whether this is the correct API to use, but it does seem to have what we need, for now at least. We'll wrangle the Prison object we get back into our own internal `Organisation` model in future work.

(403) Add Prison client

---

Dockerfile

For some reason the build has started failing with:
```
npm ERR! gyp ERR! find Python - version is 2.7.18 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
```
Specifies that we should install Python version 3 in our Docker build - this a dependency of `node-gyp`

Specify Python version 3 in Docker build

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
doc/adr/0003-use-playwright-for-end-to-end-tests.md

[Trello card](https://trello.com/c/zGaYc1r5/415-add-e2e-tests)
We now run end-to-end tests on the deployed dev environment after that stage in the CI process to ensure
the "real" service as a whole is working as expected, as opposed to our Cypress integration tests which are running against a mock backend.
The script clones the e2e test repo locally, installs dependencies and runs the Playwright test script.
Log in secrets are stored in the Circle CI env vars.

(415) Run Playwright end-to-end tests on CI

---

.circleci/config.yml
README.md
docker-compose-test.yml
docker-compose.yml
helm_deploy/hmpps-accredited-programmes-ui/values.yaml
helm_deploy/values-dev.yaml
integration.env
script/server
server/config.ts
wiremock/index.ts

The use of 9091 both as the prisons API in non-test environments and Wiremock in test environments causes a conflict if you run integration tests while the local server is running
This fixes the port clash and implements more of a system for port choice
Note that the integration tests will fail without fixing the endpoint in `wiremock/scripts/stubApis`, which is addressed in a separate PR: https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/49/commits/2b4a723cb1c5bce0299543471f2d8fa436151c6a

(445) Fix port clash

---

.github/PULL_REQUEST_TEMPLATE.md

Changes the E2E test-writing reminder to be post-merge. 
These tests will run against the deployed environment, so would always be failing if we ran them before merging...

Make E2E reminder post-merge

---

server/data/courseClient.test.ts

We were previously using a randomly generated ID provided by the factory, meaning the provider would have to generate exactly the same ID to fulfil these contracts and make the tests pass.
Here we hardcode the course ID so we can use the same one in the Provider's contract verification tests.

Use a specific course ID in Pact contract tests

---

server/testutils/factories/course.ts
server/testutils/factories/courseAudience.ts

We're explicitly using params here in a way that's built in with Fishery, so it's redundant: we get this behaviour for free
Default to implicit param overrides in factories

Remove explicit factory params

---

integration_tests/tsconfig.json
tsconfig.json

This appears to be unnecessary, and is causing some of VSCode's import suggestions to be in the form `server/**` rather than `./*` or `../*`
Remove `baseUrl` from `tsconfig` to keep import style consistent

Remove base path from tsconfig

---

integration_tests/e2e/find.cy.ts
integration_tests/mockApis/courses.ts
integration_tests/mockApis/prisons.ts
integration_tests/pages/find/course.ts
integration_tests/pages/find/courses.ts
server/controllers/dashboardController.test.ts
server/controllers/dashboardController.ts
server/controllers/find/index.ts
server/controllers/index.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/data/prisonClient.ts
server/routes/find.ts
server/routes/index.ts
server/utils/organisationUtils.ts
server/utils/routeUtils.ts
wiremock/scripts/stubApis.ts

We were still hardcoding paths in our router. Per Approved Premises, we can get the path patterns with the `.pattern` method. Some of the groundwork for this in Approved Premises was done in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/138, which adds namespacing in controllers, paths and routers. We already have this in our paths, but not in our controllers or routers
Also related to paths, we import a `paths` object from three different sources across the app, which can be a little confusing when reading code snippets
- clarify which paths are being used where
- namespace controllers and routers
- use path patterns in routes

(497) Use paths in routes

---

integration_tests/tsconfig.json

After running various updates today (macOS and brew formulae and casks), I started seeing a few errors in the `integration_tests` folder:
- in `integration_tests/tsconfig.json`, TS2688: `Cannot find type definition file for 'cypress'` and `Cannot find type definition file for 'express-session'`
- in `integration_tests/**/*.ts`, TS2304: `Cannot find name 'cy'` and `Cannot find name` with various other Cypress-related objects
The `typeRoots` change fixes the former, while the `include` change fixes the latter. This was hard to debug, but the following helped:
- https://stackoverflow.com/a/53938729/4002016 (I think - as well as the Approved Premises config)
- https://github.com/cypress-io/cypress/issues/1152#issuecomment-355794417

Fix Cypress/TypeScript/VSCode integration

---

integration_tests/pages/find/course.ts
integration_tests/pages/find/courseOffering.ts
integration_tests/pages/page.ts
server/@types/ui/index.d.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/views/courses/offerings/show.njk

The designs for the course offering page have been updated
In course offering page:
- Add link to email address
- Remove "Make referral" button
Elsewhere: various bits of groundwork and minor consistency edits

(511) Update course offering page

---

assets/scss/components/_dashboard.scss
assets/scss/components/_header-bar.scss
assets/scss/local.scss

Switch to `rem` in `assets/scss/components/*` and `assets/scss/local`, but not `assets/scss/application` since that interacts with a Node module and its behaviour may rely on a specific unit
Media queries still use `em` since `rem` aren't proper media query units and `em` is more consistent across browsers and usage scenarios than `px`:
- https://github.com/at-import/breakpoint/issues/132#issuecomment-86539326
- https://zellwk.com/blog/media-query-units
- https://stackoverflow.com/a/74798205/4002016
- https://stackoverflow.com/a/60830895/4002016

Switch to `rem`

---

docker-compose.yml
script/utils/start-backing-services

https://trello.com/c/VDp60gWQ/492-fix-ui-version-of-the-api-now-that-a-database-has-a-been-added
`script/server` started failing once we added the database to the API, as we weren't starting a postgres database.
This starts all the necessary backing services for running the API and our dependencies locally now that the API has a `seed` environment to start up with data.

(492) Get docker-compose working locally with new DB

---

integration_tests/pages/find/course.ts
integration_tests/pages/find/courses.ts
server/@types/models/Course.ts
server/@types/ui/index.d.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/testutils/factories/course.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/courses/_indexCourseSummary.njk
wiremock/stubs/courses.json

We want to display an initialised form of course names alongside the course name
This adds `alternateName` to courses and inserts it in the UI
Note: this does show the initialised forms on the second and third courses, because they were in the `name` in our stubs (removed in this PR), whereas in the screenshot below, they are pulled from `alternateName`

(516) Display acronyms

---

server/data/courseClient.test.ts

https://trello.com/c/U0gghZBi/563-fix-api-pact-issue
`Matchers.like` checks string values, but not `null` values, so tests were failing on the API when providing a `null` value which was never expected due to our factory methods always returning a string.
Adds more specific course variables for use in Pact tests, including one with a `null` `alternateName` to fulfil the contracts.

Add nullable alternate names in Pact tests

---

server/testutils/factories/courseAudience.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
wiremock/stubs/courses.json

Since we added audiences and corresponding tag colours, the data have changed
Update course audience options and related tag colours, based on the latest data and design input

Update course audience options

---

.circleci/config.yml

This is currently failing due to a change in the data in dev, which is now showing real or real-ish data, and has no email addresses
Disable E2E CI step. We'll re-enable this soon, but for now we don't want the failing step

Disable E2E CI step

---

server/middleware/setUpSentry.ts

We're using an anonymous ID but for some reason Sentry is still being usernames.
This deletes the username field from the event sent to Sentry in the hope that we'll stop sending usernames.

Remove username from event sent to Sentry

---

.circleci/config.yml

We're currently notifying the dev channel for releases, but a more dedicated events channel for error and deployment notifications feels more appropriate and will keep the dev channel a more focused place for discussion etc.
Changes the channel for notifications to `#accredited-programmes-events`

Use accredited-programmes-events slack channel for releases

---

package-lock.json
package.json

We're currently getting the following warning from `npm audit` about security vulnerabilities in Semver (a dependency of a lot of our dependencies):
`semver vulnerable to Regular Expression Denial of Service` - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
This overrides dependencies to use Semver 7.5.3 rather than earlier vulnerable versions.
Everything appears to be working correctly with tests passing.
It looks like it's had to downgrade a couple of dependencies to be compatible with this version.

Override semver version in package.json

---

server/testutils/factories/courseAudience.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
wiremock/stubs/courses.json

The audiences have changed again
- Update the audiences and corresponding tag colours
(the audiences that are out of date on the API Docker seed data will default to blue tags locally; but this will fix things on dev)

(582) Update audiences per current data

---

integration_tests/pages/authManageDetails.ts
integration_tests/pages/authSignIn.ts
integration_tests/pages/find/course.ts
integration_tests/pages/find/courseOffering.ts
integration_tests/pages/find/courses.ts
integration_tests/pages/index.ts
integration_tests/pages/page.ts
server/views/courses/index.njk
server/views/courses/offerings/show.njk
server/views/courses/show.njk
server/views/dashboard/index.njk
server/views/pages/error.njk
server/views/partials/layout.njk

We set page heading and page titles separately, but generally the heading can be reused in the title. There were some other unDRY patterns within the views
- Default to `applicationName` and `pageHeading` if `pageTitle` is not set
- Remove some custom `pageTitle`s
- Use `nameAndAlternateName` in one place it wasn't being used
- DRY up setting of `mainClasses`
- DRY up `h1` creation

(453) Use page headings as titles and other such niceties

---

server/testutils/factories/course.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
wiremock/stubs/courses.json

In some cases, a single course has multiple prerequisites with the same name. The current code will only display the last of these in such cases
- Concatenate prerequisites with the same name
- Ensure we are working on the assumption (default) that there can be multiple prerequisites with the same name on a single cause

(593) Combine multiple prerequisites

---

integration_tests/e2e/find.cy.ts
integration_tests/pages/find/courseOffering.ts
integration_tests/pages/page.ts
server/@types/models/CourseOffering.ts
server/@types/ui/index.d.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/data/courseClient.test.ts
server/testutils/factories/courseOffering.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
wiremock/stubs/courseOfferings.json

https://trello.com/c/fNkfLBoN/598-read-secondary-contact-email-address-in-the-ui
We've now added an optional secondary contact email address for Offerings to the API for Courses that might have two email addresses for a referral. We need to display this to users.
Displays a secondary offering email on the "Offering" page if one exists.
If no secondary offering email exists, we don't render the summary list item at all.
There's a fair bit going on in the main commit of this PR as I've renamed some functions and changed return values of types to support a possibly-undefined summary list item, but I wanted to make sure all tests were passing.
The integration tests here aren't exactly DRY, but we can refactor them once we have a bit more time if we think it's necessary.
[Release process …

(598) Display secondary contact email address if one exists

---

integration_tests/pages/find/course.ts
server/@types/prisonRegisterApi/index.d.ts
server/@types/ui/index.d.ts
server/services/organisationService.test.ts
server/testutils/factories/prison.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/views/courses/_locationsTable.njk

https://trello.com/c/M8TfhcMB/520-display-prison-category-in-the-list-of-offerings
Prison Category is an important field for POMs to ensure they don't refer people in prison to a programme in a prison of a different category. Until now, it's been unavailable in the Prison Register API, but we've now done the work to add it into the service.
This reverts (and slightly tweaks) the commits made in #105 where we removed the unavailable prison categories.
We now join categories returned from the Prison API with a '/' and display them in the list of offerings.

(520) Display prison category (again)

---

server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts

https://trello.com/c/P1bccynd/610-display-empty-cell-in-table-rather-than-not-available-where-no-prison-category-is-found
Some prisons don't have categories (i.e. women's prison, YOI), so showing "Not available" feels misleading.
We now show an empty row instead of "not found" where there's no prison category available.

(610) Display empty row for no Prison Category

---

.github/workflows/git.yml

It's currently possible to merge PRs with fixup and squash commits still in the commit history. These should be rebased to squash into or fix up the relevant commits before merging to `main`
Add workflow which will fail if fixup or squash commits are present
This doesn't block merge commits. I did try [this action](https://github.com/marketplace/actions/block-merge-and-autosquash-commits) which includes that, but it had a missing dependency/module not found error. [This action](https://github.com/marketplace/actions/block-merge-commits) might do the job, but it appears to require access to secrets, which I'd be more cautious about
ready to be …

(525) Block fixup and squash commits

---

.circleci/config.yml

We should prevent deployment to preprod if the E2E tests are failing - I missed this in the previous PR (#126)
Require passing E2E tests before approving preprod deployment

(569c) Require E2E test for preprod deploy

---

server/views/autherror.njk
server/views/courses/_audienceTags.njk
server/views/courses/_indexCourseSummary.njk
server/views/courses/show.njk

Some paragraph classes were missed when writing earlier PRs
Add `govuk-body` class to paragraphs where missing
No noticeable change

(641) Add missing `.govuk-body` classes

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/mockApis/referrals.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/data/referralClient.test.ts
server/data/referralClient.ts
server/paths/api.ts
server/paths/refer.ts
server/services/referralService.test.ts
server/services/referralService.ts

We currently have the course offering in all Refer paths, but we can get this from the referral once created
- Simplify post-creation Refer paths to remove redundant course offering ID
- Clean up paths
- Update test descriptions

(730) Simplify post creation actions

---

server/views/partials/layout.njk

We discussed this in a dev/design catchup - it makes more sense for the personal details to be closer to the page-specific content
- Move the personal details banner lower down

(727b) Move personal details

---

.circleci/config.yml

Our CI builds are currently broken due to npm 10 being incompatible with the current version of Node
- Pin our CI to npm 9.8.1 to fix builds

Pin npm to 9.8.1 in Circle CI

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/data/referralClient.test.ts
server/data/referralClient.ts
server/data/restClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/routeUtils.ts

The API now has support for updating a referral via a PUT request
- Add PUT request support
- Add API path
- Add client and service methods for updating a referral using the endpoint

(731) Add PUT/update support

---

integration_tests/e2e/find.cy.ts
integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/find.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/mockApis/courses.ts

We simplified the offering endpoint in https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/169 but missed `stubCourseOffering` in the integration tests
- Remove `courseId` from `stubCourseOffering

(718c) Remove `courseId` from `stubCourseOffering`

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/data/referralClient.test.ts
server/data/referralClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts

In anticipation of the referral complete step.
- Add API path for updating status
- Add client and service methods for updating a referral status using the endpoint

(650a) Add support for updating the status of a referral

---

integration_tests/e2e/refer.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/checkAnswers.ts
integration_tests/pages/refer/complete.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/views/referrals/checkAnswers.njk

Updates the form functionality on the check answers page to update the referral status to `referral_submitted` when the confirm checkbox is selected and then redirect to the referral complete page when successful. 
Also shows an error if the checkbox is not selected.
- Use `req.flash` for error messages on check answers page
- Use `govukErrorSummary` component to display errors on check answers page
- Add `submit` method to referrals controller to handle `POST` request.
- Update check answers page to use new `/submit` endpoint
With form error message

(650c) Submit referral

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/pages/refer/checkAnswers.ts
integration_tests/pages/refer/taskList.ts
server/@types/ui/index.d.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/testutils/factories/referral.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/_taskListSection.njk

The check answers task list section is currently hardcoded to show the URL and a 'cannot start yet' tag
- Make the check answers task list section dynamic, only showing the URL when ready, and updating the tag to reflect the actual status
- Redirect from check answers/submit when the referral is not ready for submission
- Tidy ups
Currently it only checks for `oasysConfirmed` since the `Referral` model is incomplete

(797) Make check answers task dynamic

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/reason.ts
integration_tests/pages/refer/taskList.ts
server/@types/models/Referral.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/testutils/factories/referral.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/reason.njk

https://trello.com/c/LSccMbIN/653-add-reason-for-the-referral-form-step-ui
- Added page template for referral reason form step
- Added `/reason-for-referral` path
- Added `reason` method to `ReferralsController`
- Update `update` method to handle `reason`
- Add url to link to new page from task list

(653) Reason for referral

---

server/utils/referralUtils.test.ts
server/utils/referralUtils.ts

https://trello.com/c/wKf9Lq9a/844-prevent-access-to-cya-page-until-reason-for-referral-has-been-filled-in
- Move _Add reason for referral and any additional information_ task to top, beneath Referral Information
- Update `isReadyForSubmission` to check for `referral.reason` to Check Your Answers page cannot be accessed

(844) Prevent access to check your answers page without referral reason

---

integration_tests/e2e/refer.cy.ts
integration_tests/pages/page.ts
server/controllers/refer/peopleController.test.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/views/referrals/checkAnswers.njk

Utilise `setFieldErrors` from `FormUtils` to set the validation for the check your answers page.
- Use `FormUtils.setFieldErrors` for the `confirmation` checkbox on check your answers page
- Updated the referrals controller test to reset the response value between each test to avoid unexpected test behaviour.

(650d) Update check your answers page validation

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/coursesController.test.ts
server/controllers/refer/referralsController.test.ts
server/data/referralClient.test.ts
server/services/referralService.test.ts
server/testutils/factories/referral.ts
server/utils/referralUtils.test.ts

- Add traits to referral factory
- Randomise default factory values

(841) Referral factory updates

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
server/controllers/refer/index.ts
server/controllers/refer/reasonController.test.ts
server/controllers/refer/reasonController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/referralUtils.ts
server/views/referrals/reason.njk

https://trello.com/c/OkMpaWcU/842-make-reason-for-referral-required-ui
We have decided to create a new controller for each step of a referral to prevent the possibility of the `ReferralsController` becoming too unwieldy.
This extracts the logic for showing, setting and updating the `reason` field on a Referral out of the ReferralsController and into an `ReasonController`.
- Add new `ReasonController`
- Move reason related method and functionality from ReferralsController to new `ReasonController`
- Add new `update` reason method 
- Display error messaging on reason page when no reason submitted

(842) Reason validation

---

integration_tests/e2e/refer.cy.ts
server/controllers/refer/oasysConfirmationController.test.ts
server/controllers/refer/oasysConfirmationController.ts
server/views/referrals/oasysConfirmation/show.njk

On the Confirm the OASys information step, we need to prevent the form from being submitted and display an error summary and an error message.
https://trello.com/c/k1Wzzrpe/795-prevent-users-being-able-to-submit-the-oasys-confirmation-page-without-checking-the-confirmation-checkbox-ui
Updated both `show` and `update` methods in the `OasysConfirmationController` to handle validation messaging when a user tries to continue without checking the confirmation checkbox.

(795) Confirm OASys validation

---

.circleci/config.yml
jest.config.ts
server/app.ts
server/applicationVersion.ts
server/controllers/find/index.ts
server/controllers/index.ts
server/controllers/refer/index.ts
server/data/index.ts
server/data/redisClient.ts
server/data/restClient.ts
server/data/restClientMetricsMiddleware.ts
server/data/tokenStore.ts
server/data/tokenVerification.ts
server/monitoring/metricsApp.ts
server/services/healthCheck.ts
server/services/index.ts
server/utils/appInsightsUtils.ts
server/utils/routeUtils.ts
wiremock/scripts/resetStubs.ts

We aren't collecting unit test coverage at the moment, despite the `collectCoverageFrom` Jest setting
- Collect unit test coverage
- Ignore certain files
- Require 100% function coverage in all other files

Collect coverage

---

.eslintignore
tsconfig.json

Added `test_results` directory to eslintignore and tsconfig files as it was causing problems.

Add `test_results` dir to eslintignore and tsconfig

---

integration_tests/mockApis/courses.ts
server/@types/models/CourseParticipation.ts
server/@types/models/index.d.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/middleware/index.ts
server/paths/api.ts
server/testutils/factories/courseParticipation.ts
server/testutils/factories/courseParticipationOutcome.ts
server/testutils/factories/courseParticipationSetting.ts
server/testutils/factories/factoryHelpers.ts
server/testutils/factories/index.ts
server/utils/formUtils.ts
server/utils/organisationUtils.ts
server/utils/userUtils.ts
wiremock/scripts/stubApis.ts
wiremock/stubs/courseParticipations.json
wiremock/stubs/index.ts

Groundwork for adding the course history index page. The API isn't quite up to date with these changes, but that's being worked on right now, and there aren't any tests this should break
- Add participations types and factories
- Add participations API endpoint paths and stubs
- Two tidy ups

(703a) Add course participations

---

server/data/courseClient.test.ts
server/data/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts

#214 added the course participation types, factories and paths
- Add client and service methods to get participations by person

(703b) Add course participation client and service methods

---

server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/index.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/views/referrals/courseParticipations/new.njk

https://trello.com/c/i2gzZOoW/655-add-page-for-selecting-course-name-ui
- Adds the form page for selecting a course to add a programme history to a referral. 
- Adds new `ProgrammeHistoryController` with `new` method to render the form page.
A follow on PR will add `create` method to create to `POST` to `/course-participations` and the functionality to submit the form (with validation).

(655a) Select programme for adding accredited programme history

---

server/controllers/refer/oasysConfirmationController.ts
server/controllers/refer/peopleController.ts
server/controllers/refer/reasonController.ts
server/controllers/refer/referralsController.ts
server/services/index.ts
server/services/personService.test.ts
server/services/personService.ts

Up until now, we've passed on the logged-in user's token to the Prisoner Offender Search client to authenticate them when searching for a Person in Prison by their `prisonNumber`. This has worked fine for now, but we've had to add the `ROLE_VIEW_PRISONER_DATA` role to all users to access the specific `prisoner/:id` endpoint.
Because this could potentially mean adding lots of roles to users and introduce a lot of admin overhead, we've now added the `VIEW_PRISONER_DATA` role to our client credentials, meaning users who have access to our service (POMs and Programme Teams) can make use of this role themselves.
This PR refactors the PersonService to pass the system client token generated by HMPPS Auth, rather than the user's own token as we did before. We also send through the user's username …

(827) Refactor prisoner client to take system token over user token

---

integration_tests/@types/index.d.ts
integration_tests/index.d.ts
integration_tests/pages/page.ts
integration_tests/support/commands.ts
integration_tests/tsconfig.json

Now we plan to use conditional radio buttons from govuk-frontend, we were getting an accessibility error which were preventing the tests from passing.
Updated the cypress `checkAccessibility` command to accept some rules, which we can then use on a page by page basis.
For example in page which has conditional radio buttons we can do:
`super('Add Accredited Programme history', { accessibilityRules: { 'aria-allowed-attr': { enabled: false } } })`

Update checkAccessibility cypress command to accept optional accessibilityRules

---

server/data/caseloadClient.test.ts
server/data/caseloadClient.ts
server/paths/prisonApi.ts

The previous endpoint (`/api/staff/:staffId/caseloads`) wouldn't return any caseloads for admin users (e.g. my own). It also meant we had to do a slightly roundabout journey reading the logged-in-user's staffID.
Switches to using the (apparently case-sensitive) `/api/users/me/caseLoads` endpoint and passing the logged-in user's token. This seems to allow us to fetch caseloads even if the user is an admin.
We'll be passing these caseloads to the request to the Prisoner Offender Search for a prisoner to ensure we're only searching by the logged in user's caseloads.

(814b) Switch endpoint for fetching user's caseloads

---

server/data/courseClient.test.ts
server/data/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts

https://trello.com/c/i2gzZOoW/655-add-page-for-selecting-course-name-ui
Adds new methods to the course client and course service to create a new course participation.

(655b) Update course client and service for creating a participation

---

server/utils/courseParticipationUtils.test.ts

This test was sometimes failing because the course participation related factories randomly provide a `yearStarted` in `outcome` if not specified in `build`.
Provide a `yearStarted` value to problematic test.  

Specify `yearStarted` to prevent intermittent test failure

---

.circleci/config.yml
integration_tests/e2e/refer.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/mockApis/courseParticipations.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/index.ts
integration_tests/pages/refer/selectProgramme.ts
server/@types/ui/index.d.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/views/referrals/courseParticipations/new.njk

https://trello.com/c/i2gzZOoW/655-add-page-for-selecting-course-name-ui
Note: Branched off #218 so contains changes to courseClient and courseService until that has been merged. 
Updates the select a programme form page to `POST` to `/course-participations` and redirects to the yet to be created details page. 
Also displays validation for either an unselected programme or missing text in the conditionally displayed Other text input.

(655c) Create course participation from select programme page

---

server/@types/models/CourseParticipation.ts
server/@types/models/index.d.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts

https://trello.com/c/oMnAOOLO/851-add-page-for-entering-course-details-ui-m
For the course participation details page we need to make a couple of calls.  One to get the participation and check it exists and then another to update when the form has been filled in.
- Add `CourseParticipationUpdate` type. 
- Add `findParticipation` and `updateParticipation` to `CourseClient`
- Add `getParticipation` and `updateParticipation` to `CourseService`

(851a) Update course client and service for finding and updating course participations 

---

server/@types/models/CourseParticipation.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/testutils/factories/courseParticipation.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
wiremock/stubs/courseParticipations.json

- Use more accurate type casting
- Update `CourseParticipationSetting` so that `type` is optional - this has been changed on the API and needs changing here in anticipation of work to allow updates to the course name/ID
- Require `setting` and `outcome` on `CourseParticipation`

Make course participation setting type optional; require setting and outcome (942/pre-856)

---

integration_tests/e2e/refer.cy.ts
integration_tests/mockApis/caseloads.ts
integration_tests/mockApis/prisoners.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/oasysConfirmationController.test.ts
server/controllers/refer/oasysConfirmationController.ts
server/controllers/refer/peopleController.test.ts
server/controllers/refer/peopleController.ts
server/controllers/refer/reasonController.test.ts
server/controllers/refer/reasonController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/data/prisonerClient.test.ts
server/data/prisonerClient.ts
server/paths/prisonerOffenderSearch.ts
server/services/personService.test.ts
server/services/personService.ts
server/testutils/helpers.ts
wiremock/scripts/stubPrisoners.ts

https://trello.com/c/PeLVF8dJ/814-ensure-referrers-cant-refer-people-outside-their-active-caseload-ui
As of #233, we have the user's caseloads stored in the `res.locals.user` variable, fetched from the Prison API.
Now that we have those, we can query the Prisoner Offender Search's `match-prisoners` endpoint with the user's prison number and the logged-in user's caseloads to only allow users to search for people in prisons that are part of their caseload to prevent them seeing any one they shouldn't.
Switches to using the Prisoner Offender Search's POST `match-prisoners` endpoint when looking up a user to refer (as well as in the banner on each page). This has no visible changes to users, as the functionality is the same, but they'll get a "user not found" error if they try to look up a …

(814d) Use Prisoner Offender Search `match-prisoners`endpoint

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/confirmPerson.ts
integration_tests/pages/refer/deleteProgrammeHistory.ts
integration_tests/pages/refer/index.ts
integration_tests/pages/refer/programmeHistory.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/views/referrals/courseParticipations/delete.njk

This adds the delete course participation page. It doesn't implement the destroy action - that will come in another PR

(853a) Delete course participation page

---

server/data/restClient.test.ts
server/data/restClient.ts
server/sanitisedError.test.ts
server/sanitisedError.ts
server/utils/routeUtils.ts

#247 added the page for deleting course participations, but not the destroy action. Our codebase doesn't currently support DELETE requests
- Add support for DELETE requests
- Add `RestClient` tests
- Remove retries on POST and PUT requests, per the template and Approved Premises

(853b) Add delete request support

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/pages/refer/programmeHistory.ts
integration_tests/pages/refer/programmeHistoryDetails.ts
server/controllers/refer/courseParticipationDetailsController.test.ts
server/controllers/refer/courseParticipationDetailsController.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/utils/formUtils.test.ts
server/utils/formUtils.ts
server/views/referrals/courseParticipations/course.njk
server/views/referrals/courseParticipations/details/show.njk
server/views/referrals/courseParticipations/index.njk

https://trello.com/c/oMnAOOLO/851-add-page-for-entering-course-details-ui-m
This PR now allows the course participation detail form to be submitted to update a course participation with further details and redirects to the programme history index page with success message when successful.  
It also displays an error message for both year started and year completed if a non numeric value is entered.

(851c) Submit course participation details

---

server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts

#243 added a new `processDetailsFormData` method, using `process` instead of `processed` to avoid creating a false impression of there being no side effects
- Update existing method to be in line with better-named new method

Rename method for clarity

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/pages/refer/programmeHistoryDetails.ts
server/controllers/refer/courseParticipationDetailsController.test.ts
server/controllers/refer/courseParticipationDetailsController.ts
server/testutils/factories/courseParticipation.ts
server/utils/formUtils.test.ts
server/utils/formUtils.ts

The course participation details form needs to be able to display current values when being visited as part of the **Change** journey.
Updated `FormUtils.setFormValues` so it can take a `defaultValues` param.  These values then get set in `res.locals.formValues` but will get overwritten by the newly inputted values if `req.flash('formValues')` is called when there is an error on the form.
Also added `shouldHaveCorrectFormValues` to the Programme history page for integration tests to use to check that form values are correctly displayed.

(950a) Update course participation details to pre-populate course participation values

---

server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts

This is a slight refactoring of #249 taking on @yndajas's helpful feedback. It felt easier to start from scratch and handle in one commit, rather than rebase the whole thing to make sense, as this is a more joined-up approach.
https://trello.com/c/0pCdIJDt/884-display-not-known-on-programme-history-when-the-user-hasnt-answered-a-question
Previously, we wouldn't show a row against a field that a user hadn't filled in when creating a CourseParticipation. We now would like to highlight this as "not known" to prompt users to enter any information they do know, rather than ignoring the field. We don't want to make the fields required, as this would prevent people who genuinely don't have this information from being able to add anything.
- Displays "Not known" for rows where the …

(888 - take 2) Display unanswered CourseParticipation fields as "Not known"

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/pages/refer/programmeHistoryDetails.ts
server/@types/models/CourseParticipation.ts
server/controllers/refer/courseParticipationDetailsController.test.ts
server/controllers/refer/courseParticipationDetailsController.ts
server/testutils/factories/courseParticipation.ts
server/testutils/factories/courseParticipationOutcome.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/views/referrals/courseParticipations/details/show.njk
wiremock/stubs/courseParticipations.json

On the API, a `detail` field has been added to the course participation model. This will replace the one on the course participation outcome
Moves to the new field, allowing the API to drop the old one
- [? definitely dev] ... and they have been released to production already

(954) Move to new participation `detail` field

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/mockApis/courseParticipations.ts
integration_tests/pages/refer/deleteProgrammeHistory.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/paths/refer.ts
server/routes/refer.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/views/referrals/courseParticipations/delete.njk

A delete page now exists and generic delete functionality has been added to the app
- Destroy participation on confirmation from delete page and redirect to participation index with a flashed message
Note the uncertainty about naming here mentioned in the commits: delete vs destroy outside the controller

(853d) Destroy course participations

---

server/views/referrals/courseParticipations/index.njk

We should to update the E2E tests now that the programme history journey is mostly built. Two buttons serve the same purpose but have a different label dependent on whether there are existing course participations
- Add a shared test ID attribute to allow us to add an E2E test that will work regardless of whether the dev test user has existing course participations

Add `data-testid` for E2E tests

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/pages/page.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts

When adding E2E tests for the programme history journey, we discovered that the order of course participations on the page was less predictable than expected
- Fix the order of course participations on the programme history page
- Fully mock a semi-mocked method
[Unclear sorting logic: mostly sorted by created at, but currently not entirely on dev]
1 = first added, 2 = second added

(982) Sort programme history

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/tsconfig.json
server/@types/express/index.d.ts
server/@types/server/index.d.ts
server/@types/ui/index.d.ts
server/@types/users/index.d.ts
server/middleware/roleBasedAccessMiddleware.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/utils/index.ts
server/utils/routeUtils.ts
tsconfig.json

A couple of type-related tidy ups
I wonder if we could clarify what the `server/index.d.ts` and `users/index.d.ts` should be used for/why we need them alongside `ui/index.td.ts` and the `models` folder? Perhaps one for the upcoming ADRs

Tidy up types

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/pages/refer/programmeHistory.ts
integration_tests/pages/refer/taskList.ts
server/@types/models/Referral.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/oasysConfirmationController.test.ts
server/controllers/refer/oasysConfirmationController.ts
server/controllers/refer/reasonController.test.ts
server/controllers/refer/reasonController.ts
server/data/referralClient.test.ts
server/paths/refer.ts
server/routes/refer.ts
server/services/referralService.test.ts
server/testutils/factories/referral.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/courseParticipations/index.njk

https://trello.com/c/Fl2C9Vve/967-set-and-fetch-hasreviewedprogrammehistory-ui
Add `updateHasReviewedProgrammeHistory` method which updates the `hasReviewedProgrammeHistory` value on a referral when used by the form on the programme history index.  
When clicking Continue on the Programme history index, `updateHasReviewedProgrammeHistory` is set to true and the user is redirected back to the task list where the status of the **Review Accredited Programme history** task is set to `Completed`.

(967) Set `hasReviewedProgrammeHistory` on a referral

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/e2e/refer/submit.cy.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/checkAnswers.ts
server/@types/ui/index.d.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/checkAnswers.njk

- Add programme history to check your answers
- A few small fixes and tidy ups

(969) Add programme history to check your answers

---

cypress.config.ts
docker-compose.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration.env
integration_tests/mockApis/auth.ts
integration_tests/mockApis/manageUsers.ts
server/@types/users/index.d.ts
server/config.ts
server/data/hmppsAuthClient.test.ts
server/data/hmppsAuthClient.ts
server/data/hmppsManageUsersClient.test.ts
server/data/hmppsManageUsersClient.ts
server/data/index.ts
server/middleware/populateCurrentUser.test.ts
server/middleware/populateCurrentUser.ts
server/services/index.ts
server/services/userService.test.ts
server/services/userService.ts
server/utils/appInsightsUtils.ts

We need to display the actual names of the user who makes a referral, not just their username.  To do this it means making use of https://github.com/ministryofjustice/hmpps-manage-users-api.
https://trello.com/c/K6mwNUHH/968-fetch-name-of-referrer-rather-than-username-for-programme-history-and-cya-page
This PR is for integrating the HMPPS Manage Users API and in the first instance, replacing the existing `/user/me` endpoint from HMPPS Auth with the new `/users/me` and `/users/${username}` from HMPPS Manage Users API.
This also meant making some changes to some of the User types as the response schema in the new api is slightly different.
ready …

(968a) Add HMPPS Manage Users API

---

integration_tests/e2e/app.cy.ts
integration_tests/e2e/authentication.cy.ts
integration_tests/e2e/find.cy.ts
integration_tests/e2e/health.cy.ts
integration_tests/e2e/refer.cy.ts
integration_tests/e2e/refer/confirmOasys.cy.ts
integration_tests/e2e/refer/create.cy.ts
integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/e2e/refer/reason.cy.ts
integration_tests/e2e/refer/show.cy.ts
integration_tests/e2e/refer/submit.cy.ts
integration_tests/e2eReferDisabled/find.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts

We have a lot of unDRY code in our integration tests, which is making navigation within specs and comparison across contexts and specs a little painful. When adding new specs and contexts there's a not insignificant careful copy/paste overhead, which also rears its head in review
- Simplify assignment and stubbing
- DRY up sign in

(998) Simplify integration tests

---

integration_tests/e2e/refer/programmeHistory.cy.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts

We already validate that course participation years are a number
- Validate that course participations are four digits long, no earlier than 1990 and no later than the current year

(975) Additional year validation

---

integration_tests/e2e/refer/submit.cy.ts
integration_tests/mockApis/auth.ts
integration_tests/mockApis/manageUsers.ts
server/data/hmppsManageUsersClient.ts
server/services/userService.test.ts
server/services/userService.ts
server/testutils/factories/index.ts
server/testutils/factories/user.ts

Will be used in the first instance to display the name of the user who added a programme history/course participation record.
- Added `UserService.getUserFromUsername` with error handling.
- Also added `userFactory` to help with testing
- Updated auth and user stubs for integration tests to use `userFactory`

(968b) Add `getUserFromUsername` to `UserService`

---

.eslintrc.json

[typescript-eslint 6.8.0][1] added a new rule extended from base `eslint` to prefer destructuring. We already have an implicit preference for this for objects, with all code compliant
- Turn the rule on
The rule is disabled for arrays, since [this is not recommended][2] if you want to allow accessing array elements directly via their indices, which we do
[1]: https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#680-2023-10-16
[2]: https://eslint.org/docs/latest/rules/prefer-destructuring#when-not-to-use-it

Turn on `prefer-destructuring`

---

integration_tests/e2e/refer/programmeHistory.cy.ts
server/controllers/refer/courseParticipationDetailsController.test.ts
server/controllers/refer/courseParticipationDetailsController.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts

Currently the only success message that gets shown when adding/updating programme history entries is "You have successfully added a programme"
- Show "added" or "updated" as appropriate in programme history success messages (outside of deletion)
- A few very small tidy ups in the integration tests
Where appropriate:

(956) Fix programme history success messages

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/e2e/refer/submit.cy.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/checkAnswers.ts
integration_tests/pages/refer/programmeHistory.ts
server/@types/ui/index.d.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/services/index.ts
server/testutils/factories/user.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts

We want to display the name of the user who has added a programme history record.
- Updated the User factory to return randomly formatted name to replicate what the manage-users-api might return.
- Add a new `presentCourseParticipation` method to `CourseService` which can be called from controllers where we need to return a formatted name for the `addedBy` user.

(968c) Show users name instead of username on programme history entries

---

integration_tests/e2e/refer/programmeHistory.cy.ts
integration_tests/mockApis/courses.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/data/courseClient.test.ts
server/data/courseClient.ts
server/paths/api.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts

To provide a unique list of course names on the course selection form pages.
https://trello.com/c/iqCz1E2v/993-use-programme-history-course-names-endpoint-ui-s
- Update course client and service to use new `/courses/course-names` endpoint.
- Update `new` and `editCourse` controller methods to use new endpoint and return correctly formatted values.

(993) Use new course names endpoint

---

integration_tests/e2e/refer.cy.ts
integration_tests/e2e/refer/submit.cy.ts
server/controllers/refer/courseParticipationDetailsController.test.ts
server/controllers/refer/courseParticipationDetailsController.ts
server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/oasysConfirmationController.test.ts
server/controllers/refer/oasysConfirmationController.ts
server/controllers/refer/reasonController.test.ts
server/controllers/refer/reasonController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts

You can currently still access pages/actions related to a referral even after it's been submitted, which could lead to unwanted changes being made
Closes #290 (replacement)
- Redirect from pages related to a referral once submitted

(815) Redirect submitted referral redux

---

script/test
script/test-history

In `script/test`, it's currently only possible for `trap cleanup EXIT` to run on successful test runs, which is not very helpful
Another issue is that it can be hard to differentiate successful and unsuccessful `script/test` runs at a glance/with limited space
- Fix use of `trap cleanup EXIT` so that `cleanup` is invoked on failed test runs
- Show a message on successful `script/test` runs

Fix `script/test` cleanup and improve feedback

---

script/update

This fixes a minor inconvenience: if we've bumped our Node version, when running `script/update` the script will exit when trying to update the GOV.UK types because it hasn't yet run `script/bootstrap` to install the new Node version. This reorders things so that the GOV.UK types are updated after Node and npm updates

Regenerate GOV.UK types after bootstrap

---

README.md
integration_tests/pages/refer/checkAnswers.ts
integration_tests/pages/refer/taskList.ts
server/paths/refer.ts
server/utils/courseParticipationUtils.test.ts
server/utils/referralUtils.test.ts

https://trello.com/c/6THL9PqW/1036-update-refer-paths-for-creating-and-viewing-a-referral
- Prefix refer paths with `/refer`
- Prefix draft referral paths with `/new` (e.g. full draft referral would be `refer/new/referrals/:id`)

(1036) Update refer and draft referral URL paths

---

server/data/courseClient.test.ts
server/data/referralClient.test.ts

Pact tests are still failing, due to IDs changing on each merge as they're generated by factories.
The backend provider tests rely on these, and they're currently changing with each merge to main, making it impossible to match on the API side. I've changed quite a few IDs here, but I'm making them line up with the test entities we're creating on the API in https://github.com/ministryofjustice/hmpps-accredited-programmes-api/blob/main/src/test/resources/db/migration/R__test_data.sql

Add explicit IDs for entities in Pact tests

---

server/data/courseClient.test.ts

Because of the way our tests are written on the provider side, we need to use a unique prison number for this test.
Uses a unique prison number for one of our Course client tests.

Use new prison number for Pact test

---

integration_tests/e2e/refer/submitted.cy.ts
integration_tests/e2eReferDisabled/refer.cy.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/index.ts
integration_tests/pages/refer/submittedPersonalDetails.ts
server/@types/ui/index.d.ts
server/controllers/index.ts
server/controllers/shared/index.ts
server/controllers/shared/submittedReferralsController.test.ts
server/controllers/shared/submittedReferralsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/dateUtils.test.ts
server/utils/dateUtils.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/submitted/partials/layout.njk
server/views/referrals/submitted/personalDetails.njk

https://trello.com/c/VU6o1f4K/885-add-basic-page-for-viewing-a-referral-personal-details-m
- Add new partial for all of the view submitted referral details pages to use
- Add paths for submitted referral pages (including the yet to be created ones) and created the navigation
- Add new `SubmittedReferralsController` with `personalDetails` and also a shared `getPageDetails` method to be used by all view submitted pages.

(885a) Review Referral Personal details page

---

README.md
doc/how-to/manage-infrastructure.md

We've got a shared Postman team which we use for interacting with APIs, that I've recently tidied up to use environments.
Adds instructions for how to get secret values for interacting with APIs.

Add instructions for Postman to readme

---

server/data/referralClient.test.ts

The test for creating a Referral is currently failing on the provider side, as the Offering we assign to the Referral needs to exist in the test DB when creating the Referral, yet we're currently generating one randomly with the Referral factory. This means with each merge the provider is looking for a referral with the newly-generated ID.
Adds fixed ID of offering that exists in the API test database.

Add specific offering ID for Pact test

---

integration_tests/e2e/refer/submit.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/refer/checkAnswers.ts
server/@types/models/Referral.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/data/referralClient.test.ts
server/data/referralClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/referral.ts

When submitting check your answers page, instead of using the PUT endpoint for changing the referral’s status, hit `referrals/:id/submit`, allowing the API to set this submitted on date and update the status for us.
https://trello.com/c/msWXJ5HB/1034-update-ui-to-use-new-referrals-id-submit-endpoint-on-referral-submission-ui-s
- Update referral client and service to utilise new endpoint.
- Update integration tests, including updating how we stub the calls to GET a referral.  One of the integration tests was giving a false positive because the referral was already being stubbed with a status of `referral_submitted`, before it was actually submitted.
As part of our continuous deployment strategy we must ensure that this …

(1034) Use submit referral endpoint

---

integration_tests/mockApis/caseloads.ts
server/@types/models/Person.ts
server/@types/prisonApi/index.d.ts
server/@types/prisonerOffenderSearch/index.d.ts
server/data/caseloadClient.test.ts
server/data/caseloadClient.ts
server/data/index.ts
server/data/sentenceInformationClient.test.ts
server/data/sentenceInformationClient.ts
server/paths/prisonApi.ts
server/testutils/factories/index.ts
server/testutils/factories/person.ts
server/testutils/factories/prisoner.ts
server/testutils/factories/sentenceAndOffenceDetails.ts
server/utils/personUtils.test.ts
server/utils/personUtils.ts
wiremock/scripts/stubCaseloads.ts

We need to access sentence information including type and various dates
- Update `Person`/`Prisoner` types to include `bookingId` to enable sentence information requests
- Add new type
- Update paths
- Add sentence information client and sentence `findSentenceAndOffenceDetails` method

(889a) Add sentence information client

---

server/controllers/refer/courseParticipationsController.test.ts
server/controllers/refer/courseParticipationsController.ts
server/controllers/refer/referralsController.test.ts
server/controllers/refer/referralsController.ts
server/services/courseService.test.ts
server/services/courseService.ts

https://trello.com/c/1Ihtlxml/893-add-page-for-viewing-a-referrals-programme-history-m
We're about to add a new page for viewing a programme's Course Participations. There's a fair bit of code we can DRY up for use when building that page, both in terms of implementation and tests.
Encapsulates the logic for converting Course Participations into a summary list in a service method, rather than calling it separately in multiple controllers.
There may be a bit of tidying up to do here, but I'm opening this to get feedback while people are around this week!

(893a) Refactor course participation presentation

---

integration_tests/pages/refer/new/checkAnswers.ts
integration_tests/pages/refer/new/programmeHistory.ts
server/views/referrals/new/checkAnswers.njk
server/views/referrals/new/courseParticipations/index.njk

Updates text on the Check your answers and Programme History index pages to brings the messaging in line with the text we'll show on the submitted referral page (added in #322) when there's no programme history to show.

Tweak message for no Accredited Programme history

---

server/@types/prisonApi/index.d.ts
server/testutils/factories/sentenceAndOffenceDetails.ts
server/utils/sentenceInformationUtils.test.ts
server/utils/sentenceInformationUtils.ts
wiremock/stubs/sentenceAndOffenceDetails.json

https://trello.com/c/kCnxzy9H/1076-use-sentencestartdate-rather-than-sentencedate-for-sentence-information-page-xs
We previously read the `sentenceDate` field returned on a person's sentence information returned from NOMIS.
We now read the `sentenceStartDate` instead. This is clearer to users and more likely to have a value set in NOMIS.

(1076) Use `sentenceStartDate` instead of `sentenceDate`

---

integration_tests/e2e/refer/show.cy.ts
server/@types/models/Person.ts
server/@types/prisonerSearch/index.d.ts
server/testutils/factories/factoryHelpers.ts
server/testutils/factories/person.ts
server/testutils/factories/prisoner.ts
server/utils/personUtils.test.ts
server/utils/personUtils.ts
wiremock/stubs/prisoners.json

We need to show various release dates when viewing details about a referral
- Fix missing `sentenceStartDate` on generated people
- Add release dates and life sentence status to prisoner model
- Add prisoner release dates and calculate earliest release date on person model

(1066a) Add release dates to prisoner/person

---

server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/data/index.ts
server/services/courseService.test.ts
server/services/referralService.test.ts

We recently moved to mapping clients to APIs more consistently. We want to avoid creating a very large client for our internal API, so to loosely follow the same principle we're nesting the relevant clients in an `accreditedProgrammesApi` folder
- Nest internal API clients

Nest internal clients

---

integration_tests/pages/refer/new/checkAnswers.ts
server/views/partials/keylessSummaryCard.njk
server/views/referrals/new/checkAnswers.njk

We have more uses for keyless summary cards now*, so this extracts the logic for building one of these into a macro that wraps around the GOV.UK summary list macro. This avoids us adding in a lot of literal HTML across the codebase and the potential for us to become out of sync with any GOV.UK Frontend macro changes
\* they will be needed for the sentence details and release dates summary cards (in the view referral sentence information page) when they have no data
We don't have a need for formatted text (using the `html` key instead of `text`) in the body of the card yet, but the macro has been written such that it supports that
Minor change in vertical spacing, more in line with other summary cards
As part of our …

(1110) Add `keylessSummaryCard` macro

---

server/@types/prisonApi/index.d.ts
server/data/prisonApiClient.test.ts
server/data/prisonApiClient.ts
server/paths/prisonApi.ts
server/testutils/factories/index.ts
server/testutils/factories/inmateDetail.ts
server/testutils/factories/offenceDto.ts
server/testutils/factories/offenceHistoryDetail.ts

We need to use a couple of new endpoints to display a persons offence history with further offence detail.
After some digging and discussions we have agreed to use the endpoints added in this PR.
- Use `{{prison_api}}/api/bookings/offenderNo/:offenderNo?extraInfo=true` to get the details for a person/offender with `offenceHistory`.
- Then use `{{prison_api}}/api/offences/code/:offenceCode` to get further information for an offence.

(886c) Add new Prison API client methods for offence history details

---

package.json

As of `1.0.0` (which we depend on), `prettier-plugin-jinja-template` depends on Prettier 3+, so we no longer need this override

Remove redundant override

---

server/controllers/refer/new/courseParticipationDetailsController.test.ts
server/controllers/refer/new/courseParticipationDetailsController.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/middleware/populateCurrentUser.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/services/index.ts
server/services/organisationService.test.ts
server/services/referralService.test.ts

https://trello.com/c/VxKOqk1u/803-use-system-token-to-communicate-with-api-m
We've had a new role added to secure our API endpoints (`ACCREDITED_PROGRAMMES_API`). This will require authenticating with client credentials, so we need to use our system token rather than the usual user token.
This is the second half of #343.
Uses the system token rather than the user token for the Course Client methods, and updates services & controllers to generate and pass the correct token. 
I've split this PR up into lots of commits to hopefully keep it easier to review, but I'll squash them together once it's been approved to ensure we don't have any failing tests on a commit.
There may be a few clashes with #350 here, particularly with renaming, so we'll need to tidy some things up depending on which …

(803b) Use system token rather than user token for calls to Accredited Programmes API - Course Client

---

integration_tests/pages/page.ts
server/paths/assess.ts
server/paths/refer.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts

When viewing a referral on the assess path, the links in the sidebar don't work correctly. They link back to refer and also don't show the active state.
Update `ReferralUtils.viewReferralNavigationItems` to use assess paths if current path begins with `/assess`.

Update view referral side navigation so it works correctly with the `/assess` path

---

.circleci/config.yml

We must have updated some e2e test dependencies in the other repo, as the e2e tests are failing to run on CI. We're getting a message that we need to use a later version of Playwright.
Updates the version of the Playwright image we're running on CI.

Update Playwright image to get E2E tests running again on CI

---

integration_tests/pages/shared/showReferral/offenceHistory.ts
integration_tests/support/sharedTests.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/utils/offenceUtils.test.ts
server/utils/offenceUtils.ts
wiremock/stubs/offenderBookings.json

Need to display messaging when there are missing details for an offence on the offence history page.
1. Display messaging when offence values are undefined
2. Also fixes issues where todays date would be shown if `offenceDate` is `undefined`

(886f) Add content for when there are missing offence details

---

README.md
integration_tests/e2e/assess.cy.ts
integration_tests/e2e/assess/show.cy.ts
integration_tests/e2e/refer.cy.ts
integration_tests/e2e/refer/show.cy.ts
integration_tests/pages/badRequest.ts
integration_tests/support/sharedTests.ts
server/@types/prisonApi/imported/index.d.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/additionalInformation.njk

Currently you can access referral show pages (meant for submitted referrals) with a draft referral
- Redirect to relevant page if the referral is a draft, which will automatically auth error for non-referrers

(1057) Restrict show referral access

---

integration_tests/e2e/find.cy.ts
integration_tests/e2e/refer/new/create.cy.ts
server/@types/models/Course.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/services/personService.ts
server/testutils/factories/course.ts
server/views/courses/offerings/show.njk

We have some non-referable courses, but currently you can make a referral to them
- Hide "Make a referral" button for non-referable courses
- Guard against request to create a referral to a non-referable course
This doesn't prevent users from manually going to the Refer pages with the ID of an offering that's for a non-referable course, but it does guard against requests made to create one. Later work could redirect back to the offering if the user has accessed the `start`, `new`, or `create` referrals actions, or the `find` and `show` new referrals people actions, with a flashed message explaining the redirect

(678) Hide "Make a referral" on non-referable courses

---

server/@types/models/Paginated.ts
server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/index.ts
server/testutils/factories/referral.ts
server/testutils/factories/referralSummary.ts

We need to display the referrals for organisation in a table for the case list/dashboard view.
- Add new types and client method to use the `{{accredited_programmes_api}}/referrals/organisation/:organisationId/dashboard` endpoint.
- Add new type and service to get the dashboard content as well as the person details to create the case list.
Pagination to be handled at a later date.
More columns to be added soon too but this gets a basic list working.

(1086a) Add client and service methods for upcoming case list page

---

server/utils/referralUtils.test.ts
server/utils/referralUtils.ts

We need to display the status of a referral using https://design-system.service.gov.uk/components/tag/.
Add `statusTagHtml` to `ReferralUtils` which provides a colour and formatted text for each of the required statuses and has a fallback to grey when there is no matching status.  We may decide to not show a tag at all but for now this is OK as I believe new statuses will be added in future.
Use newly added util in `caseListTableRows` method.

(1086c) Add `statusTagHtml` to `ReferralUtils`

---

integration_tests/e2e/refer/show.cy.ts
integration_tests/pages/shared/showReferral/sentenceInformation.ts
integration_tests/support/sharedTests.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/utils/personUtils.ts
server/views/referrals/show/sentenceInformation.njk

We need to display a general no release dates message when there are no release dates at all, instead of an individual message for each release date.
If all of the below fields are `undefined` then display `There are no release dates for this person` message.
- `conditionalReleaseDate`
- `homeDetentionCurfewEligibilityDate`
- `paroleEligibilityDate`
- `sentenceExpiryDate`
- `tariffDate`

(1109) Add no release dates message on sentence information page

---

server/controllers/shared/caseListController.test.ts
server/controllers/shared/caseListController.ts
server/middleware/populateCurrentUser.test.ts
server/middleware/populateCurrentUser.ts

The `activeCaseloadId` has been recently deprecated in the Manage Users API response, and we’re advised to read this from the Prison API.
https://trello.com/c/Y9nDk05S/1141-add-activecaseloadid-to-userdetails-when-populating-current-user-m
Add an `activeCaseLoadId` property to `res.locals.user` so we can use this elsewhere such as the `CaseListController`.

(1141) Add `activeCaseLoadId` property to `res.locals.user`

---

server/controllers/shared/referralsController.test.ts

A test for the sentence information page intermittently failed as the person factory could sometimes return a person with no release dates at all. 
Updated the flakey test so it replicates when a person has some but not all release related dates.  `conditionalReleaseDate` will be `undefined` but `paroleEligibilityDate` will be `'2024-01-02'` so this will mean that `hasReleaseDates` is `true` and `releaseDatesSummaryListRows` is not an empty array.

Fix release dates test for sentence information

---

integration_tests/e2e/assess/caseList.cy.ts
server/@types/models/Referral.ts
server/controllers/shared/referralsController.test.ts
server/testutils/factories/referral.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts

Just spotted this when working on the case list filters.

Fix `awaiting_assessment` typo and flakey test file

---

.eslintrc.json
integration_tests/pages/refer/new/selectProgramme.ts
server/data/hmppsAuthClient.test.ts
server/data/tokenStore.ts
server/middleware/populateCurrentUser.test.ts
server/middleware/setUpWebSession.ts

This rule ensures single quotes are used whenever possible, with double quotes and template literals only used when an individual single quote string wouldn't suffice (template literals are still favoured over `'string' + variable`)
- Disallow redundant template literals

Disallow redundant template literals

---

.eslintrc.json
integration_tests/pages/refer/new/selectProgramme.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/hmppsAuthClient.test.ts
server/data/tokenStore.ts
server/middleware/populateCurrentUser.test.ts
server/middleware/setUpWebSession.ts

Keeping the API and UI in line with Pact tests is becoming a burden, and the DRYness of the tests on the UI side is making it hard to spot the difference
Related API PR: https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/178
- WET Pact tests
- Linting changes from #378

(1167b) WET pact

---

server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/referralClient.test.ts

Pacts are still failing - due to nullable reasons and statuses not lining up. This is another attempt at fixing them.

Make pacts line up with API side

---

server/data/accreditedProgrammesApi/referralClient.test.ts

Add status to factory-built referrals in Pact test. This is failing due to checking the `submittedOn` date for `null` in the API. If we specify the status, we check the non-null value here.

Specify referral status in pact test

---

server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/testutils/factories/courseParticipationOutcome.ts

The Pact tests have been failing for a while and are incredibly brittle due to the way we set up state on the API before running them and then create/update/delete entities with state that persists between tests. We should definitely refactor this behaviour as soon as possible.
While we wait for time to refactor, this PR updates the Pact contract tests to:
- Ensure we're never combining nullable and non nullable fields (e.g. `secondaryContactEmail` and `yearStarted`/`yearCompleted` in expected array responses, as Pact doesn't handle these well.
- Ensure we're not making assertions on created/updated/deleted entities like referrals and offerings in tests. This is due to the way state is handled in the API, as it's set up at the beginning of the test run. This has been incredibly painful to …

Miscellaneous pact fixes

---

server/views/referrals/new/people/show.njk

Smaller screens accounted for by default too and link will go underneath the full width button.
https://trello.com/c/Fk5FrFIA/1102-move-enter-a-different-identifier-link-xs
Put both actions inside `.govuk-button-group`.  This meant taking the **Continue** button out of the form but have added an `id` to the form itself and a `form` value to the button.

(1102) Move `Enter a different identifier` link inline with Continue button

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/pages/shared/caseList.ts
server/@types/ui/index.d.ts
server/controllers/shared/caseListController.test.ts
server/controllers/shared/caseListController.ts
server/paths/assess.ts
server/routes/assess.ts
server/utils/index.ts
server/utils/pathUtils.test.ts
server/utils/pathUtils.ts
server/utils/referralUtils.test.ts
server/utils/referralUtils.ts
server/views/referrals/caseList/show.njk

We identified a few things that would clean up the URLs used when filtering the case list
- Omit unused filter fields from query params
- Use 'strand' as audience query param
- Use lower case for query params
Both params: `/assess/referrals/case-list?audience=General+violence+offence&status=REFERRAL_SUBMITTED`
One param: `/assess/referrals/case-list?audience=General+violence+offence&status=`
Both params: `/assess/referrals/case-list?strand=general+violence+offence&status=referral+submitted`
One param: `/assess/referrals/case-list?strand=general+violence+offence`

(1170) Tweak filter URLs

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/mockApis/courses.ts
integration_tests/pages/shared/caseList.ts
server/@types/ui/index.d.ts
server/controllers/shared/caseListController.test.ts
server/controllers/shared/caseListController.ts
server/controllers/shared/index.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/paths/assess.ts
server/routes/assess.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/utils/stringUtils.test.ts
server/utils/stringUtils.ts
server/views/referrals/caseList/show.njk

We need to show case lists for each course for an organisation.
Adds a primary navigation to top of the case list page which contains links to a case list page for each course for an organisation. When visiting each course page, there will be a case list of referral summaries for that course.

(1131) Assess referral case lists by course name

---

integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/pages/refer/new/programmeHistory.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/views/referrals/new/courseParticipations/index.njk

https://trello.com/c/uWDsgCor/1104-update-programme-history-page-without-history-state-s
https://trello.com/c/wdCsDyAW/1105-update-programme-history-page-with-history-state-s
Content at the top of the page changed for both with history and without history states
Buttons switched and text changed
**Without history:**
**With history:**
**Without history:**
**With history:**
**With success message after adding:**

(1104 & 1105) Update Programme History page content

---

integration_tests/pages/page.ts
integration_tests/support/sharedTests.ts
server/@types/models/Referral.ts
server/controllers/shared/index.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/testutils/factories/referral.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts

https://trello.com/c/FyFfGdPj/1123-use-referrerusername-field-to-display-name-of-person-who-created-a-referral-m
Use the user `referrerUsername` value on a Referral and call manage users api to get the referring users name and display it on the view referral page and sub pages.

(1123) Add Referrer name to the top of view referral pages

---

script/utils/generateApiSeeds/tableDefinitions.ts
script/utils/generateApiSeeds/tableRecords.ts
server/@types/models/Referral.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/referral.ts
wiremock/stubs/referrals.json

Related to API change https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/195 

(1197) Remove `referrerId` from Referral

---

integration_tests/e2e/assess/caseList.cy.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/testutils/factories/factoryHelpers.ts
server/testutils/factories/referral.ts
server/testutils/factories/referralSummary.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

On the assess case list view, we need to filter out any referrals with the REFERRAL_STARTED status.
The dashboard endpoint now allows us to pass a list of statuses so we can filter by only the statuses we need.  The controller makes the request for all statuses except `referral_started` but will still use the selected filter value.

(1183) Filter out draft referrals from assess case list

---

server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/services/userService.test.ts
server/services/userService.ts

When a user is not found a message is returned. The behaviour for two controllers was to throw if the user were missing.
Note the original function and its behaviour still exists as it may be used by other work in progress, and that behaviour may be preferred. If this is not the case a separate task could be actioned to remove it.

(1198) Handle missing user loading

---

server/views/referrals/new/courseParticipations/course.njk
server/views/referrals/new/courseParticipations/details/show.njk
server/views/referrals/new/new.njk

Update refer journey input size boxes to match prototype
Requirements: https://trello.com/c/ritmihM7/1099-change-new-referral-input-sizes-xs

(1099) Update refer journey input size boxes to match prototype

---

server/controllers/refer/caseListController.test.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

We need to show referrals with the `REFERRAL_STARTED` status on a separate Draft referrals page.
Add new navigation item to new page and update associated tests. 
Table content including progress column to be done separately.

(1139a) Add Draft referrals to My referrals

---

server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/services/referralService.test.ts
server/services/referralService.ts

We need to display how many tasks have been completed for a draft referral in the draft referrals case list table.
- Adds new method to `ReferralService` to calculate how many of the required fields on a referral have truthy values.
- Above method called in `ReferCaseListController.show` to return a `tasksCompleted` value that we can use in the table template.

(1139b) Draft referral progress

---

server/data/accreditedProgrammesApi/referralClient.test.ts

We recently added Pact contracts for fetching a logged-in user's Referrals.
This is proving very difficult to fulfil on the API side due to our poor test setup reusing data between tests. See https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/223 for more information.
In the flow of these Pact tests, we update one Referral for the logged-in user to mark it as `submitted` (and thus give it a `submittedOn` date), and create a new in-progress Referral (with a `null` `submittedOn` date).
When we make this request for the logged-in user's Referrals, we get back a Referral with a `submittedOn` date and one without, which Pact [can't handle](https://github.com/pact-foundation/pact-js/issues/393) - to correctly verify the shape of the objects we're getting back, the …

Temporarily skip Pact test

---

server/@types/models/OffenceDetail.ts
server/@types/models/index.d.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/data/index.ts
server/paths/api.ts
server/services/oasysService.test.ts
server/services/oasysService.ts
server/testutils/factories/index.ts
server/testutils/factories/offenceDetail.ts

https://trello.com/c/Pdp4YHal/1225-add-client-service-classes-for-querying-our-oasys-endpoints-m
- Added new client and service classes for oasys related endpoints from accredited programmes api
- Added offence detail related type, factory and related methods
-  These may well likely change as the endpoints are developed

(1225) Oasys client and service

---

server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

Previously we were using the Assess paths everywhere for the link to view an individual referral
- Allow Refer paths to be used for links to referrals in the Refer case lists

(1126b) Use Refer paths in Refer case lists

---

server/@types/models/OffenceDetail.ts
server/controllers/shared/index.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/services/index.ts
server/services/oasysService.test.ts
server/services/oasysService.ts
server/utils/index.ts
server/utils/risksAndNeeds/offenceAnalysisUtils.test.ts
server/utils/risksAndNeeds/offenceAnalysisUtils.ts
server/views/referrals/show/risksAndNeeds/offenceAnalysis.njk
wiremock/scripts/stubAccreditedProgrammesApi.ts
wiremock/stubs/index.ts
wiremock/stubs/oasysOffenceDetail.json

(1214c) Offence analysis page content

---

server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/testutils/factories/courseParticipation.ts
server/testutils/factories/courseParticipationOutcome.ts
server/testutils/factories/courseParticipationSetting.ts
server/testutils/factories/factoryHelpers.ts
server/testutils/factories/referralSummary.ts

Randomly generating either a string or undefined value for fields in Pact tests is making it impossible for the Provider to supply them in its own Pact tests.
Closes #445
An alternative approach to #445.

Provide non-optional fields in Pact contracts

---

.circleci/config.yml
integration_tests/e2e/assess.cy.ts

This is largely taken from [the approach taken on Approved Premises](https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/818). Our main integration test suite takes roughly 5.5-7.5 minutes to run on CI, while parallel jobs take a maximum of around 2.5 minutes. This can lead to devs waiting a long time whenever a change is made before they can confirm everything is passing on CI, and to move onto preprod and prod deployment where appropriate, interrupting the flow of a task
The refer-disabled integration tests aren't as comprehensive at this point, but in any case, they aren't causing anywhere near the slow down as the main suite, and it won't be long before they become redundant (when Refer launches), so there's no need to tamper with them at present
- Run integration …

Run integration tests in parallel

---

README.md
integration_tests/e2e/refer.cy.ts
integration_tests/e2e/refer/new/additionalInformation.cy.ts
integration_tests/e2e/refer/new/confirmOasys.cy.ts
integration_tests/e2e/refer/new/create.cy.ts
integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/e2e/refer/new/show.cy.ts
integration_tests/e2e/refer/new/submit.cy.ts
server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/controllers/refer/new/oasysConfirmationController.test.ts
server/controllers/refer/new/oasysConfirmationController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/paths/auth.ts
server/paths/index.ts
wiremock/stubs/referralSummaries.json
wiremock/stubs/referrals.json

https://trello.com/c/RuS9U9nL/813-ensure-referrers-cant-view-or-edit-draft-referrals-if-theyre-not-the-one-who-created-them-s
Check if logged in `username` is same as `referral.referrerUsername` for a **draft** referral when trying to view or update information related to the referral.

(813) Restrict draft referrals to referrer user only

---

assets/scss/application.scss
assets/scss/components/_audience-tag.scss
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts

Following the upgrade to `govuk-frontend@5`, the [`govuk-tag` class includes a max width][1]. In our prototype, longer tags are on two lines in the case list (for statuses), but audience tags are always on one line regardless of length
- Add an `audience-tag` class to retain the single-line audience tags
[1]: https://github.com/alphagov/govuk-frontend/commit/f8ee9928e4d5410645e48b5575182dc2c1a9012d

(1201b) Allow long audience tags

---

.circleci/config.yml

e2e tests on circleci have started failing due to new version.
Update from 1.39.0 to 1.41.1

Update playwright version to 1.41.1 for e2e tests on circleci

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/@types/ui/index.d.ts
server/testutils/factories/index.ts
server/testutils/factories/referralView.ts

We need to sort results across multiple pages rather than on the client. We will be using a new dashboard endpoint which has a new `ReferralView` schema, which is essentially a flatter version of the existing `ReferralSummary` type.
- Added `ReferralView` type as we will no longer be using `ReferralSummary`
- Add `SortableCaseListColumnKey` type which should match to the names of the columns we want to sort.

(1136a) Add new `ReferralView` type and factory

---

server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

https://trello.com/c/LkEEasTc/1307-tell-api-when-request-for-referral-comes-after-clicking-on-a-case-list-record-s
When a user clicks on a referral from a case list, we want the API to do some background work to update the relevant person information for the case list (to aid sorting)
We therefore need to tell the API when a request for a referral has come through this journey as opposed to just clicking between show referral/risks and needs pages
- Add `?updatePerson=true` to the links to a referral from the case lists
- Pass this query parameter through to `GET` `/referrals/:referralId?updatePerson=true` on the API.
ready to be released once …

(1307) Add `updatePerson` query param to case list referral links

---

server/data/accreditedProgrammesApi/referralClient.test.ts
server/utils/referrals/caseListUtils.test.ts

Currently failing and preventing promoting to prod environments. Will investigate and re-enable after sorting work has been completed.

Temporarily disable pact test for `findReferralViews`

---

integration_tests/pages/page.ts
integration_tests/pages/refer/new/checkAnswers.ts
integration_tests/pages/refer/new/confirmOasys.ts
integration_tests/pages/refer/new/programmeHistoryDetails.ts
integration_tests/pages/refer/new/selectProgramme.ts
package-lock.json
package.json

This was raised by the renovate bot to begin with but was causing the integration tests to fail with the error **"is being covered by another element"**, because it couldn't check radio and checkboxes.
Looking at what is in the 5.1.0 release, it includes [a change](https://github.com/alphagov/govuk-frontend/pull/4093) to radio and checkbox styling, which I believe is what is causing the issue. It looks like the removal of the `z-index` on `.govuk-radios__input` and `.govuk-checkboxes__input` has meant  they now have `z-index: auto` but the styled `label:before` and :`after` have `z-index: 1` which causes them to be higher in the `z-order` than the inputs, which causes the cypress error above.
Updating `selectRadioButton()` and adding `selectCheckbox()` to `check()` with `force: true`, …

Update govuk-frontend to minor version v5.1.0

---

integration_tests/pages/page.ts
server/views/partials/layout.njk

The **My referrals** link wasn't showing for users with `ROLE_ACP_REFERRER` as it was incorrectly using `ROLE_POM`.
Switch to check if the user has `ROLE_ACP_REFERRER`.

Use correct role for showing My referrals link

---

server/controllers/shared/index.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/partials/referralLayout.njk
server/views/referrals/show/partials/risksAndNeedsLayout.njk
server/views/referrals/show/partials/rootLayout.njk
server/views/referrals/show/partials/withNavigationLayout.njk
server/views/referrals/show/statusHistory/show.njk

We need a Status history page to view the timeline of a referral.
This adds the `StatusHistoryController`, associated template, paths and links to the new page.
There is placeholder text where the timeline will be. 

(1335a) Status history page

---

server/@types/models/Referral.ts
server/@types/ui/index.d.ts

The API now returns `statusColour` and `statusDescription` keys so the front end no longer has to match a status with a coloured tag.
- Update `Referral` and `ReferralView` types to include new keys.
- Update `TagColour` type
Work in progress to use these new values.

Update types related to Referral status tag colours

---

server/@types/models/Referral.ts
server/testutils/factories/referral.ts
server/testutils/factories/referralView.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

We no longer need to work out what colour a tag should be depending on the status as the api now returns this for us.
- Update `ReferralStatus` types to include new statuses
- Update Referral related test utils to return `statusColour` and `statusDescription`
- Update `statusTagHtml` method which to take 2 params which will be the colour and description values from the api, rather than work them out on the front end.

Update case list to use `statusColour` and `statusDescription`

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/@types/ui/index.d.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/routes/assess.ts
server/services/index.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/index.ts
server/testutils/factories/referral.ts
server/testutils/factories/referralStatusHistory.ts
server/utils/nunjucksSetup.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/statusHistory/show.njk

We need to display the timeline of a referral and all the statuses it has been in on the status history page.
- New client method for `/referrals/:id/status-history`
- Add MoJ frontend nunjucks filters so we can use the timeline component as it formats the passed in date
- New referral util for turning a status history record into something that can be used in the timeline macro
- Add missing route for status history page for assess
- New ReferralService method for getting status history from client and getting the full name from the username
Integration tests to follow.

(1335b) Status history timeline

---

server/@types/express/index.d.ts
server/controllers/shared/withdrawCategoryController.test.ts
server/controllers/shared/withdrawCategoryController.ts
server/utils/referrals/referralUtils.test.ts
server/utils/referrals/referralUtils.ts

We need to share form selections made on previous pages across multiple steps.
- Add `referralStatusUpdateData` to `req.session`
- Update `WithdrawCategoryController` so:
-  It clears any session data at the start of a new withdrawal, if it's for an unrelated referral or a status other than `WITHDRAWN`
-  If the session data is for the current referral and `WITHDRAWN`, then use the data to pre check the previously selected radio item. So when navigating back, selections will be maintained.
- When submitting, set `referralStatusUpdateData` and clear `statusReasonCode` for the next step, incase an un-matching `categoryCode` has been selected. …

(1337a) Add session object for handling status update journeys

---

server/views/referrals/withdraw/category/show.njk
server/views/referrals/withdraw/partials/layout.njk
server/views/referrals/withdraw/reason-information/show.njk
server/views/referrals/withdraw/reason/show.njk

The 3 withdrawal related pages share a similar layout and content.
- Created a layout for the withdraw pages which contains the back link, page heading, time line and divider.
- Apply the layout to the category, reason and reason information form pages.
This may further be extended/changed/removed in future as we add more status update journeys.

(1337e) Withdraw layout partial

---

cypress.config.ts
integration_tests/e2e/refer/withdraw.cy.ts
integration_tests/mockApis/referenceData.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/new/programmeHistoryDetails.ts
integration_tests/pages/refer/new/selectProgramme.ts
integration_tests/pages/shared/index.ts
integration_tests/pages/shared/withdraw/category.ts
integration_tests/pages/shared/withdraw/reason.ts
integration_tests/pages/shared/withdraw/reasonInformation.ts
server/@types/ui/index.d.ts

Integration tests required for withdraw pages.
- Added mock apis for reference-data endpoints
- Add pages and integration test for withdraw referral journey.

(1336 & 1337) Withdraw referral integration tests

---

integration_tests/e2e/refer/withdraw.cy.ts
server/@types/express/index.d.ts
server/controllers/shared/updateStatusDecisionController.test.ts
server/controllers/shared/updateStatusDecisionController.ts
server/controllers/shared/withdrawCategoryController.test.ts
server/controllers/shared/withdrawCategoryController.ts
server/controllers/shared/withdrawReasonController.test.ts
server/controllers/shared/withdrawReasonController.ts
server/controllers/shared/withdrawReasonInformationController.test.ts
server/controllers/shared/withdrawReasonInformationController.ts

The withdraw journey can be started from both the status history page and the update status journey, so the withdraw category page needs to know where to go Back to.
The reason information page also needs to have a flexible back link as it can be redirected to from both the category and reason steps, depending on your initial category selection.
- Add `previousPath` to session object so we can update the value when submitting forms and then use it where we need it.

Add `previousPath` to Referral update status journey session data

---

server/@types/models/Referral.ts
server/controllers/shared/updateStatusDecisionController.ts
server/testutils/factories/referralStatusRefData.ts
server/utils/referrals/referralUtils.test.ts
server/utils/referrals/referralUtils.ts

We need to display hint text on the radio button items on the select decision page.
- Update `ReferralStatusRefData` type and test factory
- Show hint text on radio buttons if provided.
- Fix variable name typo 

(1364b) Hint text on Select decision radio buttons

---

server/data/accreditedProgrammesApi/referenceDataClient.ts
server/paths/api.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts

We need the reference data for a referral status code.
- Add api path for `reference-data/referral-statuses/:referralStatusCode`
- Add method to `ReferenceDataClient`
- Add method to `ReferenceDataService` 

(1384a) Add client and service methods for getting referral status data

---

server/controllers/assess/index.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/index.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/assess.ts
server/utils/referrals/showReferralUtils.ts

The select decision step of the update status journey is only for users on the assess journey. Subsequent steps will be linked to directly from the refer journey.
- Move `UpdateStatusDecisionController` to be used by assess journey only, not shared with refer.
- Update `assess` related paths for update status and add some more in ready for the next step.

(1384b) Move update status select decision controller to be for assess journey only

---

server/controllers/shared/index.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/paths/refer.ts
server/routes/assess.ts
server/views/referrals/updateStatus/selection/show.njk

When a new referral status decision has been made, then the selection must be confirmed by checking a confirmation checkbox or by entering a reason for the selection.
- Add new controller with show method which calls a reference data endpoint to check if the status update requires just confirmation or `notes` (reason).
- 2 submit methods, one for the confirmation checkbox and one for the reason input, due to different validation.
- New template.
This is very generic at the moment and will continue to be updated as there are some differences in the page content in the designs, depending on the status selected, such as pausing, continuing, closing etc.
Still to do in future PRs.
- Error messaging to be confirmed.
- Back link behavaiour to be addressed separately. 
[Release process …

(1384c) Update status selection

---

server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts

A referrer is more interested in the status of their referral so we need to link direct to the status history page from the My referrals case list.
Assess case lists should contain to link to Referral details.
- Link to status history page from my referrals case list
- Change ordering of navigation items so status history appears first for refer path
Refer view:
Assess view:

(1411) Show referral navigation

---

integration_tests/e2e/find.cy.ts
server/@types/models/CourseOffering.ts
server/testutils/factories/courseOffering.ts
server/views/courses/offerings/show.njk

We need a way for the FIND service to restrict referrals to certain sites.
A `CourseOffering` now has an `organisationEnabled` property. 
- Add extra check for `organisationEnabled` before showing Make a referral button

(1399) Check if course offering is at an enabled site

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/mockApis/referenceData.ts
integration_tests/pages/shared/caseList.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/controllers/assess/index.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/paths/assess.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/referral.ts
server/testutils/factories/referralStatusRefData.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

We need to show all open referrals and the correct filters on a PT case list.
Closed to come at a later date.
- Update case list to fetch referrals with `statusGroup=open` query param.
- Update status filter to include only open statuses

(1456) Show all open referrals on PT case list

---

server/@types/express/index.d.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/categoryController.test.ts
server/controllers/shared/categoryController.ts
server/controllers/shared/index.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/assess.ts
server/views/referrals/updateStatus/category/show.njk
server/views/referrals/updateStatus/reason/show.njk

To deselect a referral, a category code and a reason code is required, similar to the withdraw journey.
- Add `CategoryController`
- Add `Reason Controller`
Both of these new controllers can be used for both `WITHDRAWN` and `DESELECTED` status decisions.  The plan is to remove the withdrawl specific controllers when this has been applied for the referrer user paths.

(1453) Deselect and close referral

---

helm_deploy/values-dev.yaml

Enable WAF and OWASP rules in Dev. Will confirm application still works as expected before progressing to preprod and prod.
[1461](https://trello.com/c/UScQbJAg/1461-add-waf-owasp-rules-to-ui-project)

Add waf owasp rules to ui project

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Enable WAF and OWASP rules in Preprod and prod. 
[1461](https://trello.com/c/UScQbJAg/1461-add-waf-owasp-rules-to-ui-project)

Add waf owasp rules to ui project (pre prod and prod)

---

assets/scss/local.scss
integration_tests/e2e/assess/caseList.cy.ts
integration_tests/e2e/assess/show.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/page.ts
integration_tests/support/sharedTests.ts
server/@types/models/Referral.ts
server/controllers/refer/updateStatusActionsController.test.ts
server/controllers/refer/updateStatusActionsController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/paths/index.ts
server/paths/refer.ts
server/routes/refer.ts
server/testutils/factories/referralStatusRefData.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/partials/rootLayout.njk

When viewing the referral details on the refer paths, a user needs to be able to:
- Put a referral on hold, if the available status transitions allow
- Remove a hold, if the available status transitions allow
- Updates the `ShowReferralUtils.button` method to check if the provided status transitions include a transition with a `hold` or `release` property and then display the correct button with the correct href.
- If neither of those are an option, then button will be disabled.
- Add `UpdateStatusActionsController.manageHold` method which takes the status from the query parameter and redirects to the selection page with the status code added to the session.
- Updated the required controllers to make the call to the `/status-transitions` endpoint, only on refer, not assess.
[Release …

(1338) Refer journey hold statuses button

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/pages/shared/caseList.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/paths/assess.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/utils/stringUtils.test.ts
server/utils/stringUtils.ts

Course names will now be suffixed with the strand, e.g. `Becoming new me plus: sexual offence`. This was causing an issue with the way we linked to the assess case lists for those courses, as we used a formatted version of the name in the url path.
Changed to use the course ID instead of the name and added `/course/` to the URL path so it won't be confused with a referral id.

Use course ID for assess case list navigation

---

server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts

When on the deselected and open journey and there are no reasons for the selected category, we should redirect directly to the decision step so the correct status can be selected. At the moment it goes to the selection page with the `DESELECTED` status, which is incorrect.
Update `ReasonController.show` to redirect to the decision step with `?deselectAndKeepOpen=true` when the `initialStatusDecision` is `'DESELECTED|OPEN'`

Update `ReasonController.show` to redirect correctly

---

integration_tests/e2e/refer/withdraw.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/shared/index.ts
integration_tests/pages/shared/withdraw/selection.ts
server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/controllers/shared/index.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/testutils/factories/confirmationFields.ts
server/testutils/factories/index.ts
server/views/referrals/updateStatus/selection/show.njk

The content of the final step of the status update journeys is different depending on the from and to referral status codes.  We need to use the new `confirmation-text` endpoint for the majority of the content on this page.
- Add new `ConfirmationFields` type and test factory util
- Add new client and service methods for new `confirmation-text` endpoint
- Update the `UpdateStatusSelectionController.show` method to call new endpoint and pass values to the template
- Add warning text component to the bottom of the page, if required

(1466) Confirmation text

---

integration_tests/mockApis/referrals.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts

The `confirmation-text` endpoint needs to know when the status update is by a `ptUser` and if it is for the `deselectAndKeepOpen` journey.
- Update the update status selection controller to pass these query parameters

(1469) Add `ptUser` and `deselectAndKeepOpen` query parameters to confirmation-text call

---

server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/views/referrals/updateStatus/decision/show.njk

The decision step is revisited when on the deselect and keep open journey and we need to display the correct content.
- Call the confirmation-text endpoint on the decision step, only when on the deselect and keep open journey. Otherwise, show default content.

(1469b) Get confirmation text on decision step for deselect and keep open journey

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/pages/shared/caseList.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/views/referrals/caseList/assess/show.njk

We need to show closed referrals on the assess case list.
- Add sub navigation for the `closed` referral status group and ensure that the available statuses in the filters are correct.

(1458) Programme team closed referrals

---

integration_tests/e2e/refer/new/submit.cy.ts
integration_tests/pages/refer/new/complete.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/views/referrals/new/complete.njk

After submitting a referral, a user needs to be able to go back to their referrals.
- Add Go to my referrals button as a link

(1444) Add `Go to my referrals` link to referral complete page

---

server/testutils/factories/risksAndAlerts.ts

`precision` is now deprecated and will be removed in v9. Also removes warning message from test run logs.

Replace use of `precision` with `multipleOf`

---

integration_tests/e2e/app.cy.ts
server/@types/ui/index.d.ts
server/paths/find.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/utils/organisationUtils.test.ts
server/views/courses/_indexCourseSummary.njk

Like `/refer` and `/assess`, we should prefix the find related page paths with `/find`.
Add /find path prefix to find pages

(1037) Add `/find` path prefix to find pages

---

assets/scss/components/_api-error.scss
integration_tests/e2e/refer/withdraw.cy.ts
server/controllers/assess/index.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/categoryController.test.ts
server/controllers/shared/categoryController.ts
server/controllers/shared/index.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/views/referrals/updateStatus/category/show.njk
server/views/referrals/updateStatus/decision/show.njk
server/views/referrals/updateStatus/partials/layout.njk
server/views/referrals/updateStatus/reason/show.njk
server/views/referrals/updateStatus/selection/show.njk

We need to show the blue person banner on the update status journey pages.
- Add new update status layout partial
- Update the 4 status update status related controllers to call the person service and pass those details to the template.

(1504) Show person details on update status journey pages

---

server/utils/appInsightsUtils.test.ts
server/utils/appInsightsUtils.ts

It will be useful to know the full name of the users active case load as well as their roles, so we can create more in depth reports.
- Send `activeCaseLoadDescription` (e.g. Moorland)
- Send `roles` as an array

(1537) Add extra information to app insights

---

server/utils/appInsightsUtils.test.ts
server/utils/appInsightsUtils.ts

We don't need to know all the other users roles
Change `roles` to `acpRoles` in the app insights properties and only send roles starting with `ROLES_ACP_`

(1537b) Only send ACP related roles to app insights

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

enabling WAF for preprod and prod

---

server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/controllers/refer/new/courseParticipationDetailsController.test.ts
server/controllers/refer/new/courseParticipationDetailsController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/views/referrals/new/checkAnswers.njk

When in check your answers, if the user selects one of the change links and makes a change they are redirected to the task list view. This needs to be updated so it directs them back to Check your answers.

(1512) Redirect back to check answers page when using change links

---

integration_tests/e2e/find.cy.ts
integration_tests/pages/find/course.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/views/courses/_locationsTable.njk
server/views/courses/show.njk

The CTAs under the programme locations have some usability and accessibility issues.
- Remove contact prison links and made location name clickable
- Added supporting content above list of offerings

(1520) Improve offering call to actions on course page

---

server/views/referrals/new/additionalInformation/show.njk
server/views/referrals/new/courseParticipations/details/show.njk
server/views/referrals/updateStatus/selection/show.njk

To ensure consistency, some font styles need to be updated across the service.
Added `govuk-fieldset__legend--s` to some legends and labels. 

(1484a) Update label and legend styling on some form components

---

server/controllers/refer/updateStatusActionsController.test.ts
server/controllers/refer/updateStatusActionsController.ts
server/controllers/shared/categoryController.test.ts
server/controllers/shared/categoryController.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts

Text incorrectly says that the referral will be closed, after selecting Deselect and keep open.
Use the `initialStatusDecision` value for the content on the category and reason pages, which in this case will be `DESELECTED|OPEN`

(1540) Update content on category and reason pages for deselect and keep open

---

integration_tests/pages/shared/showReferral/risksAndNeeds/lifestyleAndAssociates.ts
integration_tests/pages/shared/showReferral/risksAndNeeds/relationships.ts
integration_tests/support/sharedTests.ts
server/@types/models/Lifestyle.ts
server/@types/models/Relationships.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/views/referrals/show/risksAndNeeds/lifestyleAndAssociates.njk
server/views/referrals/show/risksAndNeeds/relationships.njk

Based on the last round of research, the free text information captured in OASys Layer 3 sections 6 (Relationships) and 7 (Lifestyle and Associates) needs to be added to the Risks & Needs section of a referral (for both Referrer and PT journeys)
Add required information to Relationships and Lifestyle pages within the Risks and needs section and handle when there is no information available.

(1519b) Add extra information to Relationships and Lifestyle sections

---

integration_tests/pages/shared/caseList.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

(1518) Remove 'referrals' text suffix from course name in case list navigation

---

assets/scss/local.scss
server/views/referrals/caseList/assess/show.njk
server/views/referrals/caseList/refer/show.njk

When reducing the width of the browser, the case list tables break the layout of the page.
Wrap the tables in a div which allows horizontal scroll.

(1169) Allow tables to scroll horizontally if required when screen size is reduced

---

integration_tests/pages/refer/new/programmeHistoryDetails.ts
server/views/referrals/new/courseParticipations/details/show.njk

1. Added hint text to Provide additional detail (if known) text area
2. Added "(optional)" to Provide the source label

(1445) Update label and hint text on course participation form

---

server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts

We need to display different reasons between the deselect close and deselect open status update journeys.
Call status reasons endpoint with `deselectAndKeepOpen` query parameter set to `'true'` when on the Deselect and keep open journey.
[APG-90](https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?selectedIssue=APG-89)
[APG-90]: https://dsdmoj.atlassian.net/browse/APG-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APG-90 Call status reasons endpoint with `deselectAndKeepOpen` query parameter

---

integration_tests/e2e/refer/new/additionalInformation.cy.ts
integration_tests/pages/refer/new/additionalInformation.ts
server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/views/referrals/new/additionalInformation/show.njk

The ‘Add Additional Information’ screen needs a character limit on the free text box. What should the character limit be? (suggest 4000) and error text if you go over 4000.
Replace govuk text area with govuk character count and apply limit of 4000 characters.
Unit and integration tests updated and added to.

(APG-71) Add character count to additional information page

---

server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/categoryController.test.ts
server/controllers/shared/categoryController.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/data/accreditedProgrammesApi/personClient.ts
server/services/personService.test.ts
server/services/personService.ts

If a referral was made to a programme in a users caseload, but the person being referred was in another caseload which the user did not have, then the referral would 404.
On referral view related pages, we should now search for a person in prison by their ID but not specify any caseloads so it doesn't restrict the search.

(BUG) Allow referrals to be viewed when person in prison is not in users caseloads

---

integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/pages/refer/new/programmeHistory.ts
server/views/referrals/new/courseParticipations/index.njk

Updated the CTA and body text on the Accredited Programme History page

1443 - CTA Accredited Programmes History

---

server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/controllers/refer/new/courseParticipationDetailsController.test.ts
server/controllers/refer/new/courseParticipationDetailsController.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/refer/new/oasysConfirmationController.test.ts
server/controllers/refer/new/oasysConfirmationController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts

If a user has raised a referral and then no longer has that caseload associated with their account, they would no longer be able to view that particular referral.
Call `PersonService.getPerson` with no caseloads specified so the prisoner details can be retrieved from the prisoner-search endpoint, so the referral can still be viewed.

(APG-111) Allow referrals to still be viewable if user no longer has caseload of PiP

---

package-lock.json

Update patch version of `follow-redirects` package

---

integration_tests/pages/shared/showReferral/sentenceInformation.ts
server/@types/models/Person.ts
server/@types/models/index.d.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/testutils/factories/index.ts
server/testutils/factories/keyDates.ts
server/testutils/factories/sentenceDetails.ts
server/utils/personUtils.test.ts
server/utils/personUtils.ts
server/views/referrals/show/sentenceInformation.njk

We need to display the release related dates returned from the AcP API, rather than Prison API on the Sentence Information page.
Use `keyDates` from `/people/{prisonNumber}/sentences` in AcP API, sorted by earliest first and maintaining earliest release date sub label.

(APG-109) Use Key dates for Release dates section

---

integration_tests/pages/page.ts
server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/controllers/refer/new/deleteReferralController.test.ts
server/controllers/refer/new/deleteReferralController.ts
server/controllers/refer/new/index.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/paths/refer.ts
server/routes/refer.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/views/referrals/caseList/refer/show.njk
server/views/referrals/new/_organisationAndCourse.njk
server/views/referrals/new/delete/show.njk
server/views/referrals/new/people/show.njk
server/views/referrals/new/show.njk

There is no way for users to remove draft referrals from their ‘draft referrals’ case list view. They would have to submit and then withdraw the referral to remove it.
Drafts are saved when users click continue on the person’s details confirmation page. At the moment, we don’t tell users that drafts are saved, so they may not even realise that a draft has been created.
- Add message to indicate that a draft referral will be saved
- Add Delete button to task list page which redirects to the new Delete page
- New Delete page where clicking delete is final and redirects to referrers drafts
- Add success message on referrers case list page
ready to …

(APG-88) Delete draft referrals

---

server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts

On the update status journey the character limit for reason input has been restricted to 100 characters.
User research has highlighted that 100 characters is not enough.
We’d like to increase the character limit to 500 as this should allow for approximately 2 paragraphs of text to be added.
Increase max length to 500 from 100.

(APG-149) Increase character count to 500 on update status selection page

---

integration.env
integration_tests/e2e/app.cy.ts
server/views/dashboard/index.njk

The live service is missing a link back to DPS on the AcP homepage, as per screen shot off prototype:
Add back link to Digital Prison Services to service homepage.

(APG-56) Add link to DPS on homepage and update related integration tests

---

assets/scss/application.scss
assets/scss/local.scss
assets/scss/overrides.scss

Some of the statuses (eg Assessed as suitable) appear to be wrapping when the column width is much wider for the status details. See screen shot below:
Remove `max-width` on tags within an moj timeline and added to a new overrides.scss file.  Any future moj or govuk overrides should go in here. Will help us keep an eye on if things start getting out of hand.

(APG-59) Remove `max-width` on tags within an moj timeline

---

integration_tests/e2e/assess/show.cy.ts
integration_tests/pages/shared/index.ts
integration_tests/pages/shared/showReferral/releaseDates.ts
integration_tests/pages/shared/showReferral/sentenceInformation.ts
integration_tests/support/sharedTests.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/assess.ts
server/routes/refer.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/releaseDates.njk

Based on user feedback since launch and conversations with the ‘calculate a release date’ team, we may not be providing the Earliest Possible Release Date for a person as clearly or as definitively as we could be.
- Moved Release dates summary list from Sentence information page to a new specific Release dates page within Referral details.
- Also replaced Imported from OASys text with Imported from NOMIS on both Sentence Information and the new Release dates page.

(APG-140) Move Release dates to new specific sub page under Referral details

---

server/utils/dateUtils.test.ts
server/utils/dateUtils.ts
server/utils/personUtils.test.ts
server/utils/personUtils.ts
server/utils/stringUtils.test.ts
server/utils/stringUtils.ts

We’ve identified that it might be helpful to users if we worked out the age of the person being referred. Currently we only display the DOB.
Add `calculateAge` to `DateUtils`
Add `pluralise` to `StringUtils`
Use `DateUtils.calculateAge` in `PersonUtils.summaryListRows` for Date of birth entry.

(APG-147) Calculate and display a persons age

---

integration_tests/pages/page.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/utils/referrals/showRisksAndNeedsUtils.test.ts
server/utils/referrals/showRisksAndNeedsUtils.ts
server/views/referrals/show/partials/withNavigationLayout.njk

Added a `#content` id to be used by the sub level navigation, so it doesn't scroll back to the top of the page each time.
The sub navigations when viewing a referral takes the user to the top of the page each time and forces the user to scroll back down to where the content actually is, which isn't a great experience.
- Wrap content in div with `id="content"`
- Update navigation utils hrefs to include `#content`

(APG-166) Update sub level navigation when viewing a referral

---

integration_tests/pages/refer/new/additionalInformation.ts
server/views/referrals/new/additionalInformation/show.njk

On the Additional information screen, the bullet style needs updating - text shouldn't be capitalised. Make first word of each bullet lower case.
Lowercased first character of each bullet on Additional information screen.

(APG-47) Update bullet content on additional information page

---

integration_tests/e2e/refer/withdraw.cy.ts
server/views/referrals/updateStatus/category/show.njk
server/views/referrals/updateStatus/decision/show.njk
server/views/referrals/updateStatus/reason/show.njk
server/views/referrals/updateStatus/selection/show.njk

The cancel link is missing on several of the update status screens.
Added the cancel link to all update status related pages.

(APG-36) Add Cancel button to status update pages

---

integration_tests/pages/page.ts
server/@types/express/index.d.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts

Currently, when viewing a referral, the Back to referrals button link takes the user back to the course index which is always the first course.  This could be confusing and a tedious experience because it is possible that the user may have been viewing another course, with filters selected, on another page number other than 1.
Store recently viewed case list path in session and update Back to referrals button to use that value.

(APG-165) Add `recentCaseListPath` to session to be used when navigating between case lists and referrals

---

integration_tests/e2e/refer/withdraw.cy.ts
server/@types/models/Referral.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/shared/index.ts
server/controllers/shared/updateStatusSelectionController.test.ts
server/controllers/shared/updateStatusSelectionController.ts
server/routes/assess.ts
server/routes/refer.ts
server/testutils/factories/confirmationFields.ts
server/testutils/factories/referralStatusRefData.ts
server/views/referrals/updateStatus/selection/show.njk

Some status codes will state that the notes can be optional.
When updating the status of a referral none of the ‘happy path’ journeys allow the user to add additional information. Feedback from user research suggests this creates a user needs gap. We need to add a notes box for all journeys where the status is updated.
Removed confirmation checkbox related code and make all status update journeys have a reason textarea.  On some occasions this can be optional.

(APG-164) Update final page of update status journeys to use notes/reason box

---

.circleci/config.yml

`npm_outdated` circle job no longer required.  Important updates covered by `npm_security_audit`. It has also been [removed from the typescript template](https://github.com/ministryofjustice/hmpps-template-typescript/pull/388) and multiple other services.
Remove `npm_outdated` job from circle config.

Remove `npm_outdated` job from circle config

---

integration_tests/e2e/assess/caseList.cy.ts
server/@types/models/Referral.ts
server/@types/ui/index.d.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/testutils/factories/referralView.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

There’s a need for PTs to see whether prisoners are at their site or external, as some early referral stages, like the assessment, can only be done once they have been transferred. Being able to sort by this in the case list view helps them to see which referrals they can progress now, and which require a transfer.
Display `location` from the dashboard `ReferralView` in a new Location column.

(APG-255) Add Location column to PT case list

---

integration_tests/e2e/refer/new/confirmOasys.cy.ts
integration_tests/mockApis/oasys.ts
integration_tests/pages/refer/new/confirmOasys.ts
server/@types/models/AssessmentDateInfo.ts
server/@types/models/index.d.ts
server/controllers/refer/new/index.ts
server/controllers/refer/new/oasysConfirmationController.test.ts
server/controllers/refer/new/oasysConfirmationController.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/paths/api.ts
server/services/oasysService.test.ts
server/services/oasysService.ts
server/testutils/factories/assessmentDateInfo.ts
server/testutils/factories/index.ts
server/views/referrals/new/oasysConfirmation/show.njk

The designs have been updated to give users more information about the OASys record and what will pull through, before they submit the referral.
- Call OASys `/assessment_date` endpoint
- Display assessment date information on OASys confirmation screen, if available.
With assessment date and incomplete assessment:
With assessment date only:
With no assessment information:

(APG-241) OASys assessment date on confirmation screen

---

integration_tests/pages/page.ts
integration_tests/support/sharedTests.ts
server/@types/ui/index.d.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/views/referrals/show/partials/risksAndNeedsLayout.njk

In the Risk and Needs section of the referral, where we show OASys data we should also say when OASys was last updated.
Get the `recentCompletedAssessmentDate` from `/assessment_date` and display at the top of of the Risks and needs pages.

(APG-51) Add last assessment date to top of Risks and needs pages

---

server/@types/models/Course.ts
server/@types/models/CourseAudience.ts
server/@types/models/CourseCreateRequest.ts
server/@types/models/index.d.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/testutils/factories/audience.ts
server/testutils/factories/courseAudience.ts
server/testutils/factories/index.ts

We need an easier way to update the content in FIND to ensure it is accurate.
- Add some new types to support adding a new Course/Programme
- Add `createCourse` and `findCourseAudiences` methods to `CourseClient`

(APG-250a) Add Course/Programme client methods

---

server/services/courseService.test.ts
server/services/courseService.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts

Follows #688 
- Add `createCourse` and `getCourseAudiences` methods to `CourseService`
- Add `audienceSelectItems` to `CourseUtils`

(APG-250b) CourseService and CourseUtils methods needed for adding a course

---

integration_tests/e2e/find.cy.ts
integration_tests/pages/find/courses.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/views/courses/form/show.njk
server/views/courses/index.njk

Add button link to Add a new programme form page, for users with `ROLE_ACP_EDITOR` role.

(APG-250) Add 'Add a new programme' button link to find index

---

integration_tests/e2e/find.cy.ts
integration_tests/e2eReferDisabled/find.cy.ts
server/@types/models/CourseOffering.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/data/prisonRegisterApiClient.test.ts
server/data/prisonRegisterApiClient.ts
server/paths/api.ts
server/paths/prisonRegisterApi.ts
server/services/organisationService.test.ts
server/services/organisationService.ts
server/testutils/factories/courseOffering.ts
server/utils/organisationUtils.test.ts

We need an easier way to update the content in FIND to ensure it is accurate.
- Add prison register client methods for getting all available prisons.  This is so we can show a list of available prisons/locations to select from on the form.
- Add `addCourseOffering` method to CourseClient and update `CourseOffering` type.  Will add associated PACT test to API.

(APG-253) Add client methods to help with adding a course offering

---

server/data/accreditedProgrammesApi/courseClient.test.ts

Specify `organisationId` for `addCourseOffering` PACT test

---

integration_tests/e2e/find.cy.ts
integration_tests/pages/find/course.ts
server/controllers/find/addCourseOfferingController.test.ts
server/controllers/find/addCourseOfferingController.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/controllers/find/index.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/find.ts
server/routes/editor.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/views/courses/offerings/form/show.njk
server/views/courses/show.njk

We need to be able to add offerings/locations for a course/programme.
Add new `AddCourseOfferingController` for displaying and submitting new form.

(APG-253) Add Course offering form page

---

server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/data/restClient.ts
server/paths/api.ts

We need to be able to update the prerequisites for a course.
Add new client method for `/courses/:id/prerequisites`

(APG-251) Add `updateCoursePrerequisites` method to `CourseClient`

---

integration_tests/mockApis/oasys.ts
integration_tests/pages/shared/showReferral/risksAndNeeds/lifestyleAndAssociates.ts
integration_tests/support/sharedTests.ts
server/@types/models/Lifestyle.ts
server/@types/models/index.d.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/services/oasysService.ts
server/testutils/factories/lifestyle.ts
server/utils/risksAndNeeds/lifestyleAndAssociatesUtils.test.ts
server/utils/risksAndNeeds/lifestyleAndAssociatesUtils.ts
server/views/referrals/show/risksAndNeeds/lifestyleAndAssociates.njk

We need to add the extra OASys fields used to calculate the PNI to the front-end.
- Added a new summary list for Section 7.3 - Criminal associates
- Used `Lifestyle` type from the imported file as we look to move away from using `@accredited-programmes/models` 

(APG-315) Update RIsks and Needs Section 7 - Lifestyle

---

integration_tests/mockApis/oasys.ts
integration_tests/pages/shared/showReferral/risksAndNeeds/emotionalWellbeing.ts
server/@types/models/Psychiatric.ts
server/@types/models/index.d.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/services/oasysService.ts
server/testutils/factories/psychiatric.ts
server/utils/risksAndNeeds/emotionalWellbeingUtils.test.ts
server/utils/risksAndNeeds/emotionalWellbeingUtils.ts

We need to add the extra OASys fields used to calculate the PNI to the front-end.
Add 10.1 - Difficulties coping to Risks and needs section

(APG-316) Update Risks and Needs Section 10 - Emotional wellbeing

---

assets/js/fieldRepeater.js
server/controllers/find/addCourseController.test.ts
server/controllers/find/addCourseController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/views/courses/form/show.njk

We need an easier way to update the content in FIND to ensure it is accurate.
- Added some client side JS for `fieldRepeater` so more fields can be added to allow for multiple values of a similar name.
- Used the above and added some fields to add course prerequisites when adding a new course

(APG-251) Add course prerequisites

---

integration_tests/pages/find/courseOffering.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/paths/find.ts
server/routes/find.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/views/courses/offerings/show.njk

We need an easier way to update the content in FIND to ensure it is accurate
Added Delete button to course offering page.
Note: The API only allows offerings to be deleted if there are no associated referrals. 

(APG-254) Add the ability the delete a course offering

---

server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/controllers/find/index.ts
server/controllers/find/updateCourseOfferingController.test.ts
server/controllers/find/updateCourseOfferingController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/paths/find.ts
server/routes/find.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/views/courses/offerings/form/show.njk
server/views/courses/offerings/show.njk

We need an easier way to update the content in FIND to ensure it is accurate
- Add `UpdateCourseOfferingController` 
- Update course offering form to pre-fill inputs with passed in values
Update button link
Offering form with values pre-filled

(APG-252) Update offering

---

integration_tests/e2e/find.cy.ts
integration_tests/pages/find/course.ts
integration_tests/pages/find/courseOffering.ts
server/routes/editor.ts
server/routes/find.ts
server/views/courses/offerings/show.njk
server/views/courses/show.njk

We need an easier way to update the content in FIND to ensure it is accurate
Hidden new buttons and routes for editing content behind `ROLE_ACP_EDITOR` role.

(APG-245) Only allow content update related content and routes to be visible with role

---

.gitignore

Ignore .DS_Store files, generated by macOS.

Add `**/.DS_Store` to .gitignore

---

package-lock.json
package.json

Renovate bot is updating package `@golevelup/ts-jest` which is causing some test failures, so preventing other packages being updated.
Fixing to `0.5.0` for now to prevent renovate from updating as future versions are causing test failures and need to spend more time investigating.
I think it's down to our use of `createMock` and values that should not be functions getting set as `jest.fn()`s.

Fix `@golevelup/ts-jest` version to `0.5.0`

---

package-lock.json
package.json
renovate.json

Renovate bot is updating package @golevelup/ts-jest which is causing some test failures, so preventing other packages being updated.
Instead of fixing in the package.json, only allow renovate to use 0.5.0.

Fix @golevelup/ts-jest version to 0.5.0 in renovate.json

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
server/config.ts

We only want to show the upcoming PNI page to selected organisations.
Created new `PNI_ENABLED_ORGANISATIONS` env var and added the following organisations to dev and pre prod:
- Drake Hall
- Whatton
Prod will be done in a future PR after the feature is completed.

(APG-364) Add `PNI_ENABLED_ORGANISATIONS` env value

---

server/services/pniService.test.ts
server/services/pniService.ts

Business exceptions throw a 400 so we want to return null when this happens so the Information missing message can be displayed.
Return null in getPni service method when there is a 400 error.

(APG-375) Update `PniService.getPni` to return null when there is a 400

---

server/controllers/assess/pniController.test.ts
server/controllers/assess/pniController.ts
server/data/accreditedProgrammesApi/pniClient.ts
server/services/pniService.test.ts
server/services/pniService.ts

The PNI endpoint will be quicker if we provide `gender`
Pass the persons gender to the pni call.

(APG-375c) Provide gender query param when getting pni information

---

server/utils/referrals/newReferralUtils.test.ts
server/utils/referrals/newReferralUtils.ts

We updated the OASys confirmation screen content recently, but the header on the task list hasn’t been updated to match.
Change link text content.

(APG-369) Update link text for checking OASys information

---

server/controllers/assess/pniController.test.ts
server/controllers/assess/pniController.ts
server/data/accreditedProgrammesApi/pniClient.ts
server/services/pniService.test.ts
server/services/pniService.ts

We need to make sure we get and use the latest PNI result when displaying it.
Set `savePNI` to `true` when calling the api.

(APG-375) Set `savePNI` query parameter to true when getting PNI

---

server/@types/accreditedProgrammesApi/index.d.ts
server/controllers/assess/pniController.test.ts
server/controllers/assess/pniController.ts
server/utils/risksAndNeeds/pniUtils.test.ts
server/views/referrals/show/pni/show.njk

API has recently been updated to return `MISSING_INFORMATION` for `programmePathway`
- Update ACP API types
- Update controller and template to hide calculated content when `programmePathway` is `MISSING_INFORMATION`.

(APG-375) Hide calculated section on PNI page for MISSING_INFORMATION

---

helm_deploy/values-prod.yaml

PNI has been released, it just needs enabling when we're ready.
Add `DHI` and `WTI` to `PNI_ENABLED_ORGANISATIONS`

(APG-429) Enable PNI page for Drake Hall and Whatton

---

integration_tests/e2e/refer/new/create.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/refer/index.ts
integration_tests/pages/refer/new/duplicate.ts
server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/@types/ui/index.d.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/refer.ts
server/routes/refer.ts
server/sanitisedError.test.ts
server/sanitisedError.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/views/referrals/show/duplicate.njk

In the current service its possible for a duplicate referral to be made for the same person, to the same offering at the same location.
For example, Del Hatton could be referred twice to Kaizen at Stocken.
We think it would be sensible to stop this from happening for open referrals only.
- Add `isErrorWithData` type guard so we can confidently return the data to the front end if it is received as part of a http error.
- Add new controller method and page tempate to display duplicate referral information
- Update create referral controller method to check if 409 with referral data and redirect to the new page
- Add related integration tests …

(APG-365) Prevent duplicate referrals

---

server/data/accreditedProgrammesApi/statisticsClient.ts
server/data/index.ts
server/paths/api.ts
server/services/index.ts
server/services/statisticsService.test.ts
server/services/statisticsService.ts
server/testutils/factories/index.ts
server/testutils/factories/reportContent.ts

To support the ability for service stakeholders to be able to self-serve when it comes to AcP data reporting, we need to build the dashboard for Accredited Programmes.
Add client and service to call the statistics endpoints.

(APG-363a) Client and Service for reporting dashboard

---

server/controllers/index.ts
server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/paths/index.ts
server/paths/reports.ts
server/routes/index.ts
server/routes/reports.ts
server/utils/dateUtils.test.ts
server/utils/dateUtils.ts
server/utils/index.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts
server/views/reports/_reportDataBlock.njk
server/views/reports/show.njk

To support the ability for service stakeholders to be able to self-serve when it comes to AcP data reporting, we need to build the dashboard for Accredited Programmes.
Add new controller and page to fetch and display statistics for the previous full month.

(APG-363b) Report dashboard

---

server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/paths/reports.ts
server/routes/reports.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts
server/views/reports/_reportDataBlock.njk
server/views/reports/show.njk

Building on the data reporting dashboard, users will need the ability to filter the data reports by geography and by date.
Add filters which allow the user to filter on the following time periods:
- last full month
- last full quarter
- last full 6 months

(APG-385a) Statistics report filters

---

assets/scss/overrides.scss
server/controllers/index.ts
server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/data/accreditedProgrammesApi/statisticsClient.ts
server/services/statisticsService.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts
server/views/reports/show.njk

Building on the data reporting dashboard, users will need the ability to filter the data reports by geography and by date.
Add filters which allow the user to filter nationally or by each prison location.

(APG-385b) Location filters on report page

---

server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/utils/dateUtils.test.ts
server/utils/dateUtils.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts
server/views/reports/show.njk

Building on the data reporting dashboard, users will need the ability to filter the data reports by custom dates.
Add filters which allow the user to filter by custom dates.

(APG-385c) Custom dates filters

---

server/controllers/index.ts
server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/paths/api.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts

Building on the data reporting dashboard, users will need the ability to filter the data reports by prisons where ACP is enabled.
- Show on programme count
- Only show enabled organisations in filters ist

(APG-385d) Report page updates

---

server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/utils/statisticsReportUtils.test.ts
server/utils/statisticsReportUtils.ts

Content updates
Add "national" before data when no prison is selected.
Change "Total referrals deselected" to "Total participants deselected"

(APG-385e) Update content on the report page

---

integration_tests/e2e/app.cy.ts
server/controllers/dashboardController.test.ts
server/controllers/dashboardController.ts
server/views/dashboard/index.njk

New report page needs to be easily accessible to all users.
Add link on the service homepage to the new reports page at /reports.

(APG-408) Add link from homepage to report data

---

assets/scss/local.scss
integration_tests/e2e/assess/caseList.cy.ts
integration_tests/pages/shared/caseList.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/formUtils.test.ts
server/utils/formUtils.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/views/referrals/caseList/assess/selectWithOptGroup.njk
server/views/referrals/caseList/assess/show.njk

We need the ability to search case lists.
- Add search functionality to assess case list
- Show number of results for both open and closed referrals
- Show all referral statuses, in option groups

(APG-376a) Add name or prison number search to assess case list

---

integration_tests/e2e/refer/caseList.cy.ts
integration_tests/pages/refer/new/delete.ts
integration_tests/pages/shared/caseList.ts
server/controllers/refer/caseListController.test.ts
server/controllers/refer/caseListController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/refer.ts
server/routes/refer.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts
server/views/referrals/caseList/refer/show.njk

Allow users to search their referrals with name or prison number.
- Add search box to my referrals case list page
- Show total count for each referral group in sub navigation

(APG-376b) Add search box to refer case list

---

.circleci/config.yml

Required after updating playwright in e2e test repo to 1.48.0.

Update playwright docker to 1.48.0

---

integration_tests/pages/refer/new/findPerson.ts
server/views/referrals/new/new.njk

Content needs updating on the page where you enter a prison number. We’d identified this when we tested the end-to-end journey pre-launch.
Label text update

(APG-459) Update label text when searching for a prison number

---

integration_tests/e2e/refer/withdraw.cy.ts
integration_tests/mockApis/referenceData.ts
integration_tests/pages/shared/withdraw/reason.ts
server/@types/accreditedProgrammesApi/index.d.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/refer/updateStatusActionsController.test.ts
server/controllers/refer/updateStatusActionsController.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/paths/api.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts
server/testutils/factories/pniScore.ts
server/utils/referrals/referralUtils.test.ts
server/utils/referrals/referralUtils.ts
server/utils/risksAndNeeds/pniUtils.test.ts
server/views/referrals/updateStatus/reason/show.njk

Combine category and reason steps into one page for Withdraw and Deselection journeys.

(APG-388) Combine reasons with categories onto one page for deselect and withdraw

---

server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

Based on user feedback, we should change the way we display peoples name in the case list views so it is surname first.  This will also match how it is displayed in DPS too. 
Update `formattedPrisonerName` util to display names as **Surname, Forename** in case lists.

(APG-486) Change names in case lists to be surname, forename

---

integration_tests/e2e/refer/new/submit.cy.ts
integration_tests/mockApis/referrals.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts

We need to handle duplicate referrals when submitting a draft referral.
Handle 409 conflict in submit referral method.

(APG-441) Handle duplicate referrals when submitting from draft

---

server/utils/risksAndNeeds/pniUtils.test.ts
server/utils/risksAndNeeds/pniUtils.ts
server/views/referrals/show/pni/show.njk

Currently, if there is missing information then we don't show even the scores that we do have.  If only some fields are missing from the PNI, we want to show the scores we do have and give users more information about what fields are missing.
- Show available scores if there is missing information
- Update content

(APG-478) Update PNI page to handle information missing scenarios

---

server/@types/ui/index.d.ts
server/controllers/find/buildingChoicesController.test.ts
server/controllers/find/buildingChoicesController.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/controllers/find/index.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/paths/find.ts
server/routes/find.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/testutils/factories/course.ts
server/testutils/factories/coursePrerequisite.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/views/courses/_indexCourseSummary.njk
server/views/courses/offerings/buildingChoices/show.njk
server/views/courses/show.njk

When someone selects Building Choices they are prompted to answer 2 more questions. As per designs.
- Add new BuildingChoicesController to display and submit the form
- Link to Building choices form from find page for Building choice courses

(APG-509b) Building choices form

---

package-lock.json
package.json

Failing npm audit
Overridden cookie package used by other packages. csurf package is now deprecated but an alternative solution has yet to be decided. Solution taken from hmpps-typescript-template.

Override cookie package

---

integration_tests/pages/refer/new/programmeHistoryDetails.ts
integration_tests/pages/refer/new/selectProgramme.ts
server/views/referrals/new/courseParticipations/course.njk
server/views/referrals/new/courseParticipations/details/show.njk
server/views/reports/show.njk

We have been recommended to add supporting text for screen readers to conditionally revealed radio button elements.
Add supporting text within a `govuk-visualy-hidden` `span` to all uses of conditional radio items.

(APG-497) Add supporting text for conditional field labels for screen readers

---

server/testutils/factories/coursePrerequisite.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts

Additional text needs to be displayed above and below risk criteria for Building choices programmes.
Updated Course presenter util to handle pre and post risk criteria keys.

Add pre and post risk criteria strings to pre requisites list

---

assets/scss/components/_pathway-content.scss
server/services/pniService.test.ts
server/services/pniService.ts
server/utils/risksAndNeeds/pniUtils.test.ts
server/utils/risksAndNeeds/pniUtils.ts

Reverts ministryofjustice/hmpps-accredited-programmes-ui#804
API change required to return MISSING_INFORMATION programmePathway for other scenarios.

Revert "(APG-554) Show error specific content when the pathway is not known"

---

package-lock.json
package.json
server/middleware/setUpCsrf.ts

The csurf package we use has now been deprecated - [npm: csurf](https://www.npmjs.com/package/csurf)  and will no longer receive package dependancy updates.
Replace csurf with csrf-sync. As per https://github.com/ministryofjustice/hmpps-template-typescript/pull/481

(APG-586) Replace csurf with csrf-sync

---

assets/scss/components/_pathway-content.scss
server/controllers/assess/pniController.test.ts
server/controllers/assess/pniController.ts
server/services/pniService.test.ts
server/services/pniService.ts
server/utils/risksAndNeeds/pniUtils.test.ts
server/utils/risksAndNeeds/pniUtils.ts

In the event of an API error, other than a 404, we need to display something more meaningful to the user, so they know to try again later.
Update PNI utils, service and controller to show error content when there has been an API error, but still show Missing Information if there is a 404 error.
Missing information in OASys or no assessment found (404 from api):
Any other API error:

(APG-554) Show error specific content when there has been an PNI API error

---

integration_tests/e2e/refer/new/create.cy.ts
server/views/referrals/new/people/show.njk

On the Confirm Personal Details page, the text “This will save a draft referral” is placed after the “Continue” button. While sighted users may see this text before proceeding, users relying on screen readers may miss this crucial information, as it appears after the button, breaking the logical sequence of content. This affects screen reader users who require important information to be conveyed before they perform an action.
Moved "This will save a draft referral." text to be above the Continue button.

(APG-494) Move draft referral text above Continue button

---

server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/views/partials/keylessSummaryCard.njk
server/views/referrals/new/checkAnswers.njk
server/views/referrals/show/statusHistory/show.njk

An accessibility review suggested revising some heading structures to ensure that sub-headings are nested correctly beneath their respective section headings.
- Change summary card headings on check your answers page, from h2 to h3
- Change status history timeline item headings, from h2 to h3

Change some h2s to h3s

---

server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/data/accreditedProgrammesApi/courseClient.test.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts

Course participations/Programme history records added as part of creating a new referral, need to remain in a draft state until the referral is eventually submitted.
Call `POST /course-participations` with extra values:
- `isDraft: true`
- `referralId`

(APG-314b) Add course participations as draft and for a specific referral

---

integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/pages/refer/index.ts
integration_tests/pages/refer/new/showProgrammeHistory.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/paths/refer.ts
server/routes/refer.ts
server/views/referrals/new/courseParticipations/show.njk

Each programme history page needs it's own individual route to link to from the upcoming table view.
Add new route and template for individual programme history records.

(APG-314c) Add individual programme history page

---

server/data/accreditedProgrammesApi/courseClient.test.ts

Use `0c46ed09-170b-4c0f-aee8-a24eeaeeddab` for `createCourseParticipation` in PactContractTest.kt

Add referralId for participation related pact tests

---

server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/services/courseService.test.ts
server/services/courseService.ts

We need to get the course participations added by referral id so we can show them when creating a draft referral.
Add Course client and service methods to call `/course-participations/referral/{id}`

(APG-314d) Add client and service methods to call `course-participations/referral/{id}`

---

integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/mockApis/courseParticipations.ts
integration_tests/pages/page.ts
integration_tests/pages/refer/new/deleteProgrammeHistory.ts
integration_tests/pages/refer/new/programmeHistory.ts
integration_tests/pages/refer/new/programmeHistoryDetails.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/views/referrals/new/courseParticipations/index.njk

Currently, any user can edit any programme history record for a person when creating a new referral.  A user should only be able to change or remove the history record they have added as part of that referral.  
- Implement new design for the Accredited programme history page when raising a referral.
- Show history records added as part of current draft referral in a separate table with Change and Remove action links.

(APG-314e) Update Accredited Programme history page for refer

---

integration_tests/e2e/refer/new/programmeHistory.cy.ts
integration_tests/pages/page.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/shared/index.ts
server/controllers/shared/programmeHistoryDetailController.test.ts
server/controllers/shared/programmeHistoryDetailController.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/assess.ts
server/routes/refer.ts
server/utils/courseParticipationUtils.test.ts
server/utils/courseParticipationUtils.ts
server/views/referrals/show/programmeHistoryDetail.njk

Each programme history page needs it's own individual route to link to from the upcoming table view. Originally done in #835 but then realised it needed to be linked to from other pages and be slightly more flexible in use.
Created a new `ProgrammeHistoryDetailController` with `show` method that is used by multiple routes.

(APG-469a) Individual page for programme history

---

integration_tests/support/sharedTests.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/programmeHistory.njk

- Remove unused controller method which was replaced in commit #841 
- Use `CourseParticipationUtils.table` on referral Programme history page.

(APG-469b) Programme history table view within a referral

---

server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/utils/organisationUtils.test.ts
server/utils/organisationUtils.ts
server/views/reports/show.njk

Adds an empty placeholder to the prison search filter in reports to prevent auto selecting the first entry

Add empty placeholder for prison filter

---

integration_tests/pages/find/recommendedPathway.ts
server/@types/ui/index.d.ts
server/controllers/find/recommendedPathwayController.test.ts
server/controllers/find/recommendedPathwayController.ts
server/views/find/recommendedPathway.njk

This will be used by the subsequent step in the journey to show the appropiate content.
- Add `programmePathway` to `session.pniFindAndReferData`
- Update integration test to use existing `shouldContainText` method.

(APG-623) Add `programmePathway` to `session.pniFindAndReferData`

---

server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts

When raising a referral using the new PNI find journey then we need to carry the previously entered prison number through so the user doesn't get asked to enter it again.
- Update `NewReferralsController.new` method  to redirect to person show details page if there is a `prisonNumber` in `req.session.pniFindAndReferData`
- Reset the `req.session.pniFindAndReferData` object when viewing the current find directory so the user still has the option to search using the existing journey.

(APG-686) Use `pniFindAndReferData.prisonNumber` if available when raising a referral

---

.github/PULL_REQUEST_TEMPLATE.md

While reviewing various new PRs to orient myself, I noticed that the link to the "Release process documentation" in the `Release Checklist` section of the PR was resolving to a 404.
Include `/blob/main` in front of the reference to the file.

Update Release Process Documentation link in PR template

---

server/utils/risksAndNeeds/pniUtils.test.ts
server/utils/risksAndNeeds/pniUtils.ts

In user research, we tested some different language in the message to update missing information.
- Layer 3 assessment was not widely understood
- OASys was understood by most, but not all, and we know it will date when OASys is replaced with ARNS
- Risk and needs scores was generally understood, although one person unfamiliar with OASys was still unsure about this
We are updating content to refer to risks and needs rather than layer 3/OASys scores.
Replace "layer 3" with "risk and need" within the missing information pathway content box.

(APG-646) Replace "layer 3" with "risk and need" in pathway content

---

package-lock.json
package.json
server/app.ts

This should close #833. It needed an intervention as `includeMeta` has been replaced with `includeSharedData` in v2.x of https://github.com/ministryofjustice/hmpps-connect-dps-components/releases.
Remove `includeMeta` as we weren't making use of anyway.  Must have been incorrectly included when we first implemented the shared components.
I have however raised [APG-747](https://dsdmoj.atlassian.net/browse/APG-747) as I think we should be using it, as well as the additional `dpsComponents.retrieveCaseLoadData`. Current scope is to update packages and doing now would take longer than we have time for at the moment.
ready to be released …

(APG-729b) Update `@ministryofjustice/hmpps-connect-dps-components` to v2

---

integration_tests/mockApis/oasys.ts
integration_tests/pages/shared/showReferral/risksAndNeeds/learningNeeds.ts
server/@types/models/LearningNeeds.ts
server/@types/models/index.d.ts
server/data/accreditedProgrammesApi/oasysClient.ts
server/services/oasysService.ts
server/testutils/factories/learningNeeds.ts
server/utils/risksAndNeeds/learningNeedsUtils.test.ts
server/utils/risksAndNeeds/learningNeedsUtils.ts

To support users understanding of a persons Learning Difficulties and Challenges (LDC), we need to show some additional information within section 4.7.
As per designs, we need to display a flag for ‘Numeracy’, ‘Reading’ or 'Writing’. This information will come from the BE. It could return any combination between none and all 3 being returned.
Our existing `LearningNeeds` type didn't match what was being returned from the API and didn't include the required `problemAreas` property.
- Remove the `LearningNeeds` type
- Use the `LearningNeeds` type from `accredited-programmes-api`

(APG-715a) Switch to use generated `LearningNeeds` type from API

---

assets/scss/overrides.scss
server/testutils/factories/learningNeeds.ts
server/utils/risksAndNeeds/learningNeedsUtils.test.ts
server/utils/risksAndNeeds/learningNeedsUtils.ts

To support users understanding of a persons Learning Difficulties and Challenges (LDC), we need to show some additional information within section 4.7.
As per designs, we need to display a flag for ‘Numeracy’, ‘Reading’ or 'Writing’. This information will come from the BE. It could return any combination between none and all 3 being returned.
- Update `LearningNeedsFactory` to randomise the problemAreas return value
- Add `.no-border` class to overrides.scss
- Update `LearningNeedsUtils.informationSummaryListRows` to show render `problemAreas` values as unordered list in a new row beneath section 4.7, but then conditionally apply the new `.no-border` css class to the above row if there are problem areas to display.
Integrations already existing for this section and use the …

(APG-715b) Add "Selected problem areas" beneath Learning needs section 4.7 

---

integration_tests/e2e/assess/caseList.cy.ts
integration_tests/mockApis/courses.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

When in case list view the strand filter currently returns the full list of possible strand values. We think it will be easier for users if they only get to see the strands that apply to that particular course/offering.
Call  `/courses/audiences=courseId=course-id` and use those values to populate the Programme strand select input on the assess case list.

(APG-641b) Use Audience values for course to populate programme strand filter

---

server/controllers/assess/index.ts
server/controllers/assess/transferReferralController.test.ts
server/controllers/assess/transferReferralController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/paths/assess.ts
server/routes/assess.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/transfer/error.njk
server/views/referrals/transfer/partials/layout.njk

Provides a mechanism for checking if a referral can be transferred to building choices and if not displaying the relevant error. This does not include the path for duplicate referrals as this is part of APG-695

APG-675 Unhappy Path Start Transfer to BC Journey

---

server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/services/referralService.test.ts
server/services/referralService.ts

We need to check for duplicate referrals before a referral can be transferred.
Add new client and service methods to check for duplicate referrals for a combination of `prisonNumber` and `offeringId`. 

(APG-695) Add new client and service methods for getting duplicate referrals

---

server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/services/courseService.test.ts
server/services/courseService.ts

We need to be able to get the target building choices course ID for original referral ID.
Add new client and service methods to get the correct building choices course ID for a given referral ID and pathway.

(APG-675) Add client and service methods for getting the target BC course by Referral ID

---

server/views/referrals/partials/changeStatusLayout.njk
server/views/referrals/updateStatus/category/show.njk
server/views/referrals/updateStatus/decision/show.njk
server/views/referrals/updateStatus/reason/show.njk
server/views/referrals/updateStatus/selection/show.njk

The upcoming transfer page shares the same layout as the update status journeys.
Move and rename existing layout template so it can be used by update status and transfer related pages.

(APG-694a) Move and rename layout used by update status related pages so it can be used for transfer too

---

server/@types/ui/index.d.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/paths/assess.ts
server/routes/assess.ts

When transferring a referral to Building Choices, we will need to still check if there is a duplicate referral to the desired BC programme and offering.
Allow existing duplicate controller method to be used by the Transfer to BC journey.
Please note: CTAs at the bottom of the page will still need to be updated, but this will happen in an upcoming PR.

(APG-695a) Prepare existing duplicate page/route to be used for Transfer to BC journey

---

server/controllers/assess/index.ts
server/controllers/assess/transferReferralController.test.ts
server/controllers/assess/transferReferralController.ts
server/controllers/assess/transferReferralErrorController.test.ts
server/controllers/assess/transferReferralErrorController.ts
server/routes/assess.ts
server/views/referrals/transfer/error/show.njk

When an existing referral cannot be transferred to an equivalent Building Choices programme then we need to display appropriate messaging.
Add new `TransferReferralErrorController` which conditionally displays the correct content, depending on the `errorMessage` value which is stored in the session.
There is an exception where the user will be redirected if there is already an existing referral to the same BC course offering for the person, aka duplicate. 
**Note:**
The gist of these changes were initially made in #869, however we would have had to duplicate a lot of the checks for the happy path.  This keeps the checks in one place (`TransferReferralController.show`) and this page just handles the errors set in the session.
General error (OAsys down etc):
Missing Information:
Alternative …

(APG-675) Transfer Referral Unhappy Paths

---

integration_tests/pages/page.ts
integration_tests/tsconfig.json
package-lock.json
package.json
server/@types/mojFrontend/index.d.ts
server/utils/nunjucksSetup.ts

We should update to the latest version of @ministryofjustice/frontend.
Will also unblock #875 
- Update to @ministryofjustice/frontend v.3.7.0
- Replace require with import
- Add types definition file for the required function
The use of the file extension is temporary until a change in an upcoming release means we can remove it.
In the meantime though, this uses the preferred import method and also updates to the latest version.

Update @ministryofjustice/frontend and use `import`

---

server/controllers/refer/index.ts
server/controllers/shared/index.ts
server/controllers/shared/updateStatusActionsController.test.ts
server/controllers/shared/updateStatusActionsController.ts
server/paths/assess.ts
server/routes/assess.ts

We will need to take the user straight into the withdraw journey from the duplicate referral page when making a transfer and there is a duplicate.
Allow `UpdateStatusActionsController` to be used by both refer and assess

(APG-695c) Withdraw duplicate

---

server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/duplicate.njk

The duplicate page needs to show different actions if it is redirected to as part of the transfer process.
- Use the presence of `transferErrorData` in the session to get the referral and the associated course name to display the "Withdraw to..." and "Cancel" buttons.
- Ensure `transferErrorData` is cleared from session before existing entry points to the duplicate page to ensure that the correct content is shown.

(APG-695d) Update duplicate page to be used for transfer journey

---

server/@types/ui/index.d.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/additionalInformation.njk

Adds custom Additional Info content to a referral transferred to building choices, including a link to the original referral.

APG-685 Add custom additional info for transferred referral

---

server/controllers/assess/transferReferralController.test.ts
server/controllers/assess/transferReferralController.ts
server/routes/assess.ts
server/views/referrals/transfer/show.njk

When transferring an existing referral to Building Choices, we need to be able to enter a reason for the transfer and submit the form.
Add `submit` method to `ReferralTransferController` with form error message if no reason is entered.
Note: Integration test PR to follow

(APG-694d) Submit a Referral transfer to Building Choices

---

server/controllers/assess/transferReferralController.test.ts
server/controllers/assess/transferReferralController.ts

We need to redirect to the new referral after transferring to building choices.
Redirect user to status history page of newly created referral.

(APG-694e) Redirect to newly created referral after transfer

---

integration_tests/e2e/assess/updateLdc.cy.ts
integration_tests/pages/assess/updateLdc.ts
integration_tests/pages/page.ts
server/controllers/assess/index.ts
server/controllers/assess/updateLdcController.test.ts
server/controllers/assess/updateLdcController.ts
server/paths/assess.ts
server/routes/assess.ts
server/utils/nunjucksSetup.ts
server/utils/stringUtils.test.ts
server/utils/stringUtils.ts
server/views/referrals/updateLdc/show.njk

We need to be able to change the LDC (Learning disabilities and challenges) status for a person, on a referral.
Add new `UpdateLdcController` with `show` method to display correct content and checkbox options
`hasLdc: false`
`hasLdc: true`

(APG-707a) Update LDC Page

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/controllers/refer/new/additionalInformationController.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/refer/new/oasysConfirmationController.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/services/referralService.test.ts
server/services/referralService.ts

In preparation for updating a referral with the new `hasLdcBeenOverriddenByProgrammeTeam` property it became clear we need to use the imported interface, rather than our hardcoded type.
- Use imported `ReferralUpdate` interface
- Remove hardcoded `ReferralUpdate` type

(APG-707b) Use imported `ReferralUpdate` interface/type

---

integration_tests/e2e/assess/updateLdc.cy.ts
server/controllers/assess/updateLdcController.test.ts
server/controllers/assess/updateLdcController.ts
server/routes/assess.ts
server/views/referrals/updateLdc/show.njk

Follows on from #920 
We need to be able to submit the decision to update the LDC status.
- Add `submit` method to update referral with `hasLdcBeenOverriddenByProgrammeTeam: true`. 
- Checkbox selections are irrelevant.  Purely a method of friction at the moment.

(APG-707c) Submit LDC Update

---

server/controllers/reportsController.test.ts
server/controllers/reportsController.ts
server/views/reports/show.njk

Adds a disclaimer to the reporting page to inform users of the period our data for referrals covers

APG-679 Add disclaimer on data time period to reports page

---

integration_tests/e2e/assess/updateLdc.cy.ts
integration_tests/pages/assess/updateLdc.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/controllers/assess/index.ts
server/controllers/assess/updateLdcController.test.ts
server/controllers/assess/updateLdcController.ts
server/views/referrals/caseList/assess/show.njk

After updating an LDC status we should redirect back to the case list and show a success message.

(APG-708) Show success banner after LDC status update

---

script/utils/generateApiTypes/accreditedProgrammesApi

Since 13.0.24 of the swagger-typescript-api the type generation we use against the ACP API OpenApi spec has been failing.
[
](url)
This has been tested to be an issue with library as it fails against other public OpenApi specs:
@
This has been raised as a problem with the library maintainers and until resolved we will force a working version rather than the latest in our script.

Force working swagger-typescript-api version for ACP API type generation

---

server/@types/accreditedProgrammesApi/index.d.ts
server/controllers/assess/updateLdcController.test.ts
server/controllers/assess/updateLdcController.ts

After some discussion, we decided to specify what the `hasLdc` value should be from front end rather than the API.
When updating the ldc status, set `hasLdc` to be the opposite of what it is currently.

(APG-707d) Set `hasLdc` value when updating ldc status on a referral

---

script/utils/generateApiTypes/accreditedProgrammesApi

Reverts the changes made in https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/924 now the issue with the underlying library has been resolved.

Revert swagger-typescript-api to use latest version

---

integration_tests/e2e/assess/caseList.cy.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/data/accreditedProgrammesApi/referralClient.test.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

**Bug 1:** LDC related strand values without "LDC Only" should get the referrals with` hasLdc=false`, so we don't include the results with LDC.
**Bug 2:** Strand filter selection should be maintained when clicking the following links:
- Open/Closed tab links
- Pagination links
- Column header sorting links

Bug: Fixes for LDC filter options in assess case list view

---

server/@types/ui/index.d.ts
server/controllers/assess/pniController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/partials/rootLayout.njk

If a referral is open, not already a building choices referral and is open in the assess journey, we display a button menu with the option to start the transfer to building choices journey.

Add button menu to referrals with transfer to BC option

---

assets/scss/local.scss
server/controllers/assess/pniController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/controllers/shared/risksAndNeedsController.test.ts
server/controllers/shared/risksAndNeedsController.ts
server/controllers/shared/statusHistoryController.test.ts
server/controllers/shared/statusHistoryController.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts

When viewing the referral for a person, we need a new CTA adding which links to the Update LDC Status page.
This is for Building Choices only (both Moderate and High intensity)
- Add Change LDC status button to button menu for referrals to Building Choices that are not closed or On Programme.
- Styling tweaks so menu button displays correctly

(APG-625) Add Change LDC Status item to button menu

---

server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts

Removed Change LDC status button in button menu, so we don't hold up releases. Will revert when LDC update has been done.

(APG-625) Temporarily remove Change LDC status button

---

integration_tests/e2e/assess/caseList.cy.ts
server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/utils/referrals/caseListUtils.test.ts
server/utils/referrals/caseListUtils.ts

This is read as a string from the URL and then passed as a string to the API. There were a number of bugs caused by then trying to use this as a boolean.

(APG-819) Change hasLdc from boolean to string

---

integration_tests/e2e/app.cy.ts
integration_tests/e2e/find.cy.ts
integration_tests/e2e/pniFind.cy.ts
server/controllers/find/personSearchController.test.ts
server/controllers/find/personSearchController.ts
server/routes/find.ts
server/views/dashboard/index.njk
server/views/find/personSearch.njk

Now the PNI is driving referrals we need to reinstate a journey for users to browse the full list of programmes. This should be for viewing purposes only. If anyone wishes to refer to an programme they will still need to do so via a PNI.
- Remove role protection from find routes so any user can access them
- Add "See a list of all programmes" link on the person search page
Note: Search functionality remains but users without the referrer role will only be able to search for people within their caseloads.

(APG-806) Add link to view all programmes for any user

---

server/@types/models/Referral.ts
server/@types/models/index.d.ts
server/controllers/assess/index.ts
server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/services/referenceDataService.ts
server/utils/referrals/referralUtils.test.ts
server/utils/referrals/referralUtils.ts
server/views/referrals/updateStatus/reason/show.njk

After the ‘Assessment started’ status the PT has the option to update the referral to ‘Assessed as suitable’. If the referral does not align with the PNI pathway (i.e. its an override) then a list of radio button options will capture the reason why the referral is deemed suitable despite the PNI mismatch. This information will be used downstream for Quality Assurance purpose.
- Compare PNI Score Programme pathway against the intensity of the course when selecting "Assessed as suitable and ready to continue".
- If there is a mismatch, it will redirect to the reason step and display a list of possible radio options.

(APG-789b) Check for override when marking a referral as Assessed as suitable and ready

---

server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/utils/risksAndNeeds/pniUtils.test.ts
server/utils/risksAndNeeds/pniUtils.ts

To help display the intensity and pathway values, along with an override reason
- Added util methods to convert pathway and intensity values into friendlier strings to display in the UI
- Added `pniMismatchSummaryListRows` method to be used on the Additional Information page

(APG-656a) Add utils to help display referrer override decision content

---

server/services/index.ts
server/services/referralService.test.ts
server/services/referralService.ts

There are now multiple places where we need to check if a referral is an override, such as:
- Additional information form when creating a referral
- Additional information page within a referral
- When submitting the pdate status decision form
Added a new method which returns the PNI programme pathway, the intensity of the course on the referral and if we then class the referral to be an override or not.

(APG-656b) Add method to check if a referral is an override

---

integration_tests/e2e/assess/show.cy.ts
integration_tests/e2e/refer/show.cy.ts
integration_tests/pages/shared/showReferral/additionalInformation.ts
integration_tests/support/sharedTests.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/additionalInformation.njk

We need to display if a referral is an override and the reason entered by the referrer on the Additional information screen within a referral.
Display new summary card and summary list on the Additonal information screen containing override details.

(APG-656c) Show referrer override details on Additional information page

---

server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/additionalInformation.njk

We are happy to show the Override summary on a referral even while there is currently no functionality to add the reason just yet.
Remove the additional conditional check for `referrerOverrideReason`.
This means that a referrer and a PT can still see if the referral is classed as an override based on the comparison of the PNI Pathway and the Course intensity values.

(APG-656d) Show override details even if there is no override reason

---

integration_tests/e2e/assess/show.cy.ts
integration_tests/pages/shared/showReferral/additionalInformation.ts
integration_tests/support/sharedTests.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/views/referrals/show/additionalInformation.njk

When a referral is identified as an override and the treatment manager determines the person is not eligible or not suitable, this should be visible in the additional details section of the referral.
Pass `treatmentManagerDecisionText` to the additional information template when the referral has been marked as `not_eligible` or `not_suitable`.

(APG-794) Show treatment manager decision for overrides

---

server/controllers/assess/pniController.test.ts
server/controllers/assess/pniController.ts
server/utils/referrals/referralUtils.test.ts
server/utils/referrals/referralUtils.ts
server/views/referrals/show/partials/rootLayout.njk
server/views/referrals/show/pni/show.njk

When a referral has been submitted and does not match the PNI, the Treatment Manager/ Programme Team is responsible for assessing a persons suitability for a programme and a referral does not align with the PNI.  We should show some additional text at the top of the Programme Needs Identifier page when the referral is classed as an override, but not On programme or Programme complete.
- Add `checkIfOverride` util method to compare PNI Programme pathway against a course intensity
- Show inset text at the top of the referral PNI page

(APG-795) Override text on PNI page

---

integration_tests/e2e/refer/new/additionalInformation.cy.ts
integration_tests/pages/refer/new/additionalInformation.ts
server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/controllers/refer/new/courseParticipationsController.test.ts
server/controllers/refer/new/courseParticipationsController.ts
server/controllers/refer/new/oasysConfirmationController.test.ts
server/controllers/refer/new/oasysConfirmationController.ts
server/testutils/factories/referral.ts
server/utils/referrals/newReferralUtils.test.ts
server/utils/referrals/newReferralUtils.ts
server/views/referrals/new/additionalInformation/show.njk

Makes the additional info step in creating a draft referral option. In addition, resets the additional info step if no details are entered and the continue option is selected.

Makes Additional Info step optional

---

server/controllers/assess/updateStatusDecisionController.test.ts
server/controllers/assess/updateStatusDecisionController.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/utils/referrals/showReferralUtils.ts

We now have some shared methods to help determine if a referral is an override that can be used in multiple places. `getPathways` and `checkIfOverride`.
Update recently added `getPathways` method to return only the pathways, which can then be passed to `checkIfOverride` util method.
Switch to use these methods in:
- `UpdateStatusDecisionController.submit` (no longer uses own private method)
- `ReferralsController.additionalInformation`
These methods can then be used in [APG-655](https://dsdmoj.atlassian.net/jira/software/c/projects/APG/boards/1435?label=Tech&selectedIssue=APG-655)
All areas where we check for an override will then be using the same methods.
[APG-655]: https://dsdmoj.atlassian.net/browse/APG-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

(APG-795) Update and use shared methods to check for override

---

server/controllers/find/addCourseController.test.ts
server/controllers/find/addCourseController.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/controllers/find/updateCourseController.test.ts
server/controllers/find/updateCourseController.ts
server/controllers/find/updateCourseOfferingController.test.ts
server/controllers/find/updateCourseOfferingController.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/controllers/reportsController.test.ts
server/controllers/reportsController.ts

Some of our service methods were incorrectly being called with the users token, instead of their username, which in turn then called auth to get the system client token.
This was also exposing the users token within App insights under `customDimensions.username`.
- Replace `user.token` with `user.username` in the places where it was incorrect.
- Updated associated tests to mock responses only when correctly called with `username`.

Fix to call correctly call `/oauth/token` with username instead of users token

---

integration_tests/e2e/find.cy.ts
integration_tests/e2e/pniFind.cy.ts
server/@types/models/CourseOffering.ts
server/controllers/find/courseOfferingsController.test.ts
server/controllers/find/courseOfferingsController.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/testutils/factories/courseOffering.ts

As part of [APG-653](https://dsdmoj.atlassian.net/browse/APG-653), the enabled organisations table is getting removed. The field `organisationEnabled `is returned when an offering is requested. 
- Remove check for courseOffering.organisationEnabled around **Make a referral** button.
- Remove `organisationEnabled` from `CourseOffering` type.
Would have preferred to use the generated `CourseOffering` type from the swagger API. However `id` can be marked as `null` because the same type is used for the creation of a course offering. 
Have discussed that we add a type type along the lines of CreateCourseOffering which omits an ID and then make CourseOffering.id non nullable. Ticket raised [here](https://dsdmoj.atlassian.net/browse/APG-895).
[APG-653]: …

(APG-849) Remove use of `organisationEnabled` for `CourseOffering`

---

integration_tests/pages/assess/transferError.ts
server/controllers/assess/transferReferralErrorController.test.ts
server/controllers/assess/transferReferralErrorController.ts

Update Transfer to BC error message that only appears when the general offence strand is not available.

(APG-845) Update BC Transfer error message when general offence strand is not offered

---

server/controllers/shared/reasonController.test.ts
server/controllers/shared/reasonController.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts

Updates the deselect and keep open page to use the filtered list of reasons

APG-837: Update deselection reasons for keep referral open

---

server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/controllers/find/index.ts
server/paths/find.ts
server/routes/find.ts
server/utils/courseUtils.test.ts
server/utils/courseUtils.ts
server/views/courses/hsp/details/show.njk

We require a new page to capture the sexual offence details before someone can be referred to HSP.
- Add basic `isHsp` util method
- Add new controller and page template for Sexual offence details page
Awaiting api endpoint before listing available options on the page and adding the form.

(APG-843) HSP Sexual offence details page

---

integration_tests/e2e/refer/new/additionalInformation.cy.ts
server/@types/accreditedProgrammesApi/index.d.ts
server/controllers/refer/new/additionalInformationController.test.ts
server/data/accreditedProgrammesApi/referenceDataClient.ts
server/paths/api.ts
server/services/referenceDataService.test.ts
server/services/referenceDataService.ts
server/testutils/factories/index.ts
server/testutils/factories/sexualOffenceDetails.ts
server/utils/courseUtils.test.ts
server/utils/referrals/referralUtils.test.ts

We need to display a list of checkboxes for the sexual offence details options.
- Update types from AcP API
- Add new test factory for SexualOffenceDetails
- Add client and service methods for calling `/reference-data/sexual-offence-details``

(APG-843) Methods to call `/reference-data/sexual-offence-details`

---

server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/controllers/find/index.ts
server/views/courses/hsp/details/show.njk

Need to display a list of checkboxes on the HSP SO Details page.
Use recently added utils to display checkboxes on Sexual offence details page.

(APG-843) Add checkboxes to sexual offence details page

---

server/controllers/find/addCourseOfferingController.test.ts
server/controllers/find/addCourseOfferingController.ts
server/controllers/find/buildingChoicesController.test.ts
server/controllers/find/buildingChoicesController.ts
server/views/courses/buildingChoices/show.njk
server/views/courses/offerings/form/show.njk

Adds a page for adding new offerings for building choices courses

APG-861: Add offering page for Building Choices

---

server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/paths/find.ts
server/routes/find.ts
server/views/courses/hsp/details/show.njk

Add submit method for the HSP details check list. This calculates the score from the selections and determines if they are eligible or ineligible for HSP.
Follow on steps to be completed in APG-887

(APG-843) Add submit method for HSP checklist

---

server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/controllers/find/hspNotEligibleController.test.ts
server/controllers/find/hspNotEligibleController.ts
server/controllers/find/index.ts
server/paths/find.ts
server/routes/find.ts
server/views/courses/hsp/notEligible/show.njk

When a referral to HSP does not meet the score threshold, we need to show a page which mentions that the person may not be eligible to be referred to HSP.
- Add new controller and template for HSP not eligible
- Update existing HSP details controller submit method to redirect to this page when they are not eligible

(APG-887) HSP Not eligible page

---

server/controllers/find/hspNotEligibleController.test.ts
server/controllers/find/hspNotEligibleController.ts
server/controllers/find/hspReferralReasonController.test.ts
server/controllers/find/hspReferralReasonController.ts
server/controllers/find/index.ts
server/paths/find.ts
server/routes/find.ts
server/views/courses/hsp/reason/show.njk

When a person has been considered not eligible for HSP but the referrer still wishes to continue, we need to allow them to enter a reason why they are continuing with the referral.
- Add new controller for reason page
- Link to new reason page from Continue referral button on the not eligible page

(APG-887) HSP referral reason

---

server/controllers/refer/new/additionalInformationController.test.ts
server/controllers/refer/new/additionalInformationController.ts
server/views/referrals/new/additionalInformation/show.njk

Fixes the issue raised by Anand that the override reason was not persisting on the additional info page when a validation error was encountered

NOTICKET: Fix persistence of override reason if additional info page errors

---

server/@types/express/index.d.ts
server/@types/ui/index.d.ts
server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/controllers/find/personSearchController.test.ts
server/controllers/find/personSearchController.ts
server/utils/referenceDataUtils.test.ts
server/utils/referenceDataUtils.ts

Before we create a referral, we need to store the selections made on the Sexual offence details page, so we can submit them along with the other referral data.
- Add `hspReferralData` to `req.session`
- Use these values to maintain those selections if a user navigates back or reloads the page
- Reset `hspReferralData` to `undefined` when a new find and refer journey begins

(APG-843) Add HSP detail selections to session

---

integration_tests/mockApis/courses.ts
integration_tests/pages/find/sexualOffenceForm.ts
server/data/accreditedProgrammesApi/courseClient.ts
server/paths/api.ts
server/services/courseService.test.ts
server/services/courseService.ts

Changes the client to use the new GET version of the BC course variants endpoint

APG-861 - Update BC variants endpoint to GET

---

server/@types/accreditedProgrammesApi/index.d.ts
server/data/accreditedProgrammesApi/organisationClient.ts
server/data/index.ts
server/paths/api.ts
server/services/index.ts
server/services/organisationService.test.ts
server/services/organisationService.ts
server/testutils/factories/sexualOffenceDetails.ts
server/utils/referenceDataUtils.test.ts

We need to use the `/organisation(s)` endpoints from AcP API rather than prison register.
- Type updates (unrelated to new functionality)
- Add new `OrganisationClient`
- Add new `OrganisationService` method to get a single organisation using new client.

(APG-910) Add methods to get organisation details from AcP API

---

server/@types/ui/index.d.ts
server/controllers/find/coursesController.test.ts
server/controllers/find/coursesController.ts
server/controllers/find/hspDetailsController.test.ts
server/controllers/find/hspDetailsController.ts
server/controllers/find/hspReferralReasonController.test.ts
server/controllers/find/hspReferralReasonController.ts
server/controllers/find/personSearchController.test.ts
server/controllers/refer/new/referralsController.test.ts
server/controllers/refer/new/referralsController.ts
server/data/accreditedProgrammesApi/referralClient.ts
server/paths/api.ts
server/services/courseService.test.ts
server/services/courseService.ts
server/services/referralService.test.ts
server/services/referralService.ts
server/views/courses/show.njk

When raising a referral to HSP, we need to call the POST /referral/hsp endpoint with the data collected in the two new HSP related form pages.

(APG-910) Create HSP referral

---

integration_tests/e2e/refer/show.cy.ts
integration_tests/mockApis/referrals.ts
integration_tests/pages/shared/showReferral/hspReferralDetailsPage.ts
integration_tests/support/sharedTests.ts
server/@types/accreditedProgrammesApi/index.d.ts
server/controllers/shared/referralsController.test.ts
server/controllers/shared/referralsController.ts
server/paths/assess.ts
server/paths/refer.ts
server/routes/refer.ts
server/utils/referrals/showReferralUtils.test.ts
server/utils/referrals/showReferralUtils.ts
server/views/referrals/show/hspDetails.njk

- Added HSP details side nav bar link under Referral Details page
- Added new HSP details page to show selected sexual offence details held against a referral and the eligibility override reason if present
- Updated unit and integration tests for new UI components

APG-907 Create HSP details page

---

server/controllers/assess/caseListController.test.ts
server/controllers/assess/caseListController.ts

[APG-945] Add audience filter to HSP referrals
